Code structure
javascript-tutorial/es.javascript.info pull request #32
Opened 2019-04-18 04:28 UTC by victorze

2019-05-27 04:38 UTC, lizzie136 requested changes
Hola @victorze , te dejé un par de comentarios. 🚀

2019-05-27 04:38 UTC, lizzie136 commented on 1-js/02-first-steps/02-structure/article.md
> +Ya hemos visto una declaración, `alert('¡Hola, mundo!')`, Que muestra el mensaje "¡Hola mundo!".
*Que muestra el mensaje* => *que muestra el mensaje*

2019-05-27 04:38 UTC, lizzie136 commented on 1-js/02-first-steps/02-structure/article.md
> +Pero deberían ser dos declaraciones separadas, no una. Tal unión en este caso es simplemente incorrecto, de ahí el error. Esto puede suceder en otras situaciones.
Creo que hablamos de *la unión* por lo que sería *simplemente incorrect**a***

2019-05-27 04:38 UTC, lizzie136 commented on 1-js/02-first-steps/02-structure/article.md
> +```smart header="¡Use accesos rapidos del teclado!"
*rápidos*

2019-07-07 03:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=32) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=32) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=32) it.</sub>

2019-09-09 22:41 UTC, tscandalitta approved these changes

2019-10-02 15:22 UTC, lizzie136 approved these changes
Me gusta como quedó, gracias!!

2019-10-02 15:22 UTC, merged