Bubbling and capturing
javascript-tutorial/es.javascript.info pull request #372
Opened 2020-09-03 05:38 UTC by mariomenjr

Traducción del artículo: https://es.javascript.info/bubbling-and-capturing

2020-09-03 05:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=372) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=372) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=372) it.</sub>

2020-09-03 09:57 UTC, joaquinelio requested changes
typos

Me gustó que usaras "manejadores".  Uso controladores para otra cosa (como... controllers)
pero otros reviewers los prefieren. Veremos

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +Usualmente no hay una necesidad real para prevenir la propagación. Una tarea que aparentemente requiere que sea resuelto por otros medios. Uno de ellas es usar eventos personalizados, cubriremos eso
Creo que esta mal la puntuacion en ingles, separa mal
entiendo mejor asi
 
Usualmente no hay una necesidad real para prevenir la propagación. Una tarea que aparentemente lo requiera puede ser resuelta por otros medios. Uno de ellos es usar eventos personalizados, cubriremos eso más tarde. También podemos escribir nuestros datos en el objeto `event` en un manejador y leerlo en otro, para así poder pasar información sobre el proceso de abajo a los manejadores en los padres.
 
cambié de opinion: y de puntuación, je:
```suggestion
Usualmente no hay una necesidad real para prevenir la propagación, pero una tarea que aparentemente lo requiera puede ser resuelta por otros medios. Uno de ellos es usar eventos personalizados, cubriremos eso más tarde. También podemos escribir nuestros datos en el objeto `event` en un manejador y leerlo en otro, para así poder pasar información sobre el proceso de abajo a los manejadores en los padres.
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +Se explica así: por un clic en `<td>` el evento va primero a través de la cadena de ancestros hacia el elemento (fase de captura), luego alcanza el objetivo y se desendena ahí (fase de objetivo), y p
```suggestion
Se explica así: por un clic en `<td>` el evento va primero a través de la cadena de ancestros hacia el elemento (fase de captura), luego alcanza el objetivo y se desencadena ahí (fase de objetivo), y por último va hacia arriba (fase de propagación), ejecutando los manejadores en su camino.
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +Los manejadores agregados usando `on<event>`-propiedad ó usando atributos HTML ó `addEventListener(event, handler)` con dos argumentos no ejecutarán la fase de captura, únicamente ejecutarán la 2da y
No estoy convencido de esto, ¿ propiedad on-event- ? supongo que sí, una con el manejador
¿o es una sintaxis  onevent-propiedad ?  (no creo)

```suggestion
Los manejadores agregados usando la propiedad `on<event>` ó usando atributos HTML ó `addEventListener(event, handler)` con dos argumentos no ejecutarán la fase de captura, únicamente ejecutarán la 2da y 3ra fase.
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +Es de notar que mientras formalmente hay 3 fases, la 2da fase ("la fase de objetivo": el evento alcanzó el elemento) no es manejada de forma separada; los manejadores en ambas fases, la de captura y
Respetemos los nros de linea
porque es importante para el merge desde el inglés

```suggestion

Es de notar que mientras formalmente hay 3 fases, la 2da fase ("la fase de objetivo": el evento alcanzó el elemento) no es manejada de forma separada; los manejadores en ambas fases, la de captura y propagación, se disparan en esa fase.
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +elem.addEventListener("click", e => alert(1)); // garantizado que se ejecutara primero
```suggestion
elem.addEventListener("click", e => alert(1)); // garantizado que se ejecutará primero
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +- Luego el evento se mueve hacia abajo desde el documento raíz hacia `event.target`, llamando a los manejadores en el camino asignados con `addEventListener(..., true)` (`true` es una abreviación par
si es la clave supongo que no se traduce
```suggestion
- Luego el evento se mueve hacia abajo desde el documento raíz hacia `event.target`, llamando a los manejadores en el camino asignados con `addEventListener(..., true)` (`true` es una abreviación para `{capture: true}`).
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +- `event.currentTarget` (=`this`) -- el elemento actual que maneja el evento (el qué tiene al manejador en él)
```suggestion
- `event.currentTarget` (=`this`) -- el elemento actual que maneja el evento (el que tiene al manejador en él)
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +Lo mismo para los manejadores de eventos. El código que se prepara en el manejador de un elemento en particular conoce el máximo de detalles sobre el elemento y qué hace. Un manejador en un `<td>` pa
```suggestion
Lo mismo para los manejadores de eventos. El código que se prepara en el manejador de un elemento en particular conoce el máximo de detalles sobre el elemento y qué hace. Un manejador en un `<td>` particular puede ser adecuado para ese exacto `<td>`, conocer todo sobre él, entonces debe tener su oportunidad primero. Luego su padre inmediato también conoce sobre el contexto, pero un poco menos, y así sucesivamente hasta el elemento de arriba que maneja conceptos generales y se ejecuta al final.
```

2020-09-03 09:57 UTC, joaquinelio commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +La propagación y captura ponen los cimientos para "delegación de eventos" -- un extremadamente poderoso patrón de manejo de eventos que se estudia en el siguiente capítulo.
```suggestion
La propagación y captura ponen los cimientos para "delegación de eventos": un extremadamente poderoso patrón de manejo de eventos que se estudia en el siguiente capítulo.
```

2020-09-04 03:06 UTC, mariomenjr commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +Es posible que `event.target` sea igual a `this` -- ocurre cuando el clic se hace directamente en el elemento `<form>`.
¡Muchas gracias por la correción!

2020-09-04 03:09 UTC, mariomenjr commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +2.  Luego decidimos atrapar los clic en toda la ventana, para seguir el rastro del comportamiento del usuario (dónde hacen clic). Algunos sistemas de análisis hacen eso. Usualmente el código usa `doc
No entendí la última parte de tu explicación, pero tienes razón con la corrección. Gracias.

2020-09-04 03:15 UTC, mariomenjr commented on 2-ui/2-events/02-bubbling-and-capturing/article.md
> +Se explica así: por un clic en `<td>` el evento va primero a través de la cadena de ancestros hacia el elemento (fase de captura), luego alcanza el objetivo y se desendena ahí (fase de objetivo), y p
Este descuido.

2020-09-04 03:40 UTC, mariomenjr commented
/done

2020-09-04 17:02 UTC, joaquinelio approved these changes
👍

2020-09-08 01:29 UTC, vplentinax approved these changes
Correcto

2020-09-08 07:12 UTC, merged