The clickjacking attack
javascript-tutorial/es.javascript.info pull request #374
Opened 2020-09-07 15:04 UTC by homero304

Please review my PR

2020-09-07 19:31 UTC, joaquinelio requested changes
Un par de cambios...
O uno repetido. El mismo cambio, 
Código, no lo probé pero apuesto a que no funciona.

2020-09-07 19:31 UTC, joaquinelio commented on 3-frames-and-windows/06-clickjacking/clickjacking-visible.view/facebook.html
> +  <input type="button" onclick="alert('¡"Me gusta" presionado en facebook.html!')" value="ME GUSTA !">
Comillas anidadas... no funcionará 
Sin comillas, o podés intentar comillas latinas, o invertidas
```suggestion
  <input type="button" onclick="alert('¡ME GUSTA fue presionado en facebook.html!')" value="ME GUSTA !">
```

2020-09-07 19:31 UTC, joaquinelio commented on 3-frames-and-windows/06-clickjacking/clickjacking.view/facebook.html
> +  <input type="button" onclick="alert('¡"Me gusta" presionado en facebook.html!')" value="ME GUSTA !">
```suggestion
  <input type="button" onclick="alert('¡ME GUSTA fue presionado en facebook.html!')" value="ME GUSTA !">
```

2020-09-07 20:50 UTC, homero304 commented
/done

2020-09-07 21:15 UTC, joaquinelio approved these changes

2020-09-08 01:44 UTC, vplentinax approved these changes
Muy fluido. Me gustó.

2020-09-08 07:14 UTC, merged