Resumable file upload
javascript-tutorial/es.javascript.info pull request #375
Opened 2020-09-07 22:40 UTC by FroggyGentlemen

2020-09-07 22:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=375) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=375) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=375) it.</sub>

2020-09-08 02:13 UTC, vplentinax requested changes
Gracias por tu contribución @FroggyGentlemen. Solo queda corregir unas faltas ortográficas que encontré para poder aprobarlo.

2020-09-08 02:13 UTC, vplentinax commented on 5-network/09-resume-upload/article.md
> +    El server deberia verificar sus registros, y en el caso de haber una carga de ese archivo, y el tamaño actual de la carga es exactamente  The server should check its records, and if there was an
```suggestion
    El servidor debe verificar sus registros, y si hubo una carga de ese archivo, y si el tamaño de carga actual es exactamente `X-Start-Byte`,  entonces agregarle los datos.
```

2020-09-08 02:13 UTC, vplentinax commented on 5-network/09-resume-upload/article.md
> +Aqui esta la demo con el codigo tento del cliente como del servidor, escrito en Node.js.
```suggestion
Aquí esta la demostración con el código tanto del cliente como del servidor, escrito en Node.js.
```

2020-09-08 02:13 UTC, vplentinax commented on 5-network/09-resume-upload/article.md
> +Esto funciona solo parcialmente en este sitio, ya que Node.js esta detras de otro servidor llamado Nginx, que almacena cargas, pasandolas a Node.js cuando esta completamente lleno.
```suggestion
Esto funciona solo parcialmente en este sitio, ya que Node.js esta detrás de otro servidor llamado Nginx, que almacena cargas, pasándolas a Node.js cuando esta completamente lleno.
```

2020-09-08 02:13 UTC, vplentinax commented on 5-network/09-resume-upload/article.md
> +Pero puedes cargarlo y ejecutarlo localmente para la demostracion completa:
```suggestion
Pero puedes cargarlo y ejecutarlo localmente para la demostración completa:
```

2020-09-08 02:13 UTC, vplentinax commented on 5-network/09-resume-upload/article.md
> +Como podemos ver, los metodos de networking modernos estan cerca de los gestores de archivos en sus capacidades -- control sobre header, indicador de progreso, enviar partes de archivos, etc.
```suggestion
Como podemos ver, los métodos de red modernos estan cerca de los gestores de archivos en sus capacidades -- control sobre header, indicador de progreso, enviar partes de archivos, etc.
```

2020-09-08 09:58 UTC, joaquinelio requested changes
Bienvenido

re-revisé-rescribí un par de lineas que me parecen mal expresadas en el original .

La primera vez que reviso con una revisión en curso, no sé si es efectivo.

@vplentinax , espero no te moleste edité 2 comentss tuyos (así no te robo crédito, ja)
("cuál" y "reanudar" en lugar de "resumir" que se te escapó)

2020-09-08 09:58 UTC, joaquinelio commented on 5-network/09-resume-upload/article.md
> +    Aqui enviamos al server ambos archivos id como `X-File-Id`, de modo que sepa que archivos estamos cargando, y el byte inicial como `X-Start-Byte`, de modo que sepa que no lo estamos cargando inic
¿A quién queres más, a mamá o a papá? 😆 

Corrijo desde la correcta corrección de Valentina.

Tampoco está mal "de modo", creo que está poniendo algo más universal.

Para no estar tan pegados al inglés "archivo id", "id del archivo"

Mmm.  Tampoco me gusta el original inglés "initially"

Mmm.  Se malinterpreta quiénes son "ambos": file-id, start-byte.  No son "ambos archivos"
En inglés está bien pero es confuso, en español no podemos estructurarlo así, 
podemos poner una coma despues de ambos, prefiero dos puntos.

Acentoss: acá estan ambas versiones de "que":
qué estamos cargando (qué archivo)
que estamos cargando (que sepa eso)

"sino", el que opone "no ese sino otro"

y las comas separando estructuras

y qué tanto floreo, es confuso. Fuera.

Debería mandar PR al inglés, el original es una porquería
Seguramente la rechaza (no soy tan bueno) pero también seguramente entiende y la reescribe

Uf, edité esto varias  veces...

AHORA se entiende.

```suggestion
    Aquí enviamos al servidor dos cosas: el id del archivo `X-File-Id`, para que sepa qué archivo estamos cargando, y el byte inicial `X-Start-Byte`, para que sepa que no estamos iniciando una carga sino reanudándola.
```

2020-09-08 09:58 UTC, joaquinelio commented on 5-network/09-resume-upload/article.md
> +    El server deberia verificar sus registros, y en el caso de haber una carga de ese archivo, y el tamaño actual de la carga es exactamente  The server should check its records, and if there was an
Aquí te dejo otro dilema.

Pero quiero que no te preocupes y sepas que a pesar de nuestras diferencias con Valentina nos seguimos queriendo.
jaja

Pero no está mal (el anterior sí) es solo una sugerencia, ignorenla si les parece rebuscado.

como purista,
    El servidor debe verificar sus registros y, si estaba cargando ese archivo y el tamaño de esa carga es exactamente `X-Start-Byte`, agregarle los datos.

pero mejor más parecido al de uds, más claro.
```suggestion
    El servidor debe verificar sus registros y, si estaba cargando ese archivo, y si el tamaño de esa carga es exactamente `X-Start-Byte`, entonces agregarle los datos.
```

2020-09-18 20:04 UTC, FroggyGentlemen commented
/done

2020-09-18 21:12 UTC, merged

2020-09-20 05:07 UTC, vplentinax commented
Emmm... yo no había revisado los cambios y tampoco aprobado....¿por qué se hizo merge?

2020-09-20 06:57 UTC, joaquinelio commented
Es que ve mi nombre y se descompone 

No es nada, lo hizo de gaucho para evitarte el dolor de leerme.

@vplentinax 
Pero le puse bastante tiempo a la reedición, me hubiera gustado que las revisaras...