URL objects
javascript-tutorial/es.javascript.info pull request #376
Opened 2020-09-07 22:43 UTC by Agus-c

hola! tuve algunas dudas con respecto a la traducción de algunas lineas (16, 17 por ej.), aunque intenté hacerlo de todas formas. lo siento, espero que no sea mucha molestia.
Ademas, vi algunas cosas raras en el original, como en la linea 65. Pero no estoy seguro de que sean errores o no (tampoco sabría como solucionarlo), así que decidí dejarlo como estaba.

2020-09-07 22:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=376) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=376) it.</sub>

2020-09-08 02:43 UTC, vplentinax requested changes
Hola @Agus-c , entiendo tus dudas con las líneas 16 y 17, son bastante confusas, pero en la línea 17 el "set" se refería al mismo "base" al que se estaba describiendo. Es decir, si se establece (base) y aparte de eso la "url" es una ruta única, entonces sucede lo que dice el resto de la línea. Realmente resultaba confuso, tardé un ratito en tomarle el sentido. 

Por todo lo demás, sólo unas correcciones ortográficas para que pueda aprobarlo. ¡Un saludo!

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +- **`url`** -- La URL completa o único path (si base está establecido, mira debajo),
```suggestion
- **`url`** -- La URL completa o ruta única (si se establece base, mira a continuación),
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +- **`base`** -- una URL base opcional: si set y el argumento `url` tiene un único path, entonces la URL es generada relativa a `base`.
```suggestion
- **`base`** - una URL base opcional: si se establece y el argumento `url` solo tiene una ruta, entonces la URL se genera relativa a la `base`.
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +Fácilmente podemos crear una nueva URL basada en el path relativo a una URL existente:
```suggestion
Fácilmente podemos crear una nueva URL basada en la ruta relativa a una URL existente:
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +## Parametros de busqueda "?..."
```suggestion
## Parámetros de búsqueda "?..."
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +Digamos que queremos crear una url con determinados parámetros de busqueda, por ejemplo, `https://google.com/search?query=JavaScript`.
```suggestion
Digamos que queremos crear una url con determinados parámetros de búsqueda, por ejemplo, `https://google.com/search?query=JavaScript`.
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +- **`delete(name)`** -- remueve el parámetro por `name`,
```suggestion
- **`delete(name)`** -- elimina el parámetro por `name`, 
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +// Iterar sobre los parametros de busqueda (Decodificados)
```suggestion
// Iterar sobre los parametros de búsqueda (Decodificados)
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +Existe un estándar [RFC3986](https://tools.ietf.org/html/rfc3986) que define cuales caracteres son permitidos en URLs y cuáles no.
```suggestion
Existe un estándar [RFC3986](https://tools.ietf.org/html/rfc3986) que define cuales caracteres son permitidos en URLs y cuales no.
```

2020-09-08 02:43 UTC, vplentinax commented on 5-network/07-url/article.md
> +Como puedes ver, ambos `Тест` en el path url y `ъ` en el parámetro están codificados.
```suggestion
Como puedes ver, ambos `Тест` en la ruta url y `ъ` en el parámetro están codificados.
```

2020-09-08 02:50 UTC, vplentinax requested changes
Disculpa, olvidé estas correcciones...

2020-09-08 02:50 UTC, vplentinax commented on 5-network/07-url/article.md
> +```smart header="Podemos pasar objetos `URL` a métodos de networking (y la mayoría de los demás) en lugar de a un string"
```suggestion
```smart header="Podemos pasar objetos `URL` a métodos de red (y la mayoría de los demás) en lugar de un string"
```

2020-09-08 02:50 UTC, vplentinax commented on 5-network/07-url/article.md
> +Generalmente, un objeto `URL` puede pasarse a cualquier método en lugar de a un string, ya que la mayoría de métodos llevarán a cabo la conversión del string, eso convierte un objeto `URL` en un stri
```suggestion
Generalmente, un objeto `URL` puede pasarse a cualquier método en lugar de un string, ya que la mayoría de métodos llevarán a cabo la conversión del string, eso convierte un objeto `URL` en un string con URL completa.
```

2020-09-08 11:32 UTC, joaquinelio requested changes
Bienvenido.

Algun cambio.

SSolemos traducir linkss, pero con MDN :
Tiene traducciones incompletas,
Es muy visible el combo de cambiar idioma
El ruso lo está cambiando por un sistema de path relativo, no me voy a poner a cambiarlo 
 
@vplentinax 
No sé si traducir path, quizas deberia etar entre la opcionales

2020-09-08 11:32 UTC, joaquinelio commented on 5-network/07-url/article.md
> +// Los parámetros son automaticamente codificados
Psé, yo digo "automaticaménte" pero...
Cosas de la RAE...
si tiene acento el original, -mente tambien

```suggestion
// Los parámetros son automáticamente codificados
```

2020-09-08 11:32 UTC, joaquinelio commented on 5-network/07-url/article.md
> +Existe un estándar [RFC3986](https://tools.ietf.org/html/rfc3986) que define cuales caracteres son permitidos en URLs y cuáles no.
3. pron. indef. m. y f. En la construcción cuál(es)… cuál(es)…, equivale a uno(s)… otro(s)… A cuál cubre, a cuál ciega, a cuál embiste.

como pronombre no lleva acento solo si es relativo "los cuales"

```suggestion
Existe un estándar [RFC3986](https://tools.ietf.org/html/rfc3986) que define cuáles caracteres son permitidos en URLs y cuáles no.
```

2020-09-08 11:32 UTC, joaquinelio commented on 5-network/07-url/article.md
> +Comparalo con `encodeURI`:
salvo que sea  un
"comparálo" porteño    =)
```suggestion
Compáralo con `encodeURI`:
```

2020-09-08 13:03 UTC, joaquinelio commented
Una review sin esperar la anterior se ve confuso, sorry no lo vuelvo a hacer.

Sobre las cosas raras, es el markdown, .md es la extensión de markdown, como los tags htm para titulos.
El git tiene uno, pero el server del repo tiene otro más evolucionado asi que el preview aca se ve distinto al online.
Podess instalar sserver local para probar formato, links , y ejercicios

2020-09-17 20:29 UTC, Agus-c commented
/done

2020-09-20 07:37 UTC, joaquinelio approved these changes
ok.
pero...

alguna duda con el acento a cuales ? por ahi lo explique mal...
ejemplo de la real academia:
"Le explicó cuáles eran sus razones."  linea 119 va acentuada 
(como pron relativo sin acento es "le explicó sus razones, las cuales...")
aprobado y que no se pierda mas tiempo, pero la suggest stands.

2020-09-20 16:50 UTC, vplentinax approved these changes
Ok

2020-09-20 19:15 UTC, merged