XMLHttpRequest
javascript-tutorial/es.javascript.info pull request #377
Opened 2020-09-09 08:31 UTC by kenliten

Full translated XMLHttpRequest to spanish

2020-09-09 13:18 UTC, joaquinelio requested changes
Es formato md, no html crudo.  No van los simbolos htm.
Y  algunos acentos más...

JA!
Tendría que habértelo dejado, pero para cuando me di cuenta ya había avanzado y me emperré...

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +    El salto de l&iacute;nea entre las cabeceras siempre es un `"\r\n"` (independiente del SO), as&iacute; podemos dividirlas en cabeceras individuales. El separador entre el nombre y el valor siempr
```suggestion
    El salto de línea entre las cabeceras siempre es un `"\r\n"` (independiente del SO), así podemos dividirlas en cabeceras individuales. El separador entre el nombre y el valor siempre es dos puntos seguido de un espacio `": "`. Eso quedó establecido en la especificación.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +    As&iacute;, si queremos obtener un objeto con pares nombre/valor, necesitamos tratarlas con un poco de JS.
```suggestion
    Así, si queremos obtener un objeto con pares nombre/valor, necesitamos tratarlas con un poco de JS.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +    Como esto (asumiendo que si dos cabeceras tienen el mismo nombre, entonces el &uacute;ltimo sobreecribe al primero):
```suggestion
    Como esto (asumiendo que si dos cabeceras tienen el mismo nombre, entonces el útimo sobreecribe al primero):
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +formData.append(name, value); // a&ntilde;ade un campo
```suggestion
formData.append(name, value); // añade un campo
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Lo creamos, opcionalmente lleno desde un formulario, `append` (agrega) m&aacute;s campos si se necesitan, y entonces:
```suggestion
Lo creamos, opcionalmente lleno desde un formulario, `append` (agrega) más campos si se necesitan, y entonces:
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +1. `xhr.open('POST', ...)` – se utiliza el m&eacute;todo `POST`.
```suggestion
1. `xhr.open('POST', ...)` – se utiliza el método `POST`.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +  // agrega un campo m&aacute;s
```suggestion
  // agrega un campo más
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +El formulario fue enviado con codificaci&oacute;n `multipart/form-data`.
```suggestion
El formulario fue enviado con codificación `multipart/form-data`.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +O, si nos gusta m&aacute;s JSON, entonces, un `JSON.stringify` y lo enviamos como un string.
```suggestion
O, si nos gusta más JSON, entonces, un `JSON.stringify` y lo enviamos como un string.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Solo no te olvides de asignar la cabecera `Content-Type: application/json`, muchos frameworks del lado del servidor decodifican autom&aacute;ticamente JSON con este:
```suggestion
Solo no te olvides de asignar la cabecera `Content-Type: application/json`, muchos frameworks del lado del servidor decodifican automáticamente JSON con este:
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +El m&eacute;todo `.send(body)` es bastante omnivoro. Puede enviar casi cualquier `body`, incluyendo objetos `Blob` y `BufferSource`.
```suggestion
El método `.send(body)` es bastante omnívoro. Puede enviar casi cualquier `body`, incluyendo objetos `Blob` y `BufferSource`.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Si estamos subiendo algo grande, entonces seguramente estaremos interesados en rastrear el progreso de nuestra carga. Pero `xhr.onprogress` no ayuda aqu&iacute;.
```suggestion
Si estamos subiendo algo grande, entonces seguramente estaremos interesados en rastrear el progreso de nuestra carga. Pero `xhr.onprogress` no ayuda aquí.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Hay otro objeto, sin m&eacute;todos, exclusivamente para rastrear los eventos de subida: `xhr.upload`.
```suggestion
Hay otro objeto, sin métodos, exclusivamente para rastrear los eventos de subida: `xhr.upload`.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +&Eacute;ste genera eventos, similares a `xhr`, pero `xhr.upload` se dispara solo en las subidas:
```suggestion
Este genera eventos similares a `xhr`, pero `xhr.upload` se dispara solo en las subidas:
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +- `load` -- carga finalizada con exito.
```suggestion
- `load` -- carga finalizada con éxito.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +- `timeout` -- carga caducada (si la propiedad `timeout` esta asignada).
```suggestion
- `timeout` -- carga caducada (si la propiedad `timeout` está asignada).
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +- `loadend` -- carga finalizada con exito o error.
```suggestion
- `loadend` -- carga finalizada con éxito o error.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Aqu&iacute; un ejemplo de la vida real: indicaci&oacute;n del progreso de subida de un archivo:
```suggestion
Aquí un ejemplo de la vida real: indicación del progreso de subida de un archivo:
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +`XMLHttpRequest` puede hacer solicitudes de origen cruzado, utilizando la misma pol&iacute;tica CORS que se [solicita](info:fetch-crossorigin).
```suggestion
`XMLHttpRequest` puede hacer solicitudes de origen cruzado, utilizando la misma política CORS que se [solicita](info:fetch-crossorigin).
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Tal como `fetch`, no env&iacute;a cookies ni autorizaci&oacute;n HTTP a otro origen por omisi&oacute;n. Para activarlas, asigna `xhr.withCredentials` como `true`:
```suggestion
Tal como `fetch`, no envía cookies ni autorización HTTP a otro origen por omisión. Para activarlas, asigna `xhr.withCredentials` como `true`:
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Ve el cap&iacute;tulo <info:fetch-crossorigin> para detalles sobre las cabeceras de origen cruzado.
```suggestion
Ve el capítulo <info:fetch-crossorigin> para detalles sobre las cabeceras de origen cruzado.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Codificaci&oacute;n t&iacute;pica de la solicitud GET con `XMLHttpRequest`:
```suggestion
Codificación típica de la solicitud GET con `XMLHttpRequest`:
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +De hecho hay m&aacute;s eventos, la [especificaci&oacute;n moderna](http://www.w3.org/TR/XMLHttpRequest/#events) los lista (en el orden del ciclo de vida):
```suggestion
De hecho hay más eventos, la [especificación moderna](http://www.w3.org/TR/XMLHttpRequest/#events) los lista (en el orden del ciclo de vida):
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +- `progress` -- un paquete de datos de la respuesta ha llegado, el cuerpo completo de la respuesta al momento est&aacute; en `response`.
```suggestion
- `progress` -- un paquete de datos de la respuesta ha llegado, el cuerpo completo de la respuesta al momento está en `response`.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +- `error` -- un error de conecci&oacute;n ha ocurrido, ej. nombre de dominio incorrecto. No pasa con errores HTTP como 404.
```suggestion
- `error` -- un error de conexión ha ocurrido, ej. nombre de dominio incorrecto. No pasa con errores HTTP como 404.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +- `timeout` -- la solicitud fue cancelada debido a que caduc&oacute; (solo pasa si se hab&iacute;a configurado).
```suggestion
- `timeout` -- la solicitud fue cancelada debido a que caducó (solo pasa si fue configurado).
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +- `loadend` -- se dispara despu&eacute;s de `load`, `error`, `timeout` o `abort`.
```suggestion
- `loadend` -- se dispara después de `load`, `error`, `timeout` o `abort`.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Los eventos m&aacute;s usados son la carga terminada (`load`), falla de carga (`error`), o podemos usar un solo `loadend` manejador y comprobar las propiedades del objeto solicitado `xhr` para ver qu
```suggestion
Los eventos más usados son la carga terminada (`load`), falla de carga (`error`), o podemos usar un solo manejador `loadend` y comprobar las propiedades del objeto solicitado `xhr` para ver qué ha pasado.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Ya hemos visto otro evento: `readystatechange`. Hist&oacute;ricamente, apareci&oacute; hace mucho tiempo, antes de que la especificaci&oaucte;n fuera colocada. Hoy en d&iacute;a, no es necesario usar
```suggestion
Ya hemos visto otro evento: `readystatechange`. Históricamente, apareció hace mucho tiempo, antes de que la especificación fuera publicada. Hoy en día no es necesario usarlo, podemos reemplazarlo con eventos más nuevos pero puede ser encontrado a menudo en scripts viejos.
```

2020-09-09 13:18 UTC, joaquinelio commented on 5-network/08-xmlhttprequest/article.md
> +Si necesitamos rastrear espec&iacute;ficamente, entonces debemos escuchar a los mismos eventos en el objeto `xhr.upload`.
```suggestion
Si necesitamos rastrear específicamente, entonces debemos escuchar a los mismos eventos en el objeto `xhr.upload`.
```

2020-09-14 07:10 UTC, kenliten commented
/done

2020-09-14 13:42 UTC, joaquinelio approved these changes
👍 

Me gustó que hayas puesto "nativo", 
mucho más que "incorporado" que no es muy intuitivo y como se entiende de inmediato no sugerí el cambio...
Es más, lo pondría en el glosario... aunque ya tenemos demasiado avanzado.
Es más, sugeriría un cambio masivo.
Es más, iría a MDN a cambiarlo ahí... aunque hay cosas peores.

2020-09-14 23:03 UTC, vplentinax approved these changes
¡Fuímonos!

2020-09-15 02:18 UTC, merged