Browser default actions
javascript-tutorial/es.javascript.info pull request #378
Opened 2020-09-11 03:14 UTC by homero304

please review my PR

2020-09-11 11:36 UTC, joaquinelio requested changes
Creo que no hay errores y todas son sugerencias de estilo, aplicala s o cambialas si queres

2020-09-11 11:36 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/article.md
> +Técnicamente, al evitar acciones predeterminadas y agregar JavaScript, podemos personalizar el comportamiento de cualquier elemento. Por ejemplo, podemos hacer que un enlace `<a>` funcione como un bo
eh...  sí, confuso, pero ¿mas o menos? 
"presione este link para mas o menos visitar nuestro sitio"  jjaj.  Aclaro que me rio del original.
y la ssugerencia no cambia demaiado pero creo que va mejor
```suggestion
Técnicamente, al evitar acciones predeterminadas y agregar JavaScript, podemos personalizar el comportamiento de cualquier elemento. Por ejemplo, podemos hacer que un enlace `<a>` funcione como un botón, y un botón `<button>` se comporte como un enlace (redirigir a otra URL o algo así).
```

2020-09-11 11:36 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/article.md
> +Además, si consideramos el ejemplo con `<a>`, ten en cuenta: un navegador nos permite abrir dichos enlaces en una nueva ventana (haciendo clic con el botón derecho en ellos y por otros medios). Y a l
No está nada mal, pero queda demasiado largo en español. acorto un poquito
```suggestion
Además, si consideramos el ejemplo con `<a>`, ten en cuenta: un navegador nos permite abrir dichos enlaces en una nueva ventana (usando el botón derecho u otros medios). Y a la gente le gusta. Pero si hacemos que un botón se comporte como un enlace usando JavaScript e incluso parezca un enlace usando CSS, las características específicas de `<a>` no funcionarán en él.
```

2020-09-11 11:36 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/article.md
> +Las opciones `passive: true` le dicen al navegador que el controlador no va a cancelar el desplazamiento. Luego, el navegador se desplaza de inmediato para brindar una experiencia con la máxima fluid
Dos cosas... Odio cambiar "then" por "entonces" en todos lados, pero acá es la consecuencia :
Si sabe que no cancelará "ENTONCES" lo hace ya.
El evento es manejado "al vuelo"... (no necesita busscar el prevent). tengo que encontrar mejor expresion

```suggestion
Las opciones `passive: true` le dicen al navegador que el controlador no va a cancelar el desplazamiento.  Entonces el navegador se desplaza de inmediato para brindar una experiencia con la máxima fluidez, y el evento se maneja de inmediato.
```

2020-09-11 11:36 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
> +Cuando el navegador lee el atributo `on*` como `onclick`, crea el controlador a partir de su contenido.
"el" me confundió.  
No respeto original:
```suggestion
Cuando el navegador lee un atributo `on*` como `onclick`, crea el controlador a partir de su contenido.
```

2020-09-11 11:36 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
> +Ese es un gran uso del patrón de delegación de eventos.
No sé explicarlo...
sugerencia nomas

```suggestion
Ese es un gran uso para el patrón de delegación de eventos.
```

2020-09-11 11:36 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/3-image-gallery/source.view/index.html
> +    <!-- el navegador muestra un tooltip(ya viene integrado) con el texto del atributo "title" al pasar el ratón sobre él -->
```suggestion
    <!-- el navegador muestra un tooltip (ya viene integrado) con el texto del atributo "title" al pasar el ratón sobre él -->
```

2020-09-11 13:30 UTC, homero304 commented
/done

2020-09-12 08:16 UTC, joaquinelio requested changes
¿me disculpas que haya agregado mas cosas?  de estilo tambien

salvo un acento faltante que note haciendo zoom

2020-09-12 08:16 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/article.md
> +<input *!*onmousedown="return false"*/!* onfocus="this.value=''" value="Haz clic en mi">
```suggestion
<input *!*onmousedown="return false"*/!* onfocus="this.value=''" value="Haz clic en mí">
```

2020-09-12 08:16 UTC, joaquinelio commented on 2-ui/2-events/04-default-browser-action/article.md
> +Pero, en general, deberíamos mantener el significado semántico de los elementos HTML. Por ejemplo, `<a>` debe realizar la navegación, no un botón.
sugerencia...
demasiadas comas. No essta mal, aislan complemento. pero no creo que se lea mejor-

Y la 2da tampoco me parece bien expresada
```suggestion
Pero en general deberíamos mantener el significado semántico de los elementos HTML. Por ejemplo, la navegación debe realizarla `<a>`, no un botón.
```

2020-09-12 15:46 UTC, homero304 commented
/done

2020-09-12 22:52 UTC, joaquinelio approved these changes
👍

2020-09-14 23:08 UTC, vplentinax approved these changes
Bien!

2020-09-15 02:19 UTC, merged