Server Sent Events
javascript-tutorial/es.javascript.info pull request #381
Opened 2020-09-17 21:12 UTC by homero304

please review my PR

2020-09-20 06:53 UTC, joaquinelio requested changes
muy claro, tá bueno
un par de cositas nomás

2020-09-20 06:53 UTC, joaquinelio commented on 5-network/12-server-sent-events/article.md
> +`EventSource` admite solicitudes cross-origin, como `fetch` cualquier otro método de red. Podemos utilizar cualquier URL:
no suena bien, tampoco en ingles´ creo.   
```suggestion
`EventSource` admite solicitudes cross-origin, como `fetch` y cualquier otro método de red. Podemos utilizar cualquier URL:
```

2020-09-20 06:53 UTC, joaquinelio commented on 5-network/12-server-sent-events/article.md
> +Aquí está el servidor que envía mensajes con `1`,` 2`, `3`, luego `bye` y cierra la conexión.
Con font fijo se nota mucho el mal espaciado.
```suggestion
Aquí está el servidor que envía mensajes con `1`, `2`, `3`, luego `bye` y cierra la conexión.
```

2020-09-20 12:22 UTC, homero304 commented
/done

2020-09-20 14:02 UTC, joaquinelio requested changes
sorry por la vuelta
una que sugerí me molesta,

y otra que molestaba no supe sugerir antes.

Molesta tambien lo de "cross origin", no traducirlo ni explicarlo, 
pero linkea a FETCH en este mismo capitulo y es donde lo explica asi que es correcto que quede así.

2020-09-20 16:51 UTC, vplentinax approved these changes
Ok!

2020-09-20 20:27 UTC, homero304 commented
/done

2020-09-21 03:59 UTC, joaquinelio approved these changes

2020-09-21 03:59 UTC, merged