Template element
javascript-tutorial/es.javascript.info pull request #384
Opened 2020-09-21 18:37 UTC by RocioC1207

Hola! Espero sus correcciones. 
Saludos!

2020-09-21 18:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=384) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=384) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=384) it.</sub>

2020-09-21 21:33 UTC, joaquinelio requested changes
Muy, bueno, encontré solo un acento y un signo ! de apertura

Me permití arreglar los números de linea. Necesitamos que coincidan para facilitar la review y epecialmente los sync con el repo inglés.

¡AY! casi se me escapan:  Acá no afectan porque en el ejemplo no lo usan, pero: 
no se traducen variables, ni classes y id del html (se llama refactoring ja!)
podrian ntroducir fallos, especialmente si se usaran en css y js externos

2020-09-21 21:33 UTC, joaquinelio commented on 8-web-components/4-template-element/article.md
> +Normalmente, si intentamos poner `<tr>` dentro, digamos, un `<div>`, el navegador detecta la estructura DOM invalida y la “Arregla”, y añade un `<table>` alrededor. Eso no es lo que queremos. Por otr
```suggestion
Normalmente, si intentamos poner `<tr>` dentro, digamos, un `<div>`, el navegador detecta la estructura DOM inválida y la “arregla”, y añade un `<table>` alrededor. Eso no es lo que queremos. Por otro lado, `<template>` mantiene exactamente lo que ponemos allí.
```

2020-09-21 21:33 UTC, joaquinelio commented on 8-web-components/4-template-element/article.md
> +El contenido template está disponible en su propiedad `content` como un [DocumentFragment](info:modifying-document#document-fragment) -- un tipo especial de nodo DOM.
El -- es un markup del server que no se ve en git, es un guion largo que en español no lo usamos igual. Lo dejamos en listas, pero normalmente se reemplaza por dos puntos, a veces coma.
```suggestion
El contenido template está disponible en su propiedad `content` como un [DocumentFragment](info:modifying-document#document-fragment): un tipo especial de nodo DOM.
```

2020-09-21 21:33 UTC, joaquinelio commented on 8-web-components/4-template-element/article.md
> +       elem.shadowRoot.getElementById('message').innerHTML = "!Saludos desde las sombras!";
```suggestion
    elem.shadowRoot.getElementById('message').innerHTML = "¡Saludos desde las sombras!";
```

2020-09-21 21:33 UTC, joaquinelio commented on 8-web-components/4-template-element/article.md
> +  <div class="Mensaje">¡Hola mundo!</div>
id y class son como nombres de variables, no se traducen 
```suggestion
  <div class="message">¡Hola mundo!</div>
```

2020-09-21 21:33 UTC, joaquinelio commented on 8-web-components/4-template-element/article.md
> +  <p id="mensaje"></p>
```suggestion
  <p id="message"></p>
```

2020-09-21 21:33 UTC, joaquinelio commented on 8-web-components/4-template-element/article.md
> +    <p id="mensaje"></p>
```suggestion
    <p id="message"></p>
```

2020-09-21 23:54 UTC, RocioC1207 commented
/done

2020-09-22 02:26 UTC, joaquinelio approved these changes
👍

2020-09-22 02:38 UTC, joaquinelio commented on 8-web-components/4-template-element/article.md
> +En la línea `(*)`, cuando clonamos e insertamos `tmpl.content`, como su `DocumentFragment`, sus “hijos” (`<style>`, `<p>`) se insertan en su lugar.
@RocioC1207 
Perdón que me meta de nuevo... Me incomodaba esto pero no supe qué poner y respetaba el original,
ahora lo entendí: y veo que sobra una coma en el original (suele poner de más incluso para el inglés aunque me lo niegue) 
Pero es así:

"...cuando insertamos X como fragmento,  Zs  se insertan en su lugar" 

```suggestion
En la línea `(*)`, cuando clonamos e insertamos `tmpl.content` como su `DocumentFragment`, sus “hijos” (`<style>`, `<p>`) se insertan en su lugar.
```

2020-09-22 18:25 UTC, joaquinelio commented
👍 👍 
segunda review? 
no estaría mal una de una frontend... @vplentinax

2020-09-23 16:51 UTC, vplentinax requested changes
Muy bueno, corregí algunas estructuras de frases y eliminé comillas que no eran necesarias. Por lo demás, correcto. Esperaré los cambios para aprobarlo

2020-09-23 16:51 UTC, vplentinax commented on 8-web-components/4-template-element/article.md
> +En teoría, podríamos crear cualquier elemento invisible en algún lugar de HTML par fines de almacenamiento de HTML markup. ¿Qué es especial sobre `<template>`?
```suggestion
En teoría, podríamos crear cualquier elemento invisible en algún lugar de HTML par fines de almacenamiento de HTML markup. ¿Qué hay de especial en `<template>`?
```

2020-09-23 16:51 UTC, vplentinax commented on 8-web-components/4-template-element/article.md
> +Normalmente, si intentamos poner `<tr>` dentro, digamos, un `<div>`, el navegador detecta la estructura DOM inválida y la “arregla”, y añade un `<table>` alrededor. Eso no es lo que queremos. Por otr
```suggestion
Normalmente, si intentamos poner `<tr>` dentro, digamos, de un `<div>`, el navegador detecta la estructura DOM como inválida y la “arregla”, y añade un `<table>` alrededor. Eso no es lo que queremos. Sin embargo, `<template>` mantiene exactamente lo que ponemos allí.
```

2020-09-23 16:51 UTC, vplentinax commented on 8-web-components/4-template-element/article.md
> +Podemos tratarlo como a cualquier otro nodo DOM, excepto por una propiedad especial: cuando lo insertamos en algún lugar, sus “hijos” son insertados en su lugar.
```suggestion
Podemos tratarlo como a cualquier otro nodo DOM, excepto por una propiedad especial: cuando lo insertamos en algún lugar, sus hijos son insertados en su lugar.
```

2020-09-23 16:51 UTC, vplentinax commented on 8-web-components/4-template-element/article.md
> +En la línea `(*)`, cuando clonamos e insertamos `tmpl.content` como su `DocumentFragment`, sus “hijos” (`<style>`, `<p>`) se insertan en su lugar.
```suggestion
En la línea `(*)`, cuando clonamos e insertamos `tmpl.content` como su `DocumentFragment`, sus hijos (`<style>`, `<p>`) se insertan en su lugar.
```

2020-10-07 00:06 UTC, vplentinax commented
Hola @RocioC1207 ! Te he dejado unas pequeñas correcciones para que las revises y podamos aprobar tu PR, en cuanto te sea posible, sólo queremos saber si aún sigues activa en la repo. 

Gracias!

2020-10-07 00:08 UTC, vplentinax commented
@joaquinelio  Revisando este PR me di cuenta que viene de la rama "master"... ¿Afectará en algo eso? Creo que @RocioC1207 deberá rehacer el PR desde una nueva rama como hemos sugerido en el (README)[https://github.com/javascript-tutorial/es.javascript.info/blob/master/README.md]

2020-10-07 00:10 UTC, vplentinax commented
@joaquinelio  Revisando este PR me di cuenta que viene de la rama "master"... ¿Afectará en algo eso? Creo que @RocioC1207  deberá rehacer el PR desde una nueva rama como hemos sugerido en el [README](https://github.com/javascript-tutorial/es.javascript.info/blob/master/README.md)

2020-10-07 00:26 UTC, joaquinelio commented
Que sea SU master No nos afecta.

2020-10-07 00:42 UTC, joaquinelio commented
FIRME recomendación es mantener el master propio limpio, pero solo es comodidad para uno.

Entonces:  Tenes TU fork
Mantenes tu master limpio y actualizado,
haces branch, alteras branch (y te lo alteran si los dejas) y si se acepta y se incorpora al repo, ya podes borrar el branch con confianza. 
Luego en TU MASTER solamente haces un pull y todo queda atualizado  y prolijo, 

Al Modificar el master 
No podes hacer simultáneamente una segunda modificacion sin tener la basura de la primera 
Si algo se modifica, un pull puede no dejarlos iguales (ejempl si se rechaza una de las modificaciones), 
Se arregla facil (ja, me enseñaste cómo) pero MUCHO mas facil es trabajar con diferentess branchs

Pero al  PR no le importa de donde vienen los commits.

2020-10-07 00:55 UTC, joaquinelio commented
Y si no aparece votaria por merge igual,
De acuerdo con quitar comillas a "hijos" que distraen y remarcan algo que deberia leerse naturalmente,
las otras suggest no las entendi del todo, apruebo con o sin

2020-10-09 16:40 UTC, vplentinax commented
> Que sea SU master No nos afecta.

No afectará en este PR. Para el próximo PR que cree sí afectará, porque creará nueva rama desde master y esta contendrá los commits que master tenga. Por ello la recomendación en README. Lo mejor es que una vez aprobado este PR, @RocioC1207  elimine su fork y su repo local, y vuelva a crearlo desde 0. Así su master estará limpio y comenzará siguiendo nuestra recomendación: Nueva rama para cada nuevo PR

2020-10-09 19:10 UTC, joaquinelio commented
Ah, perdón @vplentinax, contestaba a "si deberá rehacer el PR" y no, no haria falta.
 
Tambien puse "se arregla fácil" no puse cómo
git reset --hard upstream/master
aunque NO es buena práctica acotumbrarse a los reset, deberia ser algo excepcional.
Lo mejor es siempre trabajar branchs, todos los que quieras, y no borrarlos hasta que sabes que ya no los necesitas.

git reset si trabaja local, si edita online ni idea, pero en ese caso borrar y rehacer el fork despues de este PR sería muy simple.

2020-10-09 19:14 UTC, joaquinelio commented
Y parece que @RocioC1207 se cansó de nosotros...

=)

2020-10-15 22:01 UTC, RocioC1207 commented
Hola!
Quiero disculparme por mi ausencia, tuve un mes complicado.
Gracias por las correcciones!

2020-10-15 22:02 UTC, RocioC1207 commented
/done

2020-10-18 13:39 UTC, danilobrinu approved these changes

2020-10-19 16:24 UTC, vplentinax approved these changes
Ok

2020-10-20 00:31 UTC, joaquinelio commented
@danilobrinu gracias por tomarte el tiempo de leerlo

En este caso habia los dos reviews, una completa y la otra en proceso, por eso no di merge a pesar de tener tu aprobacion

Tambien notaras que el bot no te registra. Los maintainers sí, a veces los pr quedan demorados por falta de review asi que siempre es bueno tener uno más que revise.

2020-10-20 00:31 UTC, merged

2020-10-20 00:37 UTC, danilobrinu commented
@joaquinelio sii recien me di cuenta, por cierto ya estoy libre para apoyar en los reviews :D

2020-10-20 00:59 UTC, joaquinelio commented
@danilobrinu ok!
Fui flexibilizando con el tiempo, algunas cosas son regionales y se pueden mejorar, otras pueden quedar, unos dicen accesar y otros acceder, unos traducen array y otros no,  algunas cosas hacen a la fluidez, salvo que sea ortografia evidente siempre pongo el porqué
No se tu expertise, el problema ahora lo tengo con cosas conceptuales, huelo los problemas de código pero no trabajé en produccion con html, async, net request. 
Pero hassta la correccion de typos es útil.