Update article.md
javascript-tutorial/es.javascript.info pull request #385
Opened 2020-09-21 22:11 UTC by MrC0D

Traducción casi finalizada, faltan pulir detalles en lo referente al uso de términos y la gramática, estoy atento a consejos.

2020-09-21 22:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=385) it.</sub>

2020-09-22 02:08 UTC, joaquinelio reviewed
Hola!
Lo primero que noto son los números de línea, necesitamos que respeten exactamente el original,
facilita la review y ESPECIALMENTE permiten un buen diff con el master ingles para las actualizaciones, 
gracias
   
No miré la traducción, y para glosario me gustaría la colaboración de 

                      @cortizg 

que anduvo con esto de los patrones y que es buen reviewesero =)

2020-10-07 01:48 UTC, vplentinax requested changes
Gracias por tu colaboración @MrC0D . Quisiera recomendarte mucha precaución con el tema de las líneas por varias razones ya mencionadas por @joaquinelio :

1. Dificulta la sincronización del repositorio
2. Dificulta la revisión

A parte de esto, también te sugiero prestar atención a las faltas otrográficas:
- Espacios tras puntos.
- Mayúsculas tras puntos
- Acentos 

Hacer bien esto nos permitirá  a los reviwers hacer unas revisiones más rápidas y así avanzar más rápido.

Gracias!

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +alert( str.match(/\d+(?=€)/) ); // 30, el numero 1 es ignorad0, por que no tiene al lado a €
```suggestion
alert( str.match(/\d+(?=€)/) ); // 30, el número 1 es ignorado, porque no está seguido de €
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +por favor nota: el mirar adelante es solamente una prueba,lo contenido en los parentesis `pattern:(?=...)` no es incluido en el resultado `match:30`.
```suggestion
Por favor tenga en cuenta: "mirar hacia delante" es solamente una prueba, lo contenido en los paréntesis `pattern:(?=...)` no es incluido en el resultado `match:30`.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Cuando buscamos por `pattern:X(?=Y)`, el  buscador de expresion regular encuentra `pattern:X` y luego verifica si existe algun `pattern:Y` inmediatamente despues de el.Si no se cumple, entonces la po
```suggestion
Cuando buscamos por `pattern:X(?=Y)`, el  buscador de expresión regular encuentra `pattern:X` y luego verifica si existe algún `pattern:Y` inmediatamente después de él. Si no se cumple, entonces la posible coincidencia es omitida, y la búsqueda continua.    
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
>  More complex tests are possible, e.g. `pattern:X(?=Y)(?=Z)` means:
```suggestion
Es posible realizar pruebas más complejas, e.j. `pattern:X(?=Y)(?=Z)` significa:
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Pruebas mas complejas son posibles, ejemplo.`pattern:X(?=Y)(?=Z)` significa:
```suggestion

```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +1. encuentra `pattern:X`.
```suggestion
1. Encuentra `pattern:X`.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +2. Verifica si `pattern:Y` es inmediatamente despues de `pattern:X` (omitir si no es).
```suggestion
2. Verifica si `pattern:Y` está inmediatamente después de `pattern:X` (omitir si no es así).
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +3. Verifica si `pattern:Z` es también inmediatamente después de `pattern:X` (omitir si no es).
```suggestion
3. Verifica si `pattern:Z` está también inmediatamente después de `pattern:X` (omitir si no es así).
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +En otras palabras, dicho patron significa que estamos buscando por `pattern:X` seguido de `pattern:Y` y `pattern:Z` al mismo tiempo.
```suggestion
En otras palabras, dicho patrón significa que estamos buscando por `pattern:X` seguido de `pattern:Y` y `pattern:Z` al mismo tiempo. 
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Por ejemplo, `pattern:\d+(?=\s)(?=.*30)` busca por `pattern:\d+` solo si es seguido por un espacio, y si hay `30` en algun lugar despues de eso:
```suggestion
Por ejemplo, `pattern:\d+(?=\s)(?=.*30)` busca por `pattern:\d+` solo si es seguido por un espacio, y si hay `30` en algún lugar después de eso:
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +En nuestra cadena eso coincide exactamente con el numero `1`.
```suggestion
En nuestra cadena eso coincide exactamente con el número `1`. 
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Digamos que queremos una cantidad, no un precio de la misma cadena.Eso es el numero `pattern:\d+`, NO seguido por `subject:€`.
```suggestion
Digamos que queremos una cantidad, no un precio de la misma cadena. Eso es el número `pattern:\d+`, NO seguido por `subject:€`.  
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Por eso, una mirada hacia delante negativa puede ser aplicada.
```suggestion
Por eso se puede aplicar una "mirada hacia delante negativa" ("negative lookahead").
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +La sintaxis es: `pattern:X(?!Y)`, la cual significa "busca `pattern:X`, pero solo si es seguido por `pattern:Y`".
```suggestion
La sintaxis es: `pattern:X(?!Y)`, que significa "busca `pattern:X`, pero solo si no es seguido por `pattern:Y`".
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Mirar adelante permite agregar a una condicion para "que sigue".
```suggestion
Mirar hacia delante permite agregar a una condicion para "lo que sigue".
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Mirar atras es similar, pero mira detras. Eso es, permite coincidir un patron solo si hay algo antes de el.
```suggestion
Mirar hacia atrás es similar. Es decir, permite coincidir un patrón solo si hay algo antes de el.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +- Mirar atras positivo: `pattern:(?<=Y)X`, coincide `pattern:X`, pero solo si hay `pattern:Y` antes de el.
```suggestion
- Mirar hacia atrás positivo: `pattern:(?<=Y)X`, coincide `pattern:X`, pero solo si hay `pattern:Y` antes de el.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +- Mirar atras negativo: `pattern:(?<!Y)X`, coincide `pattern:X`, pero solo si no hay `pattern:Y` antes de el.
```suggestion
- Mirar hacia atrás negativo: `pattern:(?<!Y)X`, coincide `pattern:X`, pero solo si no hay `pattern:Y` antes de el.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Por ejemplo,cambiemos el precio a dolares estadounidenses. El signo de dollar usualmente va antes del numero, entonces miramos por `$30` usaremos `pattern:(?<=\$)\d+` -- una cantidad precedida por `s
```suggestion
Por ejemplo,cambiemos el precio a dólares estadounidenses. El signo de dólar usualmente va antes del número, entonces para buscar `$30` usaremos `pattern:(?<=\$)\d+` -- una cantidad precedida por `subject:$`: 
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +// el signo de dolar es escapado \$
```suggestion
// el signo de dólar se ha escapado \$
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +alert( str.match(/(?<=\$)\d+/) ); // 30 (omitido el numero)
```suggestion
alert( str.match(/(?<=\$)\d+/) ); // 30 (omitido el número)
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Y, si necesitamos la cantidad -- un numero, no precedida por  `subject:$`,entonces podemos usar un mirar atras negativo `pattern:(?<!\$)\d+`:
```suggestion

```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
>  And, if we need the quantity -- a number, not preceded by `subject:$`, then we can use a negative lookbehind `pattern:(?<!\$)\d+`:
```suggestion
Y, si necesitamos la cantidad -- un número, no precedida por  `subject:$`,entonces podemos usar mirar hacia atrás negativo `pattern:(?<!\$)\d+`: 
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Generalmente, los contenidos dentro de los parentesis de mirar alrededor no se convierten en parte del resultado.
```suggestion
Generalmente, los contenidos dentro de los paréntesis de "mirar alrededor" (lookaround) no se convierten en parte del resultado.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Ejemplo en el patron `pattern:\d+(?=€)`, el `pattern:€` signo no es capturado como parte de la coincidencia. Eso es esperado: buscamos un numero `pattern:\d+`, mientras `pattern:(?=€)` es solo una pr
```suggestion
Ejemplo en el patrón `pattern:\d+(?=€)`, el signo `pattern:€`  no es capturado como parte de la coincidencia. Eso es esperado: buscamos un número `pattern:\d+`, mientras `pattern:(?=€)` es solo una prueba que debería ser seguida por `subject:€`.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Pero en algunas situaciones nosotros podriamos querer el capturar la expresion mirar alrededor, o parte de ella. Eso es posible. solo hay que rodear esa parte por parentesis adicionales
```suggestion
Pero en algunas situaciones nosotros podríamos querer capturar la expresión mirar alrededor, o parte de ella. Eso es posible. Solo hay que rodear esa parte por paréntesis adicionales.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +let regexp = /\d+(?=(€|kr))/; // parentesis extra alrededor de €|kr
```suggestion
let regexp = /\d+(?=(€|kr))/; // paréntesis extra alrededor de €|kr
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Y esto es lo mismo para mirar atrás:
```suggestion
Y esto es lo mismo para "mirar hacia atrás":
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Mirar adelante y mirar atras (comúnmente conocido como "mirar alrededor") son útiles cuando nos gustaría hacer coincidir algo dependiendo del contexto antes / después.
```suggestion
"Mirar hacia delante" y "mirar hacia atrás" (en conjunto conocidos como "mirar alrededor") son útiles cuando nos gustaría hacer coincidir algo dependiendo del contexto antes / después.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Para simples expresiones regulares podemos hacer lo mismo maualmente. Esto es:coincidir todo, en cualquier contexto, y luego filtrar por contexto en el bucle.
```suggestion
Para simples expresiones regulares podemos hacer lo mismo maualmente. Esto es: coincidir todo, en cualquier contexto, y luego filtrar por contexto en el bucle.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Recuerda,`str.match` (sin el indicador `pattern:g`) y `str.matchAll` (siempre) retorna coincidencias como un arreglo con la propiedad `index`, ´pr ñp cual sabemos donde exactamente esta en el texto,
```suggestion
Recuerda,`str.match` (sin el indicador `pattern:g`) y `str.matchAll` (siempre) retorna coincidencias como un array con la propiedad `index`,  para que sepamos exactamente dónde está en el texto, y poder comprobar el contexto.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +Pero generalmente mirar alrededor es mas conveniente.
```suggestion
Pero generalmente "mirar alrededor" es más conveniente.
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +tipos de mirar alrededor:
```suggestion
Tipos de "mirar alrededor":
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +| Patron             | tipo             | coincidencias |
```suggestion
| Patrón             | Tipo             | Coincidencias |
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +| `X(?=Y)`   | Mirar adelante positivo | `pattern:X` si es seguido por `pattern:Y` |
```suggestion
| `X(?=Y)`   | Mirar hacia delante positivo | `pattern:X` si es seguido por `pattern:Y` |
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +| `X(?!Y)`   | Mirar adelante negativo | `pattern:X` si no es seguido por `pattern:Y` |
```suggestion
| `X(?!Y)`   | Mirar hacia delante negativo | `pattern:X` si no es seguido por `pattern:Y` |
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +| `(?<=Y)X` |  Mirar atras positivo | `pattern:X` si es despues de `pattern:Y` |
```suggestion
| `(?<=Y)X` |  Mirar hacia atrás positivo | `pattern:X` si es después de `pattern:Y` |
```

2020-10-07 01:48 UTC, vplentinax commented on 9-regular-expressions/14-regexp-lookahead-lookbehind/article.md
> +| `(?<!Y)X` | Mirar atras negativo | `pattern:X` si no es despues de `pattern:Y` |
```suggestion
| `(?<!Y)X` | Mirar hacia atrás negativo | `pattern:X` si no es después de `pattern:Y` |
```

2020-12-04 06:49 UTC, joaquinelio commented
Hello @vplentinax 

1 que hacemos con este pr? "draft"
nros de linea, ortografia, faltan las tareas
pero no seria dificil arreglarlo, ya pusiste varios acentos  Y las tareas las puedo poner como issue

2 qué tanto te molesta "mirar adelante /atrás" ?
"mirar hacia adelante" me suena innecesariamente largo, hasta redundante,
pero rae dice que es tema regional, 
si te es apenas raro, prefiero como está 
si en cambio te suena a error, lo ponemos a tu española manera (¿y qué dicen los colombianos?).

2021-02-16 18:46 UTC, joaquinelio commented
@vplentinax 
el branch esta vivo aunque el autor no
la tomo  para no desperdiciar trad y tus correcciones, y  le agrego la task

2021-02-16 21:23 UTC, vplentinax commented
> @vplentinax
> el branch esta vivo aunque el autor no
> la tomo para no desperdiciar trad y tus correcciones, y le agrego la task

Si puedes hacerte cargo estaría bien... 
Por cierto, espero que el autor también esté vivo!

2021-02-16 22:46 UTC, joaquinelio commented
Ugh.
tengo que "cuidar mi lenguaje"

hiciste montones de correcciones, las acepte todas, 
resolvi 2 conflictos.... 
en un art de poco más de 100 lineas jajaj, los coment son mas largos
todo por respetar los 2 autores 

tengo problems con lookahead lookbehind.  No es una palabra, es una contraccion para manejarse mejor
en ruso le puso "anticipatorio retrospectiva
"mirar hacia delante"  me suena feo, largo y redundante pero bue, DRAE dice que es regional y lo acepte

pero es impractico
mira esto

>También podemos unirlos en un solo `lookbehind ` aquí:

"en un solo mirar hacia delante  aqui: "  ??

y hay frases con varios lookahead /behind
quiza invente
`verdelante`
no se que poner

2021-02-18 19:02 UTC, joaquinelio commented
@vplentinax 
antes de que corrijas explico motivos de los mas polemicos 
 
* linea 3 preceder y anteceder son sinonimos ( es "precede / sucede" pero "sucede" confundiria)

* en unix usabamos "look-ahead" incluso en traducciones, cortito y practico.  Lo hubiera dejado ingles.
Como no es un comando ni palabra clave prefiero "ver delante" asi entre comillas (porque significa: "revisar lo que tenés delante")
Lo veo importante para no embarrar frases con varios "mirar hacia delante", es imposible no distraerse.
Ah, "ver delante" es correcto en España y latam, (www.fundeu.es/recomendacion/adelante/) aunque "coloquiemos" distinto.

Pero en MDN aparece como sugeriste "mirar hacia delante", no suelo hacerle caso porque su Esp suele ser incoherente... aunque no acá.
Más que gramática me encantaria tener opinion de @cortizg  u otro experimentado acá, pero si no, aceptaría tu veto.

* 36 esta mal, la reescribi
y la reescribí bastante distinto en PR ingles (seguro Ilya rechaza pero deberia corregirlo de algun modo)

* Debería haber corregido el codigo y vuelto los string de nuevo al ingles, no lo hice. Pereza.

2021-03-02 10:11 UTC, joaquinelio commented
No puedo respetar a MDN.  En una explicación ponen 

"mirar hacia delante" 
"mirar hacia atras"

pero depues
"aserción de búsqueda anticipada "
"aserción de búsqueda inversa "

que no tienen sentido, 
ademas "anticipo" es para tiempo, no posición. 

correcto:
de subsecuencia 
de precedencia 

comodo:
derecha
izquierda  
o
posterior
anterior

pero sigo con "ver delante - ver detras" salvo que lo vetes, te sigo.

2021-06-18 08:29 UTC, joaquinelio commented
art cortisimo, pero mucho trbjo de 3 personas
MERGE

2021-06-18 08:30 UTC, merged