Shadow DOM
javascript-tutorial/es.javascript.info pull request #386
Opened 2020-09-22 05:09 UTC by joaquinelio

y sombras serán

No pude traducir las herramientas de chrome porque lo tengo en inglés:
More tools > developer tools > (engranaje) > show user agent shadow dom
agregárelo quien pudiere

2020-09-23 16:59 UTC, vplentinax requested changes
¿En qué línea está lo que dices?

2020-09-23 16:59 UTC, vplentinax commented on 8-web-components/3-shadow-dom/article.md
> +1. Light tree -- un subárbol normal, hecho de HTML hijos. Todos los subárboles vistos en capítulos previos eran "light".
```suggestion
1. Light tree -- un subárbol normal, hecho de hijos HTML. Todos los subárboles vistos en capítulos previos eran "light".
```

2020-09-23 16:59 UTC, vplentinax commented on 8-web-components/3-shadow-dom/article.md
> +Así es como el DOM resultante se ve in las herramientas de desarrollador de Chrome, todo el contenido está bajo "#shadow-root":
```suggestion
Así es como el DOM resultante se ve en las herramientas de desarrollador de Chrome, todo el contenido está bajo "#shadow-root":
```

2020-09-23 17:37 UTC, joaquinelio commented
linea 15
necesitamos habilitar la opción "Show user agent shadow DOM" en "herramientas".

Supongo, que es "herramientas", supongo que es "herramientas de desarrollo"
pero no queria adivinar  "Show user agent shadow DOM"

2020-09-23 17:57 UTC, joaquinelio commented
/done

2020-10-07 00:18 UTC, vplentinax requested changes
Si, en las herramientas de desarrollo.

2020-10-07 00:18 UTC, vplentinax commented on 8-web-components/3-shadow-dom/article.md
> +El navegador usa DOM/CSS internamente para dibujarlos. Esa estructura DOM normalmente está oculta para nosotros, pero podemos verla con herramientas de desarrollo. Por ejemplo en Chrome, necesitamos
```suggestion
El navegador usa DOM/CSS internamente para dibujarlos. Esa estructura DOM normalmente está oculta para nosotros, pero podemos verla con herramientas de desarrollo. Por ejemplo en Chrome, necesitamos habilitar la opción "Show user agent shadow DOM" en las heramientas de desarrollo.
```

2020-10-07 01:00 UTC, joaquinelio commented
Ok.
¿buscaste "Show user agent shadow DOM"?

2020-10-07 02:03 UTC, vplentinax commented
Haz merge, ya que tu eres como el segundo "reviwer" y así avanzamos antes.

2020-10-07 02:58 UTC, joaquinelio commented
Es que me había entusiasmado ahora que parecía concurrido...

Pero está, bien, el procedimiento lo permite.

2020-10-07 03:00 UTC, merged