Types
javascript-tutorial/es.javascript.info pull request #391
Opened 2020-09-28 18:46 UTC by maksumi

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
> +- `NaN` representa un error computacional. Es el resultado de una operación matemática incorrecta o indefinida, por ejemplo:
```suggestion
- `NaN` representa un error de calculo. Es el resultado de una operación matemática incorrecta o indefinida, por ejemplo:
```

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
> +    `NaN` es "pegajoso". Cualquier otra operación sobre `NaN` retorna `NaN`:
```suggestion
    `NaN` es "pegajoso". Cualquier otra operación sobre `NaN` devuelve `NaN`:
```

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
> +let str2 = 'Las comillas individuales también están bien';
```suggestion
let str2 = 'Las comillas simples también están bien';
```

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
> +2. Comillas individuales: `'Hola'`.
```suggestion
2. Comillas simples: `'Hola'`.
```

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
> +Las comillas dobles e individuales son comillas "simples". No hay diferencia entre ellas en JavaScript.
```suggestion
Las comillas dobles y simples son comillas "sencillas" (es decir, funcionan igual). No hay diferencia entre ellas en JavaScript.
```

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
>  ## Un boolean (tipo lógico)
```suggestion
## Booleano (tipo lógico)
```

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
> +El tipo boolean (booleano) tiene sólo dos valores: `verdadero` y `falso`.
```suggestion
El tipo booleano tiene sólo dos valores: `true` y `false`.
```

2020-09-28 22:35 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
> +Este tipo se utiliza comúnmente para almacenar valores de sí/no: `verdadero` significa "sí, correcto", y `falso` significa "no, incorrecto".
```suggestion
Este tipo se utiliza comúnmente para almacenar valores de sí/no: `true` significa "sí, correcto, verdadero", y `false` significa "no, incorrecto, falso".
```

2020-09-28 22:40 UTC, maksumi commented on 1-js/02-first-steps/05-types/article.md
>  ## Un boolean (tipo lógico)
```suggestion
## Booleano (tipo lógico)
```

2020-09-29 03:22 UTC, joaquinelio commented on 1-js/02-first-steps/05-types/article.md
> +Las comillas dobles e individuales son comillas "simples". No hay diferencia entre ellas en JavaScript.
¿"(es decir funcionan igual)"?
ambas son sencillas porque son sencillas (es decir sin artificios) 
Y ADEMAS funcionan igual

no me fije como esta el original, supongo que mal pero no amerita pr

2020-09-29 03:34 UTC, joaquinelio commented
hola amigo @maksumi 
Puse una objeción que no tiene que ver con tus correctas correcciones.

Y reafirmaste que debo refinar el procedimiento de syncs, 
este archivo (y otros 75) debia haber estado en un issue
Y otra vez, me deprimi y deje uno casi terminado por ejemplo, dejare procedimiento mas expeditivo como legado. 
Y veo que no revisaste ingles (no te estoy criticando, tampoco lo hice) porque "uno o mas caracteres" es un error que esta corrigiendo el sync local que tengo pendiente

A medida que se va terminando cosas que tenian prioridad algo menor se van haciendo importantes.
estas re-revisiones por ejemplo
pero ojo con abusarte y sobrescribir la voluntad de traductores originales jajajaj

2020-09-29 04:31 UTC, maksumi commented
Hola @joaquinelio 
Qué gusto de nuevo, de hecho sí revisé inglés y comenté la necesidad de actualizar la traducción del artículo a lo que Eze me sugirio hacer pr (lamentablemente hice la observación en el medio equivocado *dicord* y ahora comprendo que hubiera sido mejor un issue). En el artículo en inglés dice "zero o más caracteres" pero decidí mantener la traducción que se había realizado ya que haciendo pruebas en la consola en realidad no puedes almacenar un string vacío, es `undefined`. Respecto a la onda del flujo de trabajo más bien creo que es cusetión de mejorar la comunicación y no lo digo por ti. Creo que no me he dado el tiempo suficiente a leer los issues pendientes. Sea como sea, estamos para ayudarnos

2020-09-29 05:26 UTC, joaquinelio commented
sigo deprimido, el sync sinc despegar en la notebook solo tengo que hacer push, 
pero no me gusta como lo deje... y no quiero arreglarlo...

me puse a revisar esto mejor me puse a analizar y me cuesta definirme asi que lo deje sin terminar 
me opongo a algunas cosas,
pero cada renglon es diferente, habla de tipo *number* no deberias traducirlo
en otro lado estaba "una cadena blabla " y lo pasaste a string, 
no es coherente y ademas propongo exactamente lo contrario

el tipo se llama number, "el tipo *number*"
pero si estas explicando "un numero es blabla" esta ok
pero es dificil cada renglon 

como sea, ahora uso mucho mas español que antes, 
varios lados "backticks"
y  cambiaste "acento grave" por comillas, 
en realidad "como comillas" las inventamos los programadores, son acentos.
y no usaria nunca "backticks", pondria siempre español (el nuestro) "comillas invertidas" salvo la primera aparicion "... (backticks)
tenemos que pensarlo un poco para no andar escribiendo y sobrescribiendo...

no me deja sugerir un "¿" linea 7

y algunos cambios pffff

¿por que sacaste acento de calculo? jajaj

let vacio   // undefined
vacio = ""    // ZERO chars
que no puedas hacer let x = "" es otra de las porquerias de JS

bue, disculpame que no termine esta review
me vuá dormir
ta luego

que tiene de malo discord,
comenta donde quieras, toda herramienta ess valida
no me estoy metiendo git ni discord, solo reacciono al inbox de git
me obligo a hacer review para no desanimar al que publica algo

2020-09-29 06:40 UTC, joaquinelio commented
¡¡¡!!!!
No hago review porque ofrece terminar la pendiente y no quiero

linea 69, creo que hice un pr específicamente para juntarlos, 
¿por qué los separaste? Se va a ver mal

ademas pondria number...
jeje

ah, rompiste el codigo linea 115
dejen de traducir y destraducir codigo, se rompe.

2020-10-01 02:14 UTC, maksumi commented
Hola amigo @joaquinelio 
Maldición, hay algo mal aquí y por eso se está rompiendo esto. No sé por qué no recibo notificaciones en cuánto subes comentarios y review, LLevaba rato esperandolo, creo que es la raíz de que suceda esto

2020-10-01 02:47 UTC, joaquinelio commented
hello...
1 configuré para que la campanita se ilumine ante cualquier cambio del repo, asi que no sé como son las notificaciones parciales

2 solo usso la campanita, el bookmark que tengo abre notificaciones directamente, ese inbox es perfecto para estar al dia

3 las notificaciones por mail demoran un poco, creo que git quiere asegurarse antes de mandarla. je.

2020-10-07 00:13 UTC, vplentinax approved these changes
Ok

2020-10-07 01:07 UTC, joaquinelio commented
Yo no creo que debamos decir "tipo numero"
Si dice "tipo" es "number", 
si no dice "tipo", es perfecto "numero" en castellano.

igual no logre consistencia en esta review que deje a medio hacer, hagan lo que quieran.

Por perezoso no hice el super sync pull de 30+ archivos, ahora susy aumentó a 60+

2020-10-07 01:15 UTC, joaquinelio requested changes
Lo tenia a medias
No lo revise muy bien
borre algunos suggest que dudaba, para no retrasar con discusion

objecion al  tipo "numero"

2020-10-07 01:50 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +El tipo *número* representa tanto números enteros como de punto flotante.
Concuerdo contigo, lo leí rápido parece que no me di cuenta.

2020-10-07 01:55 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +Toma en cuenta que esto sólo se puede hacer con los backticks. ¡Las otras comillas no tienen esta capacidad de incrustación!
Prefiero "backticks".

2020-10-07 01:57 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +En algunos idiomas, hay un tipo especial "carácter" para un solo carácter. Por ejemplo, en el lenguaje C y en Java es `char`.
Prefiero "lenguaje". "Idioma" lo utilizo más para referirme a los idiomas que hablamos los humanos, y "lenguaje" al que hablan las máquinas... Cosas mías, pero, al leerlo en un artículo de software o programación prefiero "lenguaje".

2020-10-07 02:00 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +Los backticks son comillas de "funcionalidad extendida". Nos permiten incrustar variables y expresiones en una cadena de caracteres encerrándolas en `${...}`, por ejemplo:
Prefiero dejar "Los backticks son comillas..."

2020-10-07 02:01 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +alert( `Hola, *!*${name}*/!*!` ); // Hola, John!
De acuerdo con Joa

2020-10-07 02:41 UTC, joaquinelio commented on 1-js/02-first-steps/05-types/article.md
> +Los backticks son comillas de "funcionalidad extendida". Nos permiten incrustar variables y expresiones en una cadena de caracteres encerrándolas en `${...}`, por ejemplo:
ok, me suena más natural porque estoy habituado a backticks en ingles...
pero sigo dudando si deberiamos usar ingles aca

2020-10-07 02:42 UTC, joaquinelio commented on 1-js/02-first-steps/05-types/article.md
> +Toma en cuenta que esto sólo se puede hacer con los backticks. ¡Las otras comillas no tienen esta capacidad de incrustación!
¡Ufa!
diría Mafalda
pero ok.  Por lo menos no el problema de "comillas" que no son.

2020-10-07 02:48 UTC, joaquinelio commented on 1-js/02-first-steps/05-types/article.md
> +En algunos idiomas, hay un tipo especial "carácter" para un solo carácter. Por ejemplo, en el lenguaje C y en Java es `char`.
jaj pero las maquinas no tienen lengua...
como sea, "lenguaje de programación" es vox populi.

2020-11-20 21:04 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +3. Backticks (comillas invertidas): <code>&#96;Hola&#96;</code>.
Me quedo con acento grave

2020-11-20 21:05 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +Las comillas dobles y simples son comillas "sencillas" (es decir, funcionan igual). No hay diferencia entre ellas en JavaScript.
Comillas simples...

2020-11-20 21:16 UTC, vplentinax requested changes
Me atreví a aceptar las sugerencias de cambios viendo el tiempo tan avanzado que llevamos con este PR abierto y sin señales de @maksumi 

Dos sugerencias de cambios más.

2020-11-20 21:16 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +En algunos idiomas, hay un tipo especial "carácter" para un solo carácter. Por ejemplo, en el lenguaje C y en Java es `char`.
```suggestion
En algunos lenguajes, hay un tipo especial "carácter" para un solo carácter. Por ejemplo, en el lenguaje C y en Java es `char`.
```

2020-11-20 21:16 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +- `boolean` para `tru`/`false`.
```suggestion
- `boolean` para `true`/`false`.
```

2020-11-20 22:39 UTC, joaquinelio approved these changes

2020-11-20 22:39 UTC, joaquinelio commented on 1-js/02-first-steps/05-types/article.md
> +Los lenguajes de programación que permiten estas cosas, como JavaScript, se denominan "dinámicamente tipados", lo que significa que allí hay tipos de datos, pero las variables no están vinculadas a n
@vplentinax 
Quiero cambiar esto, me parece conceptual y se nos pasó.

BIND puede ser casi siempre "Vincular", pero en realidad es más  apegado,  atado, 

la variable sí esta vinculada a un tipo, pero no atada para siempre a él.
no suena bien "la variable no está atada /apegada/ soldada al tipo "  si se te ocurre algo plis

si no hay palabra exacta prefiero estirar la explicacion

, pero las variables no están vinculadas a ninguno de ellos
a 
, las variables están siempre vinculadas uno de ellos pero no en forma permanente.

o algo asi

2020-11-20 22:42 UTC, joaquinelio approved these changes

2020-11-20 22:42 UTC, joaquinelio commented on 1-js/02-first-steps/05-types/article.md
> +Los lenguajes de programación que permiten estas cosas, como JavaScript, se denominan "dinámicamente tipados", lo que significa que allí hay tipos de datos, pero las variables no están vinculadas a n
in tanta vuelta
rígidamente
o 
permanentemente

```suggestion
Los lenguajes de programación que permiten estas cosas, como JavaScript, se denominan "dinámicamente tipados", lo que significa que allí hay tipos de datos, pero las variables no están vinculadas rígidamente a ninguno de ellos.
```

2020-12-17 16:54 UTC, vplentinax commented on 1-js/02-first-steps/05-types/article.md
> +Los lenguajes de programación que permiten estas cosas, como JavaScript, se denominan "dinámicamente tipados", lo que significa que allí hay tipos de datos, pero las variables no están vinculadas a n
Aceptado

2020-12-17 16:55 UTC, vplentinax approved these changes
Listo. Por mi se puede hacer merge.

2020-12-17 18:11 UTC, merged