Introduction to browser events
javascript-tutorial/es.javascript.info pull request #392
Opened 2020-09-28 20:24 UTC by maksumi

2020-09-29 15:52 UTC, joaquinelio requested changes
algunas cosas.

algunas son dudas.

No me gusta "luce" como verse o mostrarse (deberia ponerse "se luce como" que es peor), no es buen español (y encima lucir tiene connotacion de exhibicion, no solo mostrar), pero ahora todos los periodistas lo traducen así, mal. Asi que a nadie va a molestar y lo  va a entender  rapido asi que no lo corregi

2020-09-29 15:52 UTC, joaquinelio commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Toma en cuenta que dentro de `onclick` usamos comillas sencillas, porque el atributo en sí va entre comillas dobles. Si olvidamos que el código está dentro del atributo y usamos comillas dobles dentr
No sé si correhgir esto...
segun la rae es "comillas simples"
pero también segun la rae, las dobles son "comillas inglesas", no dobles jaj 

```suggestion
Toma en cuenta que dentro de `onclick` usamos comillas simples, porque el atributo en sí va entre comillas dobles. Si olvidamos que el código está dentro del atributo y usamos comillas dobles dentro, así:  `onclick="alert("Click!")"`, no funcionará correctamente.
```

2020-09-29 15:52 UTC, joaquinelio commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +    - `capture`: la fase en la que se controla el evento, que será cubierta en el capítulo <info:bubbling-and-capturing>. Por históricas razones, `options` también puede ser `false/true`, lo que es i
```suggestion
    - `capture`: la fase en la que se controla el evento, que será cubierta en el capítulo <info:bubbling-and-capturing>. Por razones históricas, `options` también puede ser `false/true`, lo que es igual a `{capture: false/true}`.
```

2020-09-30 18:24 UTC, maksumi commented
/done

2020-09-30 18:25 UTC, maksumi commented
Respecto a lo de sólido. Entiendo la confusión pero una vez dominado se entiende que se refiere en relatividad al contenido. Po cierto, mu buen ojo con esos detalles, gracias como siempre

2020-09-30 19:25 UTC, joaquinelio approved these changes

2020-10-01 16:15 UTC, vplentinax commented on 2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
> +# ¿Qué handlers se ejecutan?
Correcto, pero tengo una duda ¿no hemos traducido handler en anteriores artículos? Creo que es mejor mantener esa consistencia. No importa si se traduce como manejador o controlador, pero creo que es mejor traducirlo.

2020-10-01 16:28 UTC, maksumi commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +## Manejadores de eventos
```suggestion
## Controladores de eventos
```

2020-10-01 16:28 UTC, maksumi commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Para reaccionar con eventos podemos asignar un *handler (manejador)* el cual es una función que se ejecuta en caso de un evento.
```suggestion
Para reaccionar con eventos podemos asignar un *handler (controlador)* el cual es una función que se ejecuta en caso de un evento.
```

2020-10-01 16:32 UTC, maksumi commented
Hola @vplentinax 
Tu duda se encuentra resuelta en la linea 29 y 31 del article. Había traducido por manejadores pero me convence más controladores y lo actualice así

2020-10-01 16:36 UTC, vplentinax approved these changes
Ok!

2020-10-02 00:19 UTC, joaquinelio commented
Ja ja, lo que pasa es que @maksumi me hizo trampa,
esperó a que aprobara y despues lo cambió

Muchass cosas no nos ponemos de acuerdo, por eso el respeto a lo que decide el que traduce

En la ssync que no termine porque sigo por el piso, 
un articulo @vplentinax usa  controladorr y cuando tuve que agregar algo use controlador, 
si bien no es bueno tener desacuerdos en  conceptos 
peor es la falta de consistencia dentro de un mimo articulo

en este caso no me gusta usar la missma palabra para diferentes conceptos
JS no tiene controllers, pero handler es un método, una funcion mundana que paseamos 
controller suele ser un objeto mas complejo y poderoso, o una interfaz 
¿seguro? no, me hubiera gustado la opinion de alguien mas veterano

lo que no podemos es frenar todo por buscar lo perfecto
o hacer asamblea en cada articulo

2020-10-02 18:49 UTC, joaquinelio commented
@maksumi 

molessta esto aca che

crei que habias cambiado texto ¿vas a modificarlo? si decidiss cambiar solo esa palabra por todos lados no problem, sigue aprobado

pero que quede esto aca ocioso... faltando solo 1 para quebrar el numero 30...

30 faltantes para terminar. 10 aun por reclamar

el unico que deje reclamado en julio es el fatidico proxy, je

2020-10-02 19:08 UTC, maksumi commented
Estoy trabajando en el fatidico Proxy de hecho, pero ese lo llevo a poco. Gracias por avisar. Ya estaba revisando cuál tomar
@joaquinelio

2020-10-02 19:08 UTC, merged