Transltion of sum to task and solution
javascript-tutorial/es.javascript.info pull request #400
Opened 2020-10-06 15:02 UTC by Arnau-Ninerola

Traducción de la tarea y solución de 1.6.1.1 sum to

2020-10-06 19:20 UTC, joaquinelio requested changes
FIRST!

Jajajaj perdón el chiste, hablando de spammy teens...

OK! 
Es una traducción cuidada... 

negociemos.
Traducciones parciales suma,  pero consideramos algo traducido si suma artículo, tareas y soluciones.   
Es porque si no el control se volvería demasiado arduo.

Por mi parte lo apruebo si en otro pr agregas los demás ejercicios, 

Por favor, no hagas 5 PR con 5 tasks, eso sí sería "low quality PR" obligándonos a 10 review, para un par de renglones preferiría hacer un commit directo.

2020-10-06 19:20 UTC, joaquinelio commented on 1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
> +P.P.S. Algunos motores admiten la optimización de "tail call": si una llamada recursiva es la última en la función (como en la función anterior `sumTo`), entonces la función externa no necesitará rea
Deberiamos aclarar "optimización de cola"? 
supongo que como la explicacion viene seguida no hace falta

No sé si en español tenemos post posdata, 
pero bueno...

```suggestion
P.P.D. Algunos motores admiten la optimización de "tail call": si una llamada recursiva es la última en la función (como en la función anterior `sumTo`), entonces la función externa no necesitará reanudar la ejecución, por lo que el motor no necesita recordar su contexto de ejecución. Eso elimina la carga en la memoria, así que contar `sumTo(100000)` resulta posible. Pero si el motor de JavaScript no soporta la optimización "tail call" (la mayoría no lo hacen), entonces habrá  un error: exceso del tamaño máximo de la pila, porque generalmente hay una limitación en el tamaño total de la pila.
```

2020-10-06 19:46 UTC, Arnau-Ninerola commented on 1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
> +P.S. Naturalmente, la fórmula es la solución más rápida. Utiliza solo 3 operaciones para cualquier número `n` ¡Las matemáticas ayudan!
Lo estuve investigando y he visto que posdata (o postdata) pueden ser intercambiados por post scriptum (P.S.) y quería dejarlo así ya que el P.S.S. no se cambia al español así resulta menos confuso creo. Pero lo cambio a posdata si quieres.

De wikipedia:

> Es intercambiable con post scriptum (P. S.), "después de lo escrito". Siendo en la actualidad costumbre de fechar las cartas en el encabezado, y sin hablar de incorrección, podría ser preferible el término post scriptum (P. S.) para ese fin, al menos en ese contexto.

2020-10-06 20:02 UTC, Arnau-Ninerola reviewed
> Es porque si no el control se volvería demasiado arduo.

Lo entiendo, haré las otras en un solo PR, solo lo hice por qué ya la tenía lista.

2020-10-06 20:50 UTC, joaquinelio commented on 1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
> +P.S. Naturalmente, la fórmula es la solución más rápida. Utiliza solo 3 operaciones para cualquier número `n` ¡Las matemáticas ayudan!
👍 

Debi poner post posdata si quería "corregirlo"

Igual, no uso la wiki como referencia de español, pero sí fundeu, acá aceptan también P.S.

https://www.fundeu.es/recomendacion/posdata-postdata-como-se-escribe/

"easy points" podes revisar el repo ya que habrá otross casos de P.P.D.    jaja

2020-10-06 20:52 UTC, joaquinelio approved these changes
👍 
thanks for the schooling

2020-10-06 21:19 UTC, Arnau-Ninerola commented on 1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
> +P.S. Naturalmente, la fórmula es la solución más rápida. Utiliza solo 3 operaciones para cualquier número `n` ¡Las matemáticas ayudan!
Como tú veas, si quieres lo cambio a P.D. ya que es lo más habitual. Más delante puedo revisar lo de P.P.D. y cambiarlos todos los que encuentre en un solo PR pero me voy a centrar en traducciones completas por ahora.

2020-10-06 21:22 UTC, maksumi commented
Yo lo vengo manejando como  P.D. y P.P.D., creo que es lo que se ha venido manejando como estándar en este tutorial

2020-10-06 21:41 UTC, Arnau-Ninerola commented
Ningún problema, arreglado.

2020-10-06 21:56 UTC, joaquinelio commented on 1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
> +P.S. Naturalmente, la fórmula es la solución más rápida. Utiliza solo 3 operaciones para cualquier número `n` ¡Las matemáticas ayudan!
Ya está aprobado, PS es correcto, lo deje sin resolver por si otro lo lee.
cambiar los PDD que hubiera por PSS  es un poco broma (por lo de easy points) hay otras prioridades pero si lo haces, apruebo, es más perfectón .

2020-10-06 22:07 UTC, joaquinelio commented
eh? ah, hola alex comente recien y no te habia visto, habia aprobado PS PPS 
PD es habitual, pero cierto PPD no...

bue, da igual, 
prioridades, si hubieramos hecho asamblea cada punto esto estaría estancado
igual, creo que tenemos un buen producto y esto es buena adición

P.S.
Por "esto" me refiero a la traduccion no a Don Arnau jjjajj

2020-10-07 00:04 UTC, vplentinax approved these changes
Realmente no recuerdo como lo he estado traduciendo, pero tampoco pretendo hacer discusión por eso.

2020-10-07 00:21 UTC, joaquinelio commented
Amo las discusiones, especialmente si mejora el resultado aún en nimiedades.
Me convenció, 
sogo pensando que PD es mejor por habitual, 
pero PS es válido y PPS quizas preferible, -ahora pienso que no tanto como para cambiar los ya hechos-

Pero de acuerdo en NO FRENAR un merge por una discusión bizantina  

Va, 
but the issue stands.

2020-10-07 00:21 UTC, merged