Styles and classes
javascript-tutorial/es.javascript.info pull request #413
Opened 2020-10-08 17:47 UTC by danilobrinu

2020-10-08 17:49 UTC, danilobrinu commented
@vplentinax el archivo de `2-ui/1-document/08-styles-and-classes/solution.md` esta vacío

2020-10-08 17:55 UTC, vplentinax commented
@danilobrinu Comprueba si en la repo de inglés está vacío también.

2020-10-08 18:04 UTC, danilobrinu commented
@vplentinax en el repo original también lo está.

**repo original:** https://github.com/javascript-tutorial/en.javascript.info/blob/master/2-ui/1-document/08-styles-and-classes/2-create-notification/solution.md

2020-10-08 18:11 UTC, vplentinax commented
Pues entonces no hay problema. No hay contenido. No se traduce nada.

2020-10-09 04:22 UTC, joaquinelio commented
@vplentinax  @danilobrinu 
pienen como programadores!!

"server" precisa estructura rigida, 
cuando encuentra article lo agrega, numera y titula sin que nadie tenga que ponerlo en una lista, 
cuando ve task + solution  los pone al final del article sin que nadie necesite ponerlo explicitamente
probablemente  solution vacio habilita el boton, quizas con solamente el link al sandbox

nota:
El boton y link  a sandbox de "solution" está bien traducido, pero 
¿no les parece qie suena un poco raro? copio:
"Solución
Abrir la solución con pruebas en un entorno controlado."

2020-10-09 05:26 UTC, danilobrinu commented
> @vplentinax @danilobrinu
> pienen como programadores!!
> 
> "server" precisa estructura rigida,
> cuando encuentra article lo agrega, numera y titula sin que nadie tenga que ponerlo en una lista,
> cuando ve task + solution los pone al final del article sin que nadie necesite ponerlo explicitamente
> probablemente solution vacio habilita el boton, quizas con solamente el link al sandbox
> 
> nota:
> El boton y link a sandbox de "solution" está bien traducido, pero
> ¿no les parece qie suena un poco raro? copio:
> "Solución
> Abrir la solución con pruebas en un entorno controlado."

La verdad no te entendi nada jaja y no creo que tenga que ver con pensar como programador o no.

2020-10-09 06:32 UTC, joaquinelio commented
era solo una curiosidad, de por qué agregar solution vacio

2020-10-09 16:30 UTC, vplentinax commented on 2-ui/1-document/08-styles-and-classes/article.md
>  Before we get into JavaScript's ways of dealing with styles and classes -- here's an important rule. Hopefully it's obvious enough, but we still have to mention it.
¿Por qué no se tradujo este párrafo?

2020-10-09 16:52 UTC, danilobrinu commented on 2-ui/1-document/08-styles-and-classes/article.md
>  Before we get into JavaScript's ways of dealing with styles and classes -- here's an important rule. Hopefully it's obvious enough, but we still have to mention it.
@vplentinax creo que no te has dado cuenta que este PR esta en DRAFT.

2020-10-09 16:55 UTC, vplentinax commented on 2-ui/1-document/08-styles-and-classes/article.md
>  Before we get into JavaScript's ways of dealing with styles and classes -- here's an important rule. Hopefully it's obvious enough, but we still have to mention it.
Pues no. Ok, sigue ahí....

2020-10-17 21:54 UTC, joaquinelio requested changes

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Antes de profundizar en como JavaScript maneja las clases y los estilos, hay una regla importante. Aunque es lo suficientemente obvio, aún tenemos que mencionarlo.
```suggestion
Antes de profundizar en cómo JavaScript maneja las clases y los estilos, hay una regla importante. Aunque es lo suficientemente obvio, aún tenemos que mencionarlo.
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Nosotros deberíamos preferir las clases `css` en lugar de `style`. Este último solo debe usar si las clases "no pueden manejarlo".
```suggestion
Nosotros deberíamos preferir las clases `css` en lugar de `style`. Este último solo debe usarse si las clases "no pueden manejarlo".
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Para otros casos como convertir un texto en rojo, agregar un icono de fondo. Escribir eso en CSS y luego agregar la clase (JavaScript puede hacer eso), es más flexible y más fácil de soportar.
Está bien la traduccion liteeral, pero creo que se refiere al soporte mantenimiento.
```suggestion
Para otros casos como convertir un texto en rojo, agregar un icono de fondo. Escribir eso en CSS y luego agregar la clase (JavaScript puede hacer eso), es más flexible y más fácil de mantener.
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +En la antigüedad, había una limitación en JavaScript: una palabra reservado como `"class"` no podía ser una propiedad de un objeto. Esa limitación no existe ahora, pero en ese momento era imposible t
```suggestion
En la antigüedad, había una limitación en JavaScript: una palabra reservada como `"class"` no podía ser una propiedad de un objeto. Esa limitación no existe ahora, pero en ese momento era imposible tener una propiedad `"class"`, como `elem.class`.
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Propiedades con prefijos del navegador como `-moz-border-radius`, `-webkit-border-radius` también las que siguen la misma regla: un guion significa mayúscula.
```suggestion
Propiedades con prefijos del navegador como `-moz-border-radius`, `-webkit-border-radius` también siguen la misma regla: un guion significa mayúscula.
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +// si podemos ejecutar este código, el <body> papadeará
```suggestion
// si ejecutamos este código, el <body> papadeará
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Hace mucho tiempo `getComputedStyle` fue creado para obtener los valores calculados, pero los valores resueltos son muchos más convenientes, y el estándar cambio.
```suggestion
Hace mucho tiempo `getComputedStyle` fue creado para obtener los valores calculados, pero los valores resueltos son muchos más convenientes, y el estándar cambió.
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Por ejemplo, si hay propiedades `paddingLeft/paddingTop`, entonces que deberíamos obtener de `getComputedStyle(elem).padding`? nada, o tal vez un valor "generado" de los paddings? No hay una regla es
```suggestion
Por ejemplo, si hay propiedades `paddingLeft/paddingTop`, ¿entonces qué deberíamos obtener de `getComputedStyle(elem).padding`? ¿Nada, o tal vez un valor "generado" de los paddings? No hay una regla estándar aquí.
```

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +```smart header="Estilos aplicados a los enlacess `:visited` están ocultos!"
```suggestion
```smart header="¡Los estilos aplicados a los enlaces `:visited` están ocultos!"
```

Cosa extraña, a pesar de tener triple backtick se ve bien la suggest
OJO al resultado quizas el MD no funciones y debas editar a mano.

2020-10-17 21:54 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Leer y escribir tiene el mismo significado que modificar propiedades individuales en el atributo `"style"`. Para ver como aplicar `important` y otras cosas raras, hay una lista de métodos en [MDN](md
```suggestion
Leer y escribir tiene el mismo significado que modificar propiedades individuales en el atributo `"style"`. Para ver cómo aplicar `important` y otras cosas raras, hay una lista de métodos en [MDN](mdn:api/CSSStyleDeclaration).
```

2020-10-17 22:20 UTC, danilobrinu commented
/done

2020-10-18 03:26 UTC, joaquinelio requested changes
Se me escapó una.
Dos. 
Creo que es todo.

2020-10-18 03:26 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Los enlaces visitados deberían estar coloreados la pseudo-clase `:visited` de CSS.
```suggestion
Los enlaces visitados pueden ser coloreados usando la pseudo-clase `:visited` de CSS.
```

2020-10-18 03:26 UTC, joaquinelio commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Para leer los estilos resueltos (con respecto a todas las clases, después de que se aplica todo el `css` se calculan los valores finales):
```suggestion
Para leer los estilos resueltos (con respecto a todas las clases, después de que se aplica todo el `css` y se calculan los valores finales):
```

2020-10-18 13:31 UTC, danilobrinu commented
/done

2020-10-19 02:48 UTC, joaquinelio approved these changes

2020-10-19 16:25 UTC, vplentinax approved these changes
OK

2020-10-20 01:13 UTC, merged

2020-10-20 01:30 UTC, joaquinelio commented
@vplentinax @danilobrinu 

Me canse de hacer pr y me permiti hacer un commit directo, pero aviso. 

task estaba traducida, faltaba una linea
"the options are" a "Las opciones son"
La solucion esta vacia porque solo funciona en nueva pagina o plnkr
y funciona nicely