Methods of RegExp and String
javascript-tutorial/es.javascript.info pull request #414
Opened 2020-10-09 01:48 UTC by danilobrinu

2020-10-09 01:48 UTC, danilobrinu commented
@joaquinelio yo creo que ahora ya esta bien

2020-10-09 03:46 UTC, joaquinelio requested changes
- Si rescribis en lugar de usar las suggest, cuida los acentos que les agregué/quité
- una de las correccione esta sin suggest porque el md con graves me lo impide
- para mi es valido "retornar" como el "devolver" que sugerimos en todos lados, no se que piensan otros.  Sugerimos consistencia pero no creo que esto confunda a nadie.
-no creo que debas usarr lista en lugar de array, para quien solo sepa js lista no tiene entidad. No lo puse en suggest porque en el momento dudaba...

2020-10-09 03:46 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
>    alert( `Found ${result[0]} at position ${result.index}` );
Preferiria que el comentario // coincidiera con el codigo
es texto, se puede cambiar, 
pero es backticks, hay que tener cuidado... haceme review del suggest jaja
```suggestion
  alert( `Se encontró ${result[0]} en la posición ${result.index}` );
```

2020-10-09 03:46 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Si la expresión regular tiene la bandera `pattern:y`, entonces la busqueda se realizará exactamente en la posición del `regexp.lastIndex`, no más adelante.
```suggestion
Si la expresión regular tiene la bandera `pattern:y`, entonces la búsqueda se realizará exactamente en la posición del `regexp.lastIndex`, no más adelante.
```

2020-10-09 03:46 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Vamos a reemplazar la bandera `pattern:g` con `pattern:y` en el ejemplo anterior. No habrá coincidencias, ya que no hay palabra en la posiicón `5`:
```suggestion
Vamos a reemplazar la bandera `pattern:g` con `pattern:y` en el ejemplo anterior. No habrá coincidencias, ya que no hay palabra en la posición `5`:
```

2020-10-09 03:46 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Es conveniente para situaciones cuando necesitamos "leer" algo de la cadena por una expresión regular en una posición exacta. That's convenient for situations when we need to "read" something from th
hard to read...
ademas del mix ingles

Es conveniente para situaciones cuando, con una expresión regular, necesitamos "leer" algo de la cadena en una posición exacta, no en otro lugar.

Es conveniente para situaciones cuando necesitamos "leer" algo de la cadena en una posición exacta, no en otro lugar, , con una expresión regular.

en ingles esta feo. fuera.


Esto es conveniente cuando necesitamos "leer" algo de la cadena en una posición exacta, no en otro lugar, con una expresión regular.

```suggestion
Esto es conveniente cuando con una expresión regular necesitamos "leer" algo de la cadena en una posición exacta, no en otro lugar.
```
o con comas
Esto es conveniente cuando, con una expresión regular, necesitamos "leer" algo de la cadena en una posición exacta, no en otro lugar.

y si me apuras quito "no en otro lugar" coma incluida.  Exacta es exacta. y como cierra la oración, queda clarísima.

Esto es conveniente cuando con una expresión regular necesitamos "leer" algo de la cadena en una posición exacta.

uf 
mejor me voy a dormir

2020-10-09 03:46 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +````warn header="La misma expresión regular probada (de manera global) repetidamente en diferentes lugares puede fallar"
Si pusiste los parentesis para suavizar la lectura, estoy en desacuerdo, el "global" es vital aca
no puedo hacer suggest por el MD con graves
tampoco es del todo correcto porque entre comas (aunque gramaticamente correcto)  pero necesito suavizar el largo y no se como.

Una misma expresión regular global, probada repetidamente en diferentes lugares, puede fallar.

2020-10-09 03:46 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Si nosotros aplicamos la misma expresión regular (de manera global) a diferentes entradas, puede causar resultados incorrectos, porque `regexp.test` anticipa las llamadas usando la propiedad `regexp.
```suggestion
Aplicar la misma expresión regular global a diferentes entradas puede causar resultados incorrectos, porque `regexp.test` anticipa las llamadas usando la propiedad `regexp.lastIndex`, por lo que la búsqueda en otra cadena puede comenzar desde una posición distinta a cero.
```
varias cosas en la misma oracion...
-el pronombre redundante
-"aplicamos / puede " suena mal, no se explicar por que y puedo equivocarme, ademas si pongo impersonal queda mas corto...  En ingles estan obligados a poner persona "si yo/alguno/nos hace/ tal cosa.." no pueden "Hacer tal cosa..."
-si te asusta la falta de comas, digo que es correcto asi. Un buen lector sabe leer las pausas de la estructura. Aunque a veces dejo que las agreguen (aun en lugares incorrectos) porque esto lo leen programadores no literatos (y eso incluye a Ilya) jajaja  ,
podes agregarlas.

2020-10-09 03:46 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert( regexp.test("javascript") ); // true (regexp.lastIndex=10 ahora)
```suggestion
alert( regexp.test("javascript") ); // true (ahora es regexp.lastIndex=10 )
```

2020-10-09 05:43 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert(matchAll); // [object RegExp String Iterator], no es una lista, pero si un objeto iterable
Que opinas de esto https://developer.mozilla.org/es/docs/Learn/JavaScript/First_steps/Arrays ?

2020-10-09 05:55 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +Si hay paréntesis en la expresión regular, entonces solo son 3 argumentos: `func(str, offset, input)`.
El entonces se refiere a que sucede cuando ocurre una condicion

2020-10-09 06:40 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert(matchAll); // [object RegExp String Iterator], no es una lista, pero si un objeto iterable
No me gustan las traducciones de MDN, las uso lo minimo posible como referencia... 
pero eso es discutible, otros se apoyan mucho más en MDN.

Considera a quien viene por primera vez, en ningun lugar del sitio explicamos el concepto de lista en programacion,
para quien lee, lista es una lista natural. 
El original dice array, que me parece adecuado. Yo voto por array.  Si hay otras opiniones...

2020-10-09 13:36 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert(matchAll); // [object RegExp String Iterator], no es una lista, pero si un objeto iterable
En todo caso debería ser arreglo, pero si ya en todas partes esta como array lo mejor es mantenerlo así

2020-10-09 13:41 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +    Si queremos que el resultado sea una lista, podemos escribirlo así:
```suggestion
    Si queremos que el resultado sea un array, podemos escribirlo así:
```

2020-10-09 13:41 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +1. Retorna un objeto iterable con las coincidencias en lugar de una lista. Podemos convertirlo en una lista usando el método `Array.from`.
```suggestion
1. Retorna un objeto iterable con las coincidencias en lugar de un array. Podemos convertirlo en un array usando el método `Array.from`.
```

2020-10-09 14:30 UTC, danilobrinu commented
/done

2020-10-09 14:35 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +2. Si la expresión regular (`regexp`) tiene la bandera `pattern:g`, retorna una lista de todas las coincidencias como cadenas, sin capturar grupos y otros detalles.
```suggestion
2. Si la expresión regular (`regexp`) tiene la bandera `pattern:g`, retorna un array de todas las coincidencias como cadenas, sin capturar grupos y otros detalles.
```

2020-10-09 14:35 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +2. Cada coincidencia es retornada como una lista con los grupos capturados (el mismo formato de `str.match` sin la bandera `pattern:g`).
```suggestion
2. Cada coincidencia es retornada como un array con los grupos capturados (el mismo formato de `str.match` sin la bandera `pattern:g`).
```

2020-10-09 14:35 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert(matchAll); // [object RegExp String Iterator], no es una lista, pero si un objeto iterable
```suggestion
alert(matchAll); // [object RegExp String Iterator], no es un array, pero si un objeto iterable
```

2020-10-09 14:35 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +matchAll = Array.from(matchAll); // ahora es una lista
```suggestion
matchAll = Array.from(matchAll); // ahora es un array
```

2020-10-09 14:35 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert('12-34-56'.split('-')) // lista de [12, 34, 56]
```suggestion
alert('12-34-56'.split('-')) // array de [12, 34, 56]
```

2020-10-09 14:35 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +1. Si la expresión regular (`regexp`) no tiene la bandera `pattern:g`, retorna una lista con los grupos capturados y las propiedades `index` (posición de la coincidencia), `input` (cadena de entrada,
```suggestion
1. Si la expresión regular (`regexp`) no tiene la bandera `pattern:g`, retorna un array con los grupos capturados y las propiedades `index` (posición de la coincidencia), `input` (cadena de entrada, igual a `str`):
```

2020-10-09 14:49 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert( regexp.test("javascript") ); // true (ahora es regexp.lastIndex=10 )
```suggestion
alert( regexp.test("javascript") ); // true (ahora regexp.lastIndex es 10)
```

2020-10-09 16:28 UTC, vplentinax requested changes
Pequeños detalles.
@danilobrinu  no olvides poner /done al finalizar las correcciones.

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +3. Si no hay coincidencias, no importa si tiene la bandera `pattern:g` o no, `null` es retornado.
Esta sugerencia me parece más natural al leerlo. 

```suggestion
3. Si no hay coincidencias, no importa si tiene la bandera `pattern:g` o no,  retorna `null` .
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +    Esto es algo mmuy importante. Si no hay coincidencias, no vamos a obtener un array vacío, pero si un `null`. Es fácil cometer un error olvidandolo, ej.:
```suggestion
    Esto es algo muy importante. Si no hay coincidencias, no vamos a obtener un array vacío, pero si un `null`. Es fácil cometer un error olvidándolo, ej.:
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +3. Si no hay resultados, no retorna `null`, pero si un objecto iterable vacío.
```suggestion
3. Si no hay resultados, no retorna `null`, pero sí un objeto iterable vacío.
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert(matchAll); // [object RegExp String Iterator], no es un array, pero si un objeto iterable
```suggestion
alert(matchAll); // [object RegExp String Iterator], no es un array, pero sí un objeto iterable
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +Podemos usarlo sin expresiones regular, para buscar y reemplazar una sub-cadena:
```suggestion
Podemos usarlo sin expresiones regulares, para buscar y reemplazar una sub-cadena:
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +|`$n`|si `n` es un 1-2 dígito númerico, inserta el contenido del enésimo grupo capturado, para más detalles ver [](info:regexp-groups)|
```suggestion
|`$n`|si `n` es un número de 1 o 2 dígitos númericos, inserta el contenido del enésimo grupo capturado, para más detalles ver [](info:regexp-groups)|
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +Si no está bandera `pattern:g`, entonces `regexp.exec(str)` retorna la primera coincidencia igual que `str.match(regexp)`. Este comportamiento no trae nada nuevo.
```suggestion
Si no está la bandera `pattern:g`, entonces `regexp.exec(str)` retorna la primera coincidencia igual que `str.match(regexp)`. Este comportamiento no trae nada nuevo.
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +// comienza la busqueda desde la posición 10:
```suggestion
// comienza la búsqueda desde la posición 10:
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +Si nosotros aplicamos la misma expresión regular (de manera global) a diferentes entradas, puede causar resultados incorrectos, porque `regexp.test` anticipa las llamadas usando la propiedad `regexp.
```suggestion
Si nosotros aplicamos la misma expresión regular (de manera global) a diferentes entradas, puede causar resultados incorrectos, porque `regexp.test` anticipa las llamadas usando la propiedad `regexp.lastIndex`, por lo que la búsqueda en otra cadena puede comenzar desde una posición distinta a cero.
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +Para solucionarlo, podemos establecer `regexp.lastIndex = 0` antes de cada busqueda. O en lugar de llamar a los metodos en la expresión regular usar los metodos de cadena `str.match/search/...`, ello
```suggestion
Para solucionarlo, podemos establecer `regexp.lastIndex = 0` antes de cada búsqueda. O en lugar de llamar a los metodos en la expresión regular usar los metodos de cadena `str.match/search/...`, ellos no usan el `lastIndex`.
```

2020-10-09 16:28 UTC, vplentinax commented on 9-regular-expressions/17-regexp-methods/article.md
> +Entonces, repetidas llamadas retornan todas las coincidencias una tras otra, usando la propiedad `regexp.lastIndex` para realizar el rastreo de la posición actual de la busqueda.
```suggestion
Entonces, repetidas llamadas retornan todas las coincidencias una tras otra, usando la propiedad `regexp.lastIndex` para realizar el rastreo de la posición actual de la búsqueda.
```

2020-10-09 16:55 UTC, danilobrinu commented
/done

2020-10-09 16:57 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +|`$n`|si `n` es un 1-2 dígito númerico, inserta el contenido del enésimo grupo capturado, para más detalles ver [](info:regexp-groups)|
```suggestion
|`$n`|si `n` es un número, inserta el contenido del enésimo grupo capturado, para más detalles ver [](info:regexp-groups)|
```

2020-10-09 18:07 UTC, vplentinax commented
No hay necesidad de volvernos a solicitar revisión. Al escribir /done, ya nos llega el aviso y la etiqueta cambia automáticamente.

2020-10-09 18:42 UTC, joaquinelio requested changes
1) sorry se me escaparon cosas, 
estoy miope, ahora hice superzoom para encontrarlas,  acentos y typos

2) No insisto con quitar el "entonces" porque hay algo de gusto personal, pero no es lo mismo cuando falta el "si", Con el "si" el entoncess es casi redundante (y habria que quitar la coma pero no me importa). 
"A tiene B, entonces pasa C"  (el "entonces" obligado)
"Si A tiene B, pasa C"
"Si A tiene B entonces pasa C"

3) Algo me molestaba... pero no tengo ganas de sugerirlo ahora porque me vas a ignorar. 
cambiaría el " No es A, pero sí B" por  un simple "No es A sino B" o "No es A, si no B".
SALVO un lugar donde vale remarcarlo: "No devuelve un array, pero sí un iterable"  

4) Un codigo lo pase a ingles si no habria que cambiar el comentario, la 2da vez la dejaste en ingles asi que quedaria coherente.

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +El método `regexp.exec(str)` retorna una coincidencia por expresión regular (`regexp`) en la cadena (`str`). A diferencia de los metodos anteriores, se llama en una expresión regular en lugar de en u
mas acentos...
```suggestion
El método `regexp.exec(str)` retorna una coincidencia por expresión regular (`regexp`) en la cadena (`str`). A diferencia de los métodos anteriores, se llama en una expresión regular en lugar de en una cadena.
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +- Una llamda a `regexp.exec(str)` retorna la primera coincidencia y guarda la posición inmediatamante después en `regexp.lastIndex`.
```suggestion
- Una llamda a `regexp.exec(str)` retorna la primera coincidencia y guarda la posición inmediatamente después en `regexp.lastIndex`.
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Esto también, aunque para navegadores modernos `str.matchAll` es lo más conveniente.
¿esto estaba asi? Esto tambien qué.
se me escapo...

y no sé por que quitaste "usualmente", 
no sé lo suficiente como para saber si hay condiciones en que no  sea lo mas conveniente que es lo que parece sugerir el original...

lastima la cacofonia

```suggestion
Esto también funciona, aunque para navegadores modernos `str.matchAll` usualmente es lo más conveniente.
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +let str = 'Hola, mundo!';
Tambien se me escapo esto!!!
La coma ya no esta en el 5to lugar (contando de cero), aunque el resultado fuera  el mismo deberiamos ser mas precisos.

Se arregla dejando ingles 
o cambiando los comentarios
 
adema si es castellano falta la apertura  " ¡   ! " 
```suggestion
let str = 'Hello, world!';
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert( regexp.exec(str) ); // mundo
uf
debi cambiar el numero  

si decidis eso no olvides el " ¡ "

```suggestion
alert( regexp.exec(str) ); // world
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Por ejemplo, podemos llamarlo aquí `regexp.test` dos veces en el mismo texto y en la segunda vez falla:
"llamarlo a algo" no va...

y prefiero la contruccion original...

```suggestion
Por ejemplo, aquí llamamos `regexp.test` dos veces en el mismo texto y en la segunda vez falla:
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Eso es exactamente porque `regexp.lastIndex` no es cero en la segunda prueba.
El original ingles
 es una porquería

sugiero ignorarlo "exactamente" queda forzado y no añade nada

```suggestion
Eso es porque `regexp.lastIndex` no es cero en la segunda prueba.
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +Para solucionarlo, podemos establecer `regexp.lastIndex = 0` antes de cada búsqueda. O en lugar de llamar a los metodos en la expresión regular usar los metodos de cadena `str.match/search/...`, ello
mas acentos
```suggestion
Para solucionarlo, podemos establecer `regexp.lastIndex = 0` antes de cada búsqueda. O en lugar de llamar a los métodos en la expresión regular usar los métodos de cadena `str.match/search/...`, ellos no usan el `lastIndex`.
```

2020-10-09 18:42 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +    Esto es algo muy importante. Si no hay coincidencias, no vamos a obtener un array vacío, pero si un `null`. Es fácil cometer un error olvidándolo, ej.:
otro acento...

```suggestion
    Esto es algo muy importante. Si no hay coincidencias, no vamos a obtener un array vacío, pero sí un `null`. Es fácil cometer un error olvidándolo, ej.:
```

2020-10-09 18:56 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +Esto también, aunque para navegadores modernos `str.matchAll` es lo más conveniente.
No lo quite fue una de las sugerencias que se aplicaron antes

2020-10-09 19:18 UTC, danilobrinu commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert( regexp.exec(str) ); // mundo
```suggestion
alert( regexp.exec(str) ); // world!
```

2020-10-09 19:18 UTC, danilobrinu commented
/done

2020-10-09 19:28 UTC, joaquinelio requested changes
AAAHHHH!!! 
¿¿¿Lo pase al ingles con el signo "!" ?????  sorrysorrysorrysorrysorry

linea 274
supongo que  w+ es solamente "world"

ya está, me quemé.
perdon si los arrastre a uds tambien...

2020-10-09 19:28 UTC, joaquinelio commented on 9-regular-expressions/17-regexp-methods/article.md
> +alert( regexp.exec(str) ); // world!
```suggestion
alert( regexp.exec(str) ); // world
```

2020-10-09 20:30 UTC, danilobrinu commented
/done

2020-10-09 21:28 UTC, joaquinelio approved these changes

2020-10-12 16:27 UTC, vplentinax approved these changes
Ok

2020-10-12 20:48 UTC, merged