Susy201010
javascript-tutorial/es.javascript.info pull request #415
Opened 2020-10-10 01:37 UTC by joaquinelio

debio ser 20 10 09...

2020-10-10 01:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=415) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=415) before we can accept your contribution.<br/>**3** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: vsemozhetbyt<br/>:white_check_mark: joaquinelio<br/>:white_check_mark: iliakan<br/>:x: Ledorub<br/>:x: haond10adp<br/>:x: Anurag-Chauhan-289<br/>:x: ZYinMD<br/>:x: Mr0cket<br/>:x: CrypterSr<br/>:x: paroche<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=415) it.</sub>

2020-10-12 16:21 UTC, vplentinax requested changes
Primera revisión rápida. Luego vuelvo.

2020-10-12 16:21 UTC, vplentinax commented on 1-js/04-object-basics/02-object-copy/article.md
> +Esto es fácil de entender si miramos un poco "bajo cunierta" de lo que pasa cuando copiamos por valor.
```suggestion
Esto es fácil de entender si miramos un poco "bajo cubierta" de lo que pasa cuando copiamos por valor.
```

2020-10-12 16:21 UTC, vplentinax commented on 1-js/04-object-basics/02-object-copy/article.md
> +And here's how it's actually stored in memory:
```suggestion
Y así es como se almacena en la memoria:
```

2020-10-12 16:21 UTC, vplentinax commented on 1-js/04-object-basics/02-object-copy/article.md
> +Cuando ejecutamos acciones con el objeto, por ejemplo tomar una propiedad `user.name`, el motor JavaScript busca aquella dirección y ejecuta la operacion en el objeto mismo.
```suggestion
Cuando ejecutamos acciones con el objeto, por ejemplo tomar una propiedad `user.name`, el motor JavaScript busca aquella dirección y ejecuta la operación en el objeto mismo.
```

2020-10-12 16:21 UTC, vplentinax commented on 1-js/04-object-basics/02-object-copy/article.md
> +Es como si tuviéramos un gabinete con dos llaves y usáramos una de ellas (`admin`) para accederlo. Si más tarde usamos la llave (`user`), podemos ver los cambios.
```suggestion
Es como si tuviéramos un gabinete con dos llaves y usáramos una de ellas (`admin`) para acceder a él. Si más tarde usamos la llave (`user`), podemos ver los cambios.
```

2020-10-12 20:45 UTC, joaquinelio commented
/done

2020-10-19 16:36 UTC, vplentinax approved these changes
Todo bien,  pequeñas cosas. Puede hacer merge después

2020-10-19 16:36 UTC, vplentinax commented on 1-js/01-getting-started/1-intro/article.md
>    Los navegadores mas modernos le permiten trabajar con archivos, pero el acceso es limitado y solo permitido si el usuario realiza ciertas acciones, como "arrastrar" un archivo a la ventana del nave
```suggestion
  Los navegadores más modernos le permiten trabajar con archivos, pero el acceso es limitado y solo permitido si el usuario realiza ciertas acciones, como "arrastrar" un archivo a la ventana del navegador o seleccionarlo por medio de una etiqueta `<input`>.
```

2020-10-19 16:36 UTC, vplentinax commented on 1-js/01-getting-started/1-intro/article.md
> +    Existen maneras de interactuar con la cámara, micrófono y otros dispositivos, pero eso requiere el permiso explicito del usuario. Por lo tanto, una página habilitada para JavaScript no puede habi
```suggestion
    Existen maneras de interactuar con la cámara, micrófono y otros dispositivos, pero eso requiere el permiso explícito del usuario. Por lo tanto, una página habilitada para JavaScript no puede habilitar una cámara web para observar el entorno y enviar la información a la [NSA](https://es.wikipedia.org/wiki/Agencia_de_Seguridad_Nacional).
```

2020-10-19 17:08 UTC, joaquinelio commented
/done

2020-10-19 17:09 UTC, joaquinelio commented
/done pero te tomo la palabra, no lo dejaré abandonado

2020-10-20 01:32 UTC, merged