1.4.7 opt chaining update from ENG
javascript-tutorial/es.javascript.info pull request #419
Opened 2020-10-11 07:52 UTC by joaquinelio

https://es.javascript.info/optional-chaining

habia un err no visible de formato en ejemplo antes del resumen

2020-10-14 23:21 UTC, vplentinax requested changes
Pequeñas cositas

2020-10-14 23:21 UTC, vplentinax commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Este es el resultado esperado, JavaScript funciona así, pero en muchos casos prácticoss preferiríamos obtener `undefined` en lugar del error (sin "street").
```suggestion
Este es el resultado esperado, JavaScript funciona así, pero en muchos casos prácticos preferiríamos obtener `undefined` en lugar del error (sin "street").
```

2020-10-14 23:21 UTC, vplentinax commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +**De aquí en más en este artículo, por brevedad, diremos que algo "existe" si no es `null` o `undefined`.**
```suggestion
**De aquí en adelante en este artículo, por brevedad, diremos que algo "existe" si no es `null` o `undefined`.**
```

2020-10-15 02:38 UTC, joaquinelio commented
/done

2020-10-15 02:45 UTC, joaquinelio commented
Es mayor responsabilidad del traductor hacer cambios español a español, en review no comparas con el inglés original.

No veo como mejorarlo.
La manera perfecta de review sería bajando el branch y compararlo con lens, pero es una locura no puedo pedir eso.

Más convencido cada vez, la sync delega, 
que el artículo se haga sin apuro.

2020-10-19 16:40 UTC, vplentinax approved these changes
ok

2020-10-21 22:02 UTC, merged