Node properties: type, tag and contents
javascript-tutorial/es.javascript.info pull request #422
Opened 2020-10-12 00:22 UTC by homero304

please review my PR

2020-10-12 05:37 UTC, joaquinelio requested changes
correcciones y divagues...

y sorry si algun coment parece agresivo no lo es, solo estoy jugando.
es que nunca antes en mi vida usé bugs, era perfecto
y en las ultimas sync puse dos y todavia no me recupero del shock.

Ah, creo que hay correctores automaticos metiendo el rabo
bad Homer..!

2020-10-12 05:37 UTC, joaquinelio commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +En el ejemplo de `chatDiv` arriba, la línea `chatDiv.innerHTML+="¿Cómo va?"` recrea el contenido HTML y recarga `smile.gif` (espero que esté en caché). Si `chatDiv` tiene muchos otros textos e imágen
creo que asi, no tan literal, 
refleja mejor la idea del original  (o "esperando que esté en cache")
```suggestion
En el ejemplo de `chatDiv` arriba, la línea `chatDiv.innerHTML+="¿Cómo va?"` recrea el contenido HTML y recarga `smile.gif` (con la esperanza de que esté en caché). Si `chatDiv` tiene muchos otros textos e imágenes, entonces la recarga se vuelve claramente visible.
```

2020-10-12 05:37 UTC, joaquinelio commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Es muy fácil cometer un error aquí: modifica `div.outerHTML` y luego continúa trabajando con `div` como si tuviera el nuevo contenido. Pero no es así. Esto es correcto para `innerHTML`, pero no para
```suggestion
Es muy fácil cometer un error aquí: modificar `div.outerHTML` y luego continuar trabajando con `div` como si tuviera el nuevo contenido. Pero no es así. Esto es correcto para `innerHTML`, pero no para `outerHTML`.
```

2020-10-12 05:37 UTC, joaquinelio commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +  let name = prompt("¿Cuál es tu nombre?", "<b>Winnie-el-pooh!</b>");
buuuhhh
¡el nombre de Winnie-the-pooh no se traduce, hereje!
¿o si?

Ademas el original esta mal porque Pooh es parte del nombre,
deberias mandar PR al repo ingles, fatal bug
se llama 
Winnie-the-Pooh
o 
Winnie Pooh


jaja no me hagas caso estoy quemado

2020-10-12 05:37 UTC, joaquinelio commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Podemos usarlo en HTML o asignar usando JavaScript, así:
en ingles falta "it"

```suggestion
Podemos usarlo en HTML o asignarlo usando JavaScript, así:
```

2020-10-12 05:37 UTC, joaquinelio commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Técnicamente, `hidden` funciona igual que `style="display: none"`. Pero es más corto de escribir.
creo, no recuerdo, que se recomienda sin espacios, 
por las dudas dejo como el original
```suggestion
Técnicamente, `hidden` funciona igual que `style="display:none"`. Pero es más corto de escribir.
```

frontend people, ¿ es cierto esto?  
crei que display none quita el elemento entero de la pagina
y que hidden solo lo hacia invisible

2020-10-12 11:42 UTC, homero304 commented
/done

2020-10-12 12:41 UTC, homero304 commented
/done

2020-10-12 19:49 UTC, joaquinelio commented
ah, 
lo de "built in" era solo un comentario  

"incorporada" es lo que usamos hasta ahora, seria "correcto" aunque en mi opinion muy facil de malinterpretar, las bibliotecas de 3ros tambien "incorporan" funciones
"integrada" me gustaba un poco más, no se por qué, me da idea de que ya esta ahi, no incorporado posteriormente en una biblioteca extra... "built-in" ="integrada" me gusta. No recuerdo ssi ses uso asi en algun lado.
"nativa" me parecia perfecta pero no lo habiamos ussado antes, y no lo discutimos antes, para mi esta bien, no lo habia sugerido porque podria haber desacuerdos, 
Acepto cualquier version, pero no se los demás.

2020-10-12 19:57 UTC, joaquinelio approved these changes

2020-10-14 23:14 UTC, vplentinax approved these changes
Good!

2020-10-15 01:31 UTC, merged

2020-10-15 01:59 UTC, joaquinelio commented
@vplentinax  
🎉🎉🎉🎉🎉
Si sos el 2do ok, podes hacer merge sin esperarme,
salvo que no tengas tiempo de revisar online, ya cometi el error de no revisar bien,  dejamelo es una satisfacción.
*El mensaje de idioma sigue saliendo, no problem, al tiempo deja de salir.
*Tambien tarda un poco más mostrar el índice español que la página. El índice ES el titulo de la pagina, asi que solo es esperar nosequé.
*Siempre revisar FORMATO no se ven los err de formato dentro de git
*Imagenes
*Las soluciones, que abran, ves enseguida si falta traduccion, y TAMBIEN he visto fallas de formato dentro
*Los links, suelo buscarlos y abrirloss con el boton del medio asi reviso todos juntos, internos y externos
-Los sandbox... culpable,  demora mucho en abrir plunker y a veces son muchos... 

Y ESTE PR se vio perfecto
¡¡¡¡ Faltan 25 !!!!   
🎉🎉🎉🎉🎉