Update article.md
javascript-tutorial/es.javascript.info pull request #424
Opened 2020-10-15 20:43 UTC by AbiF73

Hola! Tuve algunas dudas con algunas palabras, lo siento. Espero sus correcciones.

2020-10-15 20:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=424) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=424) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=424) it.</sub>

2020-10-15 22:42 UTC, joaquinelio requested changes
bienvenido 
y bienvenido si continuas

Sabes de git ?  veo que modificaste tu master
No nos afecta en el pr, pero lo mejor para trabajar en tu fork es
dejar el master intocable (solo actualizar desde nuestro fork)
generar en un branch y modificar alli
una vez hecho el pr y añadido al nuestro repo, puedes borrar el branch
y actualizar tu master desde nuestro remoto

2020-10-15 22:42 UTC, joaquinelio commented on 9-regular-expressions/16-regexp-sticky/article.md
> +Tal uso de `regexp.exec` es una alternativa para el método `str.match bAll`.
```suggestion
Tal uso de `regexp.exec` es una alternativa al método `str.match bAll`.
```

2020-10-15 22:42 UTC, joaquinelio commented on 9-regular-expressions/16-regexp-sticky/article.md
> +Por favor nota que la búsqueda comienza en la posición `lastIndex` y luego profundiza. Sí no hay ninguna palabra en la posición `lastIndex`, pero está en algún lugar posterior, entonces será encontra
no creo que profundizar sea la palabra
sin acento "sí"
Y si me permitis quito el por favor que me empalaga,
algo con las comas largo de explicar...
tampoco sé explicar el cambio "la hay"...  (tambien "pero sí en algun lugar posterior")
rechaza o rescribilo todo si queres, soy un maniatico jajaj
```suggestion
Nota que la búsqueda comienza en la posición `lastIndex` y luego sigue adelante. Si no hay ninguna palabra en la posición `lastIndex` pero la hay en algún lugar posterior, entonces será encontrada:
```

2020-10-15 22:42 UTC, joaquinelio commented on 9-regular-expressions/16-regexp-sticky/article.md
> +En tales tareas como el análisis léxico, normalmente hay muchas búsquedas en una posición exacta. Usar el indicador `pattern:y` es la clave para un buen desempeño.
```suggestion
En tareas tales como el análisis léxico, normalmente hay muchas búsquedas en una posición exacta. Usar el indicador `pattern:y` es la clave para un buen desempeño.
```

2020-10-15 22:45 UTC, joaquinelio commented
ah, para llevar el control (y Don Bot lo entienda) 
cambié el nombre al PR

Sticky flag "y", searching at position

2020-10-15 22:56 UTC, joaquinelio commented
AAAHHHHHHH!!!!

Ilya marcó la version en ingles como WIP
el crazy va a rescribirlo todo!!!!

2020-10-25 16:08 UTC, vplentinax commented
Después que se acepten las sugerencias de Joaquinelio, paso yo a revisar.

2020-10-25 17:36 UTC, joaquinelio commented
> Después que se acepten las sugerencias de Joaquinelio, paso yo a revisar.

@vplentinax 
El pr es de hace 10 dias, las suggest son de hace 10 dias...

Encima Ilya lo rescribió dos dias después. 
Aun no se si hacer sync (ingles-ingles, seria directo) y que este quede con conflictos multiples
o esperar al merge de esto e  descartar la nueva version para verla tranquilo

2020-10-26 23:40 UTC, vplentinax commented
@joaquinelio Hazlo como te parezca más cómodo a ti. No tengo inconveniente con ninguna de las dos formas.

2020-11-20 23:24 UTC, joaquinelio commented
@vplentinax 
Este es un art breve
El ingles fue reescrito o rescrito, (en repo esp deje version vieja para que esto no diera conflictos)
podriamos descartar esto y hacerlo de cero

por otro lado, 
corrigiendo ortografia le daria MERGE,
es un art muy facil de entender 
e Ilya hizo mucho cambio no dire superfluo pero...

2020-12-17 17:18 UTC, vplentinax approved these changes
Ok

2020-12-17 17:49 UTC, merged