Fetch: Download progress
javascript-tutorial/es.javascript.info pull request #425
Opened 2020-10-17 17:08 UTC by homero304

please review my PR

2020-10-17 21:27 UTC, joaquinelio requested changes

2020-10-17 21:27 UTC, joaquinelio commented on 5-network/03-fetch-progress/article.md
> +4. Al final, tenemos `chunks` - una matriz de fragmentos de bytes `Uint8Array`. Necesitamos unirlos en un solo resultado. Desafortunadamente, no hay un método único que los concatene, por lo que hay
simple por facil no por unico supongo
```suggestion
4. Al final, tenemos `chunks` - una matriz de fragmentos de bytes `Uint8Array`. Necesitamos unirlos en un solo resultado. Desafortunadamente, no hay un método simple que los concatene, por lo que hay un código para hacerlo:
```

2020-10-17 21:27 UTC, joaquinelio commented on 5-network/03-fetch-progress/article.md
> +Una vez más, ten en cuenta que eso no es para el progreso de *carga* (de ninguna manera ahora con `fetch`), solo para el progreso de *descarga*.
-bien traducido pero no se ve claro
-duda: Es bien claro que "carga" es subida ?
```suggestion
Una vez más, ten en cuenta que eso no es para el progreso de *carga* (hasta ahora eso no es posible con `fetch`), solo para el progreso de *descarga*.
```

2020-10-17 23:03 UTC, homero304 commented
/done

2020-10-18 03:31 UTC, joaquinelio approved these changes
ok

2020-10-19 16:22 UTC, vplentinax approved these changes
Ok

2020-10-19 22:14 UTC, merged