Cross origin requests
javascript-tutorial/es.javascript.info pull request #427
Opened 2020-10-19 02:33 UTC by MaskeZen

Se actualiza con la versión en inglés y se traduce el artículo.
Tengo algunas dudas con el término solicitud de "pre-vuelo" y el haber traducido "cross-origin", aunque en el caso de cross-origin, utilicé en un par de casos entre paréntesis el termino en inglés junto a la traducción para que el lector hispano tenga contacto con el termino original.

Espero no de muchos dolores de cabeza la revisión, saludos! 🧉

2020-10-19 05:38 UTC, joaquinelio commented
ooops conflictos...  mejor lo veo despues

dont worry, es que la sync está bastante al dia seguro son faciles, 
y como decis que te basaste en ingles resuelvo aceptando lo tuyo, deben ser los mismos cambios.

2020-10-20 13:58 UTC, joaquinelio commented
Todavia  no lo revise, pero veo que tiene 1 ejerccicio tambien prar traducir
task  solution
por las dudas: los svg no se tocan, tienen tratamiento especial.

2020-10-21 02:04 UTC, MaskeZen commented
> Todavia no lo revise, pero veo que tiene 1 ejerccicio tambien prar traducir
> task solution
> por las dudas: los svg no se tocan, tienen tratamiento especial.

Impecable, ahí agregué esos archivos que se me habían pasado.

2020-10-22 03:11 UTC, joaquinelio requested changes

2020-10-22 03:11 UTC, joaquinelio commented on 5-network/05-fetch-crossorigin/article.md
> +Por ejemplo, `fetch('http://another.com')` no enviará ninguna cookie, Incluso (!) esas que pertenecen al dominio `another.com`.
creo que esta bien,
incluso = ni siquiera ?

```suggestion
Por ejemplo, `fetch('http://another.com')` no enviará ninguna cookie, incluso (!) esas que pertenecen al dominio `another.com`.
```

2020-10-22 03:11 UTC, joaquinelio commented on 5-network/05-fetch-crossorigin/article.md
> +Si el servidor esta de acuerdo en aceptar solicitudes *with credentials*, debe agregar la cabecera `Access-Control-Allow-Credentials: true` a la respuesta, además de `Access-Control-Allow-Origin`.
```suggestion
Si el servidor está de acuerdo en aceptar solicitudes *with credentials*, debe agregar la cabecera `Access-Control-Allow-Credentials: true` a la respuesta, además de `Access-Control-Allow-Origin`.
```

2020-10-22 03:11 UTC, joaquinelio commented on 5-network/05-fetch-crossorigin/article.md
> +Cabe destacar que: `Access-Control-Allow-Origin` no es posible utilizar con un asterisco `*` para solicitudes con credenciales. Tal como se muestra a continuación debe proveer el origen exacto. Esto
prefiero 
estructura española
```suggestion
Cabe destacar que: `Access-Control-Allow-Origin` no se puede utilizar con un asterisco `*` para solicitudes con credenciales. Tal como se muestra a continuación debe proveer el origen exacto. Esto es una medida adicional de seguridad, para asegurar de que el servidor conozca exactamente en quién confiar para que le envíe este tipo de solicitudes.
```

2020-10-22 03:11 UTC, joaquinelio commented on 5-network/05-fetch-crossorigin/article.md
> +Por lo tanto, en la práctica, la diferencia se encuentra en que las solicitudes simples son realizadas de forma directa, utilizando la cabecera `Origin`, mientras que para las otras el navegador real
solamente 
para evitar la redundancia
```suggestion
Por lo tanto, en la práctica, la diferencia se encuentra en que las solicitudes simples son realizadas de forma directa, utilizando la cabecera `Origin`, mientras que para las otras el navegador realiza una solicitud extra de "pre-vuelo" para requerir la autorización.
```

2020-10-22 13:13 UTC, joaquinelio commented
corregido nombre pr pa'q bot lo entienda
corregido a issue17  pr427

2020-10-23 01:58 UTC, MaskeZen commented on 5-network/05-fetch-crossorigin/1-do-we-need-origin/solution.md
> +Necesitamos la cabecera `Origin`, ya que en algunos casos `Referer` no está presente. Por ejemplo, cuando realizamos un `fetch` desde una página HTTP a una HTTPS (desde un sitio menos seguro a uno má
¡Sí!, le erré ahí.

2020-10-23 02:00 UTC, MaskeZen commented on 5-network/05-fetch-crossorigin/article.md
> +Podemos utilizar cualquier método HTTP: no únicamente `GET/POST`, sino que también `PATCH`, `DELETE` y otros.
Supongo que acá abusamos un poco del "que".

2020-10-23 02:12 UTC, MaskeZen commented on 5-network/05-fetch-crossorigin/article.md
> +Hace algún tiempo atrás nadie podía siquiera imaginar que un sitio web pudiera realizar ese tipo de solicitudes. Por lo que aún existen servicios web que cuando reciben un método no estándar los cons
Yo no tengo la certeza, lo interpreté como que no revisan, pero creo que tu interpretación-traducción es más coherente con la versión en inglés.

2020-10-23 02:17 UTC, MaskeZen commented on 5-network/05-fetch-crossorigin/article.md
> +Por ejemplo, `fetch('http://another.com')` no enviará ninguna cookie, Incluso (!) esas que pertenecen al dominio `another.com`.
me quedé con tu sugerencia parcial "ni siquiera".

2020-10-23 02:19 UTC, MaskeZen commented
/done

2020-10-25 16:58 UTC, vplentinax requested changes
Buena traducción, solo algunas sugerencias.

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/1-do-we-need-origin/task.md
> +1. ¿Por que la cabecera `Origin` es necesaria, si `Referer` contiene incluso más información?
```suggestion
1. ¿Por qué la cabecera `Origin` es necesaria, si `Referer` contiene incluso más información?
```

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Pro ejemplo, probemos realizar una petición a `http://example.com`:
```suggestion
Por ejemplo, probemos realizar una petición a `http://example.com`:
```

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +CORS existe para proteger Internet de los malvados hackers.
Para mejor lectura.

```suggestion
CORS existe para proteger Internet de los hackers malvados.
```

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Si un sitio, por ejemplo, `another.com` requiere exponer datos con este tipo de acceso, el protocolo entonces llamado "JSONP (JSON con padding)" era utilizado.
También para mejor coherencia en la lectura.

```suggestion
Si un sitio, por ejemplo, `another.com` requiere exponer datos con este tipo de acceso, se utilizaba el protocolo llamado en ese entonces "JSONP (JSON con padding)" .
```

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Cuando intentamos realizar una solicitud "no simple", el navegador envía una solicitud especial de "pre-vuelo" consultándole al servidor si está de acuerdo en aceptar ese tipo de solicitud de origen
No se lee mal "pre-vuelo". Y se entiende en el contexto: una solicitud de comprobación desde el cliente hacia el servidor, antes del envío de cualquier otra solicitud.

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Access-Control-Allow-Origin: https://es.javascript.info
No creo que haya fallos al cambiar la url, pero ¿se probó que funcionara en el servidor?

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Access-Control-Allow-Origin: https://es.javascript.info
Misma duda que en la sugerencia anterior con el cambio de url

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Origin: https://es.javascript.info
Misma duda con la url

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Si se encuentra con una cabecera `Access-Control-Max-Age` con determinada cantidad de segundos, entonces los permisos son almacenados en el caché por ese determinado tiempo. La solicitud anterior ser
```suggestion
Si se encuentra con una cabecera `Access-Control-Max-Age` con determinada cantidad de segundos, entonces los permisos son almacenados en el caché por ese determinado tiempo. La solicitud anterior será cacheada por 86400 segundos (un día). Durante ese marco de tiempo, las solicitudes siguientes no requerirán la solicitud de pre-vuelo. Asumiendo que estén dentro de lo permitido en la respuesta cacheada, serán enviadas de forma directa.
```

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +Origin: https://es.javascript.info
Igual.

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +**Para solicitudes no simples, una solicitud preliminar de "pre-vuelo" es utilizada antes de la solicitud principal:**
```suggestion
**Para solicitudes no simples, se utiliza una solicitud preliminar "pre-vuelo"  antes de la solicitud principal:**
```

2020-10-25 16:58 UTC, vplentinax commented on 5-network/05-fetch-crossorigin/article.md
> +- Tras lo cual la solicitud es enviada, y el esquema previo utilizado para las solicitudes "simples" es aplicado.
```suggestion
- Tras lo cual la solicitud es enviada, y se aplica el esquema previo utilizado para las solicitudes "simples".
```

2020-10-25 19:55 UTC, joaquinelio commented
Sí, es terrible.
-prevuelo lo escribiria sin guion, pero no afecta.  Y no sé qué tan práctica es la metáfora si se entiende igual. 
-no me gustan las redundancias,  solicitud - solicitud
-aun hay algun problema de concordacias, ojo la sug de voz pasiva reformulada creo que tamb está mal.
-y por supuesto, las comas medievales de más. Las comas no son para marcar pausas. Batalla que asumo perdida pero siempre lo apunto.

Pero mientras no afecte el concepto, apruebo lo que venga. 
Ja ja !!!
está bueno.

Lo leo desp de que revises la revision de Valentina...

2020-10-27 00:30 UTC, MaskeZen commented on 5-network/05-fetch-crossorigin/article.md
> +Access-Control-Allow-Origin: https://es.javascript.info
Buen punto, voy a revisar las notas de contribución por que no estoy seguro de como probarlo.

2020-10-27 11:30 UTC, MaskeZen commented
Corté por lo sano y removí los `es.` de las URLs.

/done

2020-10-27 12:40 UTC, joaquinelio approved these changes
👍 
Yo creo que es hermoso.

2020-10-27 12:45 UTC, joaquinelio commented
Por las dudas, entendiste que "es terrible" era un chiste, ¿no?
Me han dicho que chistes, sarcasmos e ironias debo hacerlos explicitos con protocolos tags o emoji
qué gracia asi.

Como sea, aprobemos este bodrio así nos lo sacamos de encima.

2020-10-28 01:17 UTC, MaskeZen commented
👍🏽 Sí, lo interpreté en una buena.
Ya casi... jejeje

2020-10-30 01:46 UTC, vplentinax approved these changes
Oki

2020-10-30 02:33 UTC, merged