Form elements traducido
javascript-tutorial/es.javascript.info pull request #431
Opened 2020-10-20 03:56 UTC by kenliten

Traducido Form elements

2020-10-20 14:01 UTC, joaquinelio commented
todavia no lo revise, pero aviso que tiene task y solution para traducir tambien
y por las dudas: los svg no se tocan, tienen tratamiento especial

2020-10-22 11:30 UTC, joaquinelio requested changes
El nombre para que Don Bot lo registre es "Form properties and methods", puedo agregarlo a mano al issue pero

Faltan task y solution, podrias
* agregarlos aca y corrijo nombre e issue a mano, o
* hacer un nuevo pr con ambos y el nombre "Form properties and methods"
 y hago merge de este sin cambiar el nombre
* No vale la pena borrar este... que ya tiene la revision

2020-10-22 11:30 UTC, joaquinelio commented on 2-ui/4-forms-controls/1-form-elements/article.md
> +: El option está seleccionado.
sutil,
El option que está seleccionado 
o 
```suggestion
: Es el option seleccionado.
```

2020-10-22 11:49 UTC, joaquinelio commented
MERGE:
a quien lo haga,  plis verificar formatos anidados online
imposible de verificar dentro del hub

2020-10-22 12:20 UTC, kenliten commented
> El nombre para que Don Bot lo registre es "Form properties and methods", puedo agregarlo a mano al issue pero
> 
> Faltan task y solution, podrias
> 
>     * agregarlos aca y corrijo nombre e issue a mano, o
> 
>     * hacer un nuevo pr con ambos y el nombre "Form properties and methods"
>       y hago merge de este sin cambiar el nombre
> 
>     * No vale la pena borrar este... que ya tiene la revision

No entiendo a que te refieres con "Task y Solution" me aclaras?

2020-10-22 12:56 UTC, joaquinelio commented
Puedo.
los articulos tienen un subdirectorio por cada ejercicio.  La tuya tiene
article.md que ya hiciste, 
un svg que no se toca,
y /1-add-select-option/ con  task.md y solution.md dentro

https://github.com/kenliten/es.javascript.info/blob/kenliten/2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
https://github.com/kenliten/es.javascript.info/blob/kenliten/2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md

ah, el encabezado "importance: x" del task no se traduce aunque no se para que sirve.
happy translating 🎉

2020-10-22 13:38 UTC, kenliten commented
> Puedo.
> los articulos tienen un subdirectorio por cada ejercicio. El tuyo tiene
> article.md que ya hiciste,
> un svg que no se toca,
> y /1-add-select-option/ con task.md y solution.md dentro
> 
> https://github.com/kenliten/es.javascript.info/blob/kenliten/2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
> https://github.com/kenliten/es.javascript.info/blob/kenliten/2-ui/4-forms-controls/1-form-elements/1-add-select-option/solution.md
> 
> ah, el encabezado "importance: x" del task no se traduce aunque no se para que sirve.
> happy translating tada

Ok, perfecto.

Entonces deja los traduzco, y asi hago el pr con el ultimo que tome que ya lo tengo listo y estos tres en un solo pr.
💯 PeAcE!

2020-11-20 23:03 UTC, joaquinelio commented
@kenliten 
hello... anybody home?
me gustaria agregar esto, pero faltan  task y solution

o @vplentinax podes revisarlo, 
hacemos merge y agrego lo faltante como issue, ¡es muy poco lo que falta! Es una pena no aprovecharlo.

merge: no figura en el issue17, hay que agregarlo a mano

2020-11-27 01:16 UTC, joaquinelio commented
@kenliten oops!
Te había comentado que otro articulo requiere otro branch

he aquí

-----master no se toca, cada tanto haces

git fetch upstream
git merge upstream/master

----para cada articulo un branch

git branch articulo1
git checkout articulo1
----mods,,,  stage, commits...
git push origin articulo1
------ pr1

----depues de esto modificar el branch y push  es modificar el pr 

------- (ojo si quedaron cambios sin commit en el limbo se arrastran con el cambio de branch)
git checkout master
---- actualizas merge si hace falta

git branch articulo2
git checkout articulo2
----mods,,,  stage, commits...
git push origin articulo2
------- pr2

2020-11-28 14:55 UTC, kenliten commented
De acuerdo, perdón, ando algo messy, jaja, voy de nuevo

2020-11-28 23:11 UTC, joaquinelio commented
> De acuerdo, perdón, ando algo messy, jaja, voy de nuevo

¿sabes como hacerlo?
Me paso exactamente lo mismo hace un año #105 
me ayudaron y ahi aprendi bastante de git...
recomiendo ver la solucion ayuda a entender los commit

pero ya habia solucionado cortando y pegando como un niño de 5,
mas rapido porque sí tenia claro qué estaba haciendo (hay que ser cuidadoso para no perder nada) 

como sea, cuidado no rompas este pr que tiene ya mucho trabajo tuyo y de revision

2020-12-07 12:23 UTC, joaquinelio requested changes
esta bueno
sobran algunas comas qe salvo la obvia no las corrijo 
porque es batalla perdida =(

a ver si agregamos de una vez...

falta tan poco...

2020-12-07 12:23 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +- Cuando el botón del ratón es presionado, durante el arrastrado del ratón, puedes ir arriba o debajo de la barra de desplazamiento. Ésta seguirá funcionando (conveniente para el usuario).
```suggestion
- Cuando el botón del ratón es presionado, durante el arrastrado del ratón puedes ir por arriba o debajo de la barra deslizante. Ésta seguirá funcionando (es lo conveniente para el usuario).
```
coma, fluidez

2020-12-07 12:23 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +importancia: 5
```suggestion
importance: 5
```

2020-12-07 12:23 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +Hacer que todos los elementos con clase `draggable` -- sean arrastrables. Como la pelota de este capítulo.
```suggestion
Hacer que todos los elementos con clase `draggable` sean arrastrables. Como la pelota de este capítulo.
```

2020-12-07 12:23 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +- Si los elementos son arrastrados a los bordes superior/inferior de la ventana -- la página se desliza hacia arriba/abajo para permitir dicho arrastre.
```suggestion
- Si los elementos son arrastrados a los bordes superior/inferior de la ventana: la página se desliza hacia arriba/abajo para permitir dicho arrastre.
```

2020-12-07 12:23 UTC, joaquinelio commented on 2-ui/4-forms-controls/1-form-elements/1-add-select-option/task.md
> +importancia: 5
```suggestion
importance: 5
```

2020-12-07 12:23 UTC, joaquinelio commented on 2-ui/4-forms-controls/1-form-elements/article.md
> +Los formularios y controles, como `<input>` Tienen muchos eventos y propiedades especiales.
dos coma o ninguna 

no se pone coma para separar sujeto y predicado. Es ley.
pero sí para encerrar un modificador,
tambien puede ponerse 
Los formularios y controles (como `<input>`) tienen muchos eventos y propiedades especiales.

```suggestion
Los formularios y controles, como `<input>`, tienen muchos eventos y propiedades especiales.
```

2020-12-07 12:25 UTC, joaquinelio commented
no me voy a poner exquisito
ya lo revise asi, doble pr

onmerge solo hay que agregar el tilde en el issue 17

2020-12-17 17:05 UTC, vplentinax commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +# Barra de desplazamiento
Lo conozco más como "Barra de desplazamiento"

2020-12-17 17:06 UTC, vplentinax commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +Crea una barra de desplazamiento:
Lo mismo que lo anterior

2020-12-17 17:06 UTC, vplentinax commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +- Cuando el botón del ratón es presionado, durante el arrastrado del ratón, puedes ir arriba o debajo de la barra de desplazamiento. Ésta seguirá funcionando (conveniente para el usuario).
No quiero eliminar la palabra "desplazamiento". Quizas mejor hacer otra suggest solo para las otras correcciones.

2020-12-17 17:13 UTC, vplentinax approved these changes
Bien

2020-12-17 17:53 UTC, merged