Lgabrielvleon patch 1 -  Element size and scrolling
javascript-tutorial/es.javascript.info pull request #433
Opened 2020-10-22 02:26 UTC by lgabrielvleon

Traducción del capítulo  Element size and scrolling

2020-10-22 02:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=433) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=433) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=433) it.</sub>

2020-10-22 12:30 UTC, joaquinelio commented
Corregido nombre pr /  issue17

MERGE:  
Tiene 4 tasks y mucho formato anidado, 
verificar online como quedan, imposible probarlo debtro del hub
 
Listo, cuando se me pase la pereza lo reviso. 
Hasta mañana zzzz

2020-10-26 00:00 UTC, joaquinelio requested changes
varias cosas...
suelo re-revisar mi revision pero me estoy durmiendo

creo que edite el archivo para cambiar numeracion, si no fue en otro

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
> +2. `getComputedStyle` puede devolver un ancho no numérico como `"auto"` para un elemento en linea.
CREO 
que inline es la propiedad de posicionamiento, en ese caso no traduciria
No estoy seguro

```suggestion
2. `getComputedStyle` puede devolver un ancho no numérico como `"auto"` para un elemento inline.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
> +3. `clientWidth` es el contenido interior del area del elemento más los rellenos, mientras el ancho de CSS (con el estandar `box-sizing`) es el contenido interior del area *sin rellenos*.
```suggestion
3. `clientWidth` es el contenido interior del área del elemento más los rellenos, mientras el ancho de CSS (con el estándar `box-sizing`) es el contenido interior del área *sin rellenos*.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +# Elementos de tamaño y desplazamiento
Tamaños de elemento 
o 
```suggestion
# Elementos: tamaño y desplazamiento
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Este tiene el borde, relleno y desplazamiento. El conjunto completo de funciones. No hay margenes, ya que no son parte del elemento en sí, y estos no tiene propiedades especiales.
```suggestion
Este tiene el borde, relleno y desplazamiento. El conjunto completo de funciones. No hay márgenes, ya que no son parte del elemento en sí, y estos no tiene propiedades especiales.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Tu puedes [abrir el documento en la zona de pruebas](sandbox:metric).
acento vi que falta
Tú  vi 
or 
no tu ví

```suggestion
Puedes [abrir el documento en la zona de pruebas](sandbox:metric).
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Hay varias ocaciones en la que `offsetParent` es `null`:
```suggestion
Hay varias ocasiones en la que `offsetParent` es `null`:
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +- `scrollWidth = 324` -- es el ancho interior completo, aqui no tenemos desplazamiento horizontal, por lo que es igual a `clientWidth`.
```suggestion
- `scrollWidth = 324` -- es el ancho interior completo, aquí no tenemos desplazamiento horizontal, por lo que es igual a `clientWidth`.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +    Desde el punto de vista de CSS, `width:auto` es perfectamente normal, pero en JavaScript neceistamos un tamaño exacto en `px` que podríamos usar en los cálculos. Entonces, aquí el ancho de CSS wi
```suggestion
    Desde el punto de vista de CSS, `width:auto` es perfectamente normal, pero en JavaScript necesitamos un tamaño exacto en `px` que podríamos usar en los cálculos. Entonces, aquí el ancho de CSS width es inútil.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Y hay una razón más: una barra de desplazamiento. A veces, el código que funcionaba bien sin una barra de desplazamiento tiene errores, por que una barra de desplazmiento toma el espacio del contenid
```suggestion
Y hay una razón más: una barra de desplazamiento. A veces, el código que funcionaba bien sin una barra de desplazamiento tiene errores, porque una barra de desplazmiento toma el espacio del contenido en algunos navegadores. Entonces, el ancho real disponible para el contenido es *menor* que el ancho de CSS. Y `clientWidth/clientHeight` tenga eso en cuenta.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Tenga en cuenta que la diferencia descrita solo de leer `getComputedStyle(...).width` de JavaScript, visualmente todo es correcto.
```suggestion
Tenga en cuenta que la diferencia descrita es solo de leer `getComputedStyle(...).width` de JavaScript, visualmente todo es correcto.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +- `clientLeft/clientTop` -- las distancias desde la esquina exterior superior izquierda a la esquina interior superior izquierda (contenido + relleno). Para los Sistemas Operativos de izquierda. dere
```suggestion
- `clientLeft/clientTop` -- las distancias desde la esquina exterior superior izquierda a la esquina interior superior izquierda (contenido + relleno). Para los Sistemas Operativos de izquierda a derecha, siempre son los anchos de los bordes izquierdo/superior. Para los Sistemas Operativos de derecha a izquierda, la barra de desplazamiento está a la izquierda, por lo que `clientLeft` también incluye su ancho.
```

2020-10-26 00:00 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +- `scrollWidth/scrollHeight` -- el ancho/alto del contenido, al igual que `clientWidth/clientHeight`, pero también incluyela parte invisible desplazada del elemento.
```suggestion
- `scrollWidth/scrollHeight` -- el ancho/alto del contenido, al igual que `clientWidth/clientHeight`, pero también incluye la parte invisible desplazada del elemento.
```

2020-10-26 00:21 UTC, lgabrielvleon reviewed
/done

2020-10-26 00:21 UTC, lgabrielvleon commented on 2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
> +2. `getComputedStyle` puede devolver un ancho no numérico como `"auto"` para un elemento en linea.
Pero creo que el texto hace referencia a elementos en linea, y no a la propiedad "inline"

2020-10-26 22:29 UTC, joaquinelio requested changes
Creo que hoy tengo los ojos más limpios, encontré varios acentos faltantes...

Y vi que hay correcciones de tilde no aplicadas.  Puedo dejarme convencer en css, pero con los acentos estoy bastante convencido...

Lo importante es que el texto se lee bien,  lo prefiero online-

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Entonces, sin la barra de desplazamiento el ancho del contenido sería `300px`, pero si la barra de desplazamiento tiene un ancho de `16px` (el ancho puede variar entre dispositivos y navegadores) ent
```suggestion
Entonces, sin la barra de desplazamiento el ancho del contenido sería `300px`, pero si la barra de desplazamiento tiene un ancho de `16px` (el ancho puede variar entre dispositivos y navegadores) entonces solo queda `300 - 16 = 284px`, y deberíamos tenerlo en cuenta. Es por eso que los ejemplos de este capítulo asumen que hay una barra de desplazamiento. Sin él, algunos cálculos son más sencillos.
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Por ejemplo, `offsetParent` es `null`, y `offsetWidth`, `offsetHeight` son `0` cuando creamos un elemento, pero aun no lo han insertado en el documento, o eso (o su antecesor) tiene `display:none`.
```suggestion
Por ejemplo, `offsetParent` es `null`, y `offsetWidth`, `offsetHeight` son `0` cuando creamos un elemento, pero aún no lo han insertado en el documento, o eso (o su antecesor) tiene `display:none`.
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Por favor ten encuenta que `isHidden` retorna `true` para elementos que están en pantalla, pero tienen tamaño cero (como un `<div>` vacío).
```suggestion
Por favor ten en cuenta que `isHidden` retorna `true` para elementos que están en pantalla, pero tienen tamaño cero (como un `<div>` vacío).
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Se vuelve visible cuando el documento está de derecha a izquierda (el sistema operativo está en idioma Árabe o Hebreo). La barra de desplazamiento no está a la derecha, si no a la izquierda, y luego
```suggestion
Se vuelve visible cuando el documento está de derecha a izquierda (el sistema operativo está en idioma Árabe o Hebreo). La barra de desplazamiento no está a la derecha, sino a la izquierda, y luego `clientLeft` también incluye el ancho de la barra de desplazamiento.
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Esta propiedad proporciona el tamaño del area dentro del los bordes del elemento.
```suggestion
Esta propiedad proporciona el tamaño del área dentro del los bordes del elemento.
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Clic en el bton para expandir el elemento:
```suggestion
Clic en el botón para expandir el elemento:
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +La mayoría de las propiedades aqui son solo lectura, pero `scrollLeft/scrollTop` se puede cambiar, y el navegador desplazará el elemento.
```suggestion
La mayoría de las propiedades aquí son solo lectura, pero `scrollLeft/scrollTop` se puede cambiar, y el navegador desplazará el elemento.
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Si haces clic en el elemento de abajo, se ejecuta el codigo `elem.scrollTop += 10`. Eso hace que el contenido del elemento se desplace `10px` abajo.
```suggestion
Si haces clic en el elemento de abajo, se ejecuta el código `elem.scrollTop += 10`. Eso hace que el contenido del elemento se desplace `10px` abajo.
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +1. Primero, CSS `width/height` dependen de otra propiedad: `box-sizing` que define "qué es" CSS width y height. Un cambio en `box-sizing` para propísitos de CSS puede romper dicho JavaScript.
```suggestion
1. Primero, CSS `width/height` dependen de otra propiedad: `box-sizing` que define "qué es" CSS width y height. Un cambio en `box-sizing` para propósitos de CSS puede romper dicho JavaScript.
```

2020-10-26 22:29 UTC, joaquinelio commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Y hay una razón más: una barra de desplazamiento. A veces, el código que funcionaba bien sin una barra de desplazamiento tiene errores, porque una barra de desplazmiento toma el espacio del contenido
```suggestion
Y hay una razón más: una barra de desplazamiento. A veces, el código que funcionaba bien sin una barra de desplazamiento tiene errores, porque una barra de desplazmiento toma el espacio del contenido en algunos navegadores. Entonces, el ancho real disponible para el contenido es *menor* que el ancho de CSS. Y `clientWidth/clientHeight` tiene eso en cuenta.
```

2020-11-20 22:52 UTC, joaquinelio commented
@vplentinax 
podes hacer lo mismo aqui?
este pr es completo, fue revisado, lo corrigio, 
más revision y asi quedó

Tuvo ya mucho trabajo hecho, si te parece revisa y revisa mi revision,
es una buena adicion al repo

2020-12-17 17:02 UTC, vplentinax approved these changes
Lo veo bien. Avancemos.

2020-12-17 18:03 UTC, merged