Traducción articulo Fetch
javascript-tutorial/es.javascript.info pull request #435
Opened 2020-10-25 19:05 UTC by carlosabud

2020-10-25 19:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=435) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=435) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=435) it.</sub>

2020-10-25 20:29 UTC, joaquinelio commented
Hola
Todavia no lo revise pero te aviso que tiene ejercicios

uno ejercicio solo.  en tu branch
https://github.com/carlosabud/es.javascript.info/tree/master/5-network/01-fetch/01-fetch-users
task.md y solution.md

2020-10-25 22:31 UTC, joaquinelio requested changes
* Varios acentos, si no usas las suggest acordate de ponerlos
* Recordar que faltan task y solution
* Me permití corregir los nros de linea
necesitamos que coincidan con el inglés para poder hacer bien los pull

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +Los encabezados de respuesta estan dispobiles como un objeto de tipo Map dentro del `response.headers`.
```suggestion
Los encabezados de respuesta están disponibles como un objeto de tipo Map dentro del `response.headers`. 
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +Para especificar un encabezado en nuestro `fetch`, poddemos utilizar la opción `headers`. La misma posee un objeto con los encabezados salientes, como se muestra en el siguiente ejemplo:
```suggestion
Para especificar un encabezado en nuestro `fetch`, podemos utilizar la opción `headers`. La misma posee un objeto con los encabezados salientes, como se muestra en el siguiente ejemplo:
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +...Pero existe una [lista de encabezados]  (https://fetch.spec.whatwg.org/#forbidden-header-name) que no pueden ser especificados:
```suggestion
...Pero existe una [lista de encabezados](https://fetch.spec.whatwg.org/#forbidden-header-name) que no pueden ser especificados:
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +Pero, como vamos a enviar un objeto JSON, en su lugar utilizaremos la opción `headers` especificada a `application/json`, que es la opcion correcta `Content-Type` para información en formato JSON.
```suggestion
Pero, como vamos a enviar un objeto JSON, en su lugar utilizaremos la opción `headers` especificada a `application/json`, que es la opción correcta `Content-Type` para información en formato JSON.
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +Una aclaración, aquí no especificamos el `Content-Type` de manera manual, precisamente porque el objeto `Blob` posee un tipo incorporado (en este caso `image/png`, el cual es generado por la funcion
```suggestion
Una aclaración, aquí no especificamos el `Content-Type` de manera manual, precisamente porque el objeto `Blob` posee un tipo incorporado (en este caso `image/png`, el cual es generado por la función `toBlob`). Para objetos `Blob` ese es el valor por defecto del encabezado `Content-Type`.
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +Una petición fetch tipica esta formada por dos llamadas `await`:
```suggestion
Una petición fetch típica está formada por dos llamadas `await`: 
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +- `response.ok` -- Devuelve `true` si el Codigo HTTP es 200-299.
```suggestion
- `response.ok` -- Devuelve `true` si el código HTTP es 200-299.
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +- `response.status` -- Codigo HTTP de la respuesta.
```suggestion
- `response.status` -- Código HTTP de la respuesta.
```

2020-10-25 22:31 UTC, joaquinelio commented on 5-network/01-fetch/article.md
> +En el próximo capítulo veremos más sobre opciones y los casos de uso para `fetch`.
Son varios art de fetch...
```suggestion
En los próximos capítulos veremos más sobre opciones y casos de uso para `fetch`.
```

2020-10-26 02:40 UTC, carlosabud commented
Buenas Joaquin, ahí realicé un par de actualizaciones tomando tus sugerencias. 

Cualquier cosa avisame

2020-10-26 08:27 UTC, joaquinelio commented
Uh
Debí advertirte, no traducimos código, puede salir mal. 
Y no lo podemos probar acá.
(Pero los devs somos perfectos y no cometemos errores, para qué probar)  

Se traducen solamente // comentarios  /*  */
y usualmente mensajes entrecomillados  (con cuidado los backticks) pero no los string que participan de codigo

salvo eso, el article creo que ya está,  task y solution estan bien...
¿podrias poner codigo sin traducir?

2020-10-26 20:09 UTC, carlosabud commented
Creo que ahí estamos. Avisame!

2020-10-26 21:45 UTC, joaquinelio requested changes
Qudó un js
5-network/01-fetch/01-fetch-users/_js.view/solution.js
lo más seguro es poner el original entero,


al otro js le copie la linea vieja, 
5-network/01-fetch/01-fetch-users/_js.view/source.js
por lo menos el comentario quedo traducido...  =) 

- 
Estaba tentado a dejarlo asi, probarlo localmente
el problema es que a veces hacen cambios de codigo y el pull es directo
es posible por ej que agreguen una linea usando la variable ingles y nadie se de cuenta de que el codigo se malogro

Mas  par de cositas,

2020-10-26 21:45 UTC, joaquinelio commented on 5-network/01-fetch/01-fetch-users/_js.view/source.js
> +async function obtenerUsuarios(nombresUsuarios) {
```suggestion
async function getUsers(names) {
```

2020-10-26 21:45 UTC, joaquinelio commented on 5-network/01-fetch/01-fetch-users/solution.md
> +Si en su lugar utilizáramos `await Promise.all(names.map(name => fetch(...)))` y llamamos a la función `.json()` sobre los resultados, entonces esperaríamos a que todos las peticiones fetch completen
hoy estoy medio lento y no se explicarlo, pero creo que va "de"

"Nosotros aseguramos que las peticiones"             
"Nosotros nos aseguramos DE que las peticiones"

queismo/dequeismo, el truco de reemplazar por "eso"
"Nos aseguramos de eso"
```suggestion
Si en su lugar utilizáramos `await Promise.all(names.map(name => fetch(...)))` y llamamos a la función `.json()` sobre los resultados, entonces esperaríamos a que todos las peticiones fetch completen antes de obtener una respuesta. Al agregar `.json()` directamente en cada `fetch`, nos aseguramos de que las peticiones se procesen de manera independiente obteniendo una mejor respuesta en nuestra aplicación. 
```

2020-10-26 21:45 UTC, joaquinelio commented on 5-network/01-fetch/01-fetch-users/solution.md
> +Esto es un ejemplo de como la API de Promesas puede ser útil aunque mayormente se utilice `async/await`.
```suggestion
Esto es un ejemplo de cómo la API de Promesas puede ser útil aunque mayormente se utilice `async/await`.
```

2020-10-27 01:59 UTC, carlosabud commented
Listo. Perdón por las idas y vueltas. 

/done

2020-10-27 12:13 UTC, joaquinelio approved these changes
👍

2020-10-27 13:53 UTC, carlosabud commented
@joaquinelio por las dudas, no me deja completar el PR. Supongo que hará falta que otra persona con permisos revise el PR y lo complete. Saludos!

2020-10-27 16:12 UTC, joaquinelio commented
Sí, solo maintainers pueden continuarlo.

- El branch y el PR son tuyos, podes hacer y deshacer.
- merge dentro del repo solo la puede hacer alguien con permisos,
- la aprobación es cuestion de procedimiento, lo esperable es que dos personas aprueben y el bot de Ilya responde cambiando los cartelitos.  
- Vos podrias hacer review y aprobar el PR de otra persona, y aunque el BOT te ignore, el maintainter no 
 (especialmente por la escasez de reviewers)

Ja, deberia poner esto en el curso de git filosofico 
para complementar cualquier curso de comandos git

2020-10-30 01:43 UTC, vplentinax approved these changes
Ok

2020-10-30 02:34 UTC, merged