Proxy and Reflect
javascript-tutorial/es.javascript.info pull request #451
Opened 2020-11-27 03:37 UTC by joaquinelio

Finally! 
1033 lineas
ok, la mitad vacias, la mitad de mitad codigo
pero es el mas largo y complejo del repo

1) use trampa para trap, algo incomodo, pero es la trampa de osos que atrapa operaciones, ¿que otra cosa podia poner? 
podia dejar TRAP, todo el mundo la entiende

2)  El articulo original es excelente, pero deberia mejorar la granatuca y hacerla mas suave    
Fui muy liberal en la traduccion no técnica
tambien extendi algunas cosas

2020-11-27 03:46 UTC, joaquinelio commented
I know, Mr Bot.

2020-12-13 21:04 UTC, vplentinax commented
Me lo pienso para comenzar esta revisión... Pronto lo haré

2020-12-14 06:40 UTC, joaquinelio commented
> Me lo pienso para comenzar esta revisión... Pronto lo haré

podes hacerla en comodas cuotas...

pero si podes dar algo de tiempo, la sync es siempre prioridad 
Y las mantengo pequeñas para minimizar conflicto, no deberia llevar mucho tiempo.

2020-12-18 18:00 UTC, vplentinax requested changes
Revision de tareas y del articulo hasta la línea 200.

2020-12-19 01:02 UTC, joaquinelio commented
>No comprendo muy bien la frase, ¿podría mejorarse?

`181 El proxy debe reemplazar totalmente el objeto target en todo lugar. Nadie debe jamás hacer referencia al objeto target después de haberlo hecho el proxy. De otro modo sería fácil manipularlo.
`

ya es "fácil manipularlo.", lo que es facil es arruinarlo  ("trastearlo"! puse jajaj!!!)
seria facil de explicartelo informalmente, pero deberia quedar claro ACA. 
¿puedo apartarme del original y repasar lo que es la envoltura (wrapper) ?  Me permito redundancias..

pruebo con

`El proxy debe reemplazar completamente al objeto "target" que envolvió .  El proxy debe supervisar todas sus operaciones: nadie debe jamás hacer referencia al objeto target saltando tal envoltura.  De otro modo sería fácil desbaratarlo. 
`

2020-12-23 18:31 UTC, vplentinax requested changes
Revisón hasta la línea 592. Ya vamos por la mitad. Realmente está muy bien, pocas cosas que arreglar.

2020-12-23 18:31 UTC, vplentinax commented on 1-js/99-js-misc/01-proxy/article.md
> +Hay una convención extendida que propiedades y métodos que comienzan con guion bajo`_` son de uso interno. Ellos no deberían ser accedidos desde fuera del objeto.
```suggestion
Hay una convención extendida en la que propiedades y métodos que comienzan con guion bajo`_` son de uso interno. Ellos no deberían ser accedidos desde fuera del objeto.
```

2020-12-23 18:31 UTC, vplentinax commented on 1-js/99-js-misc/01-proxy/article.md
> +// después de esta envoltiura, llamados a sayHi serán demorados por 3 segundos
```suggestion
// después de esta envoltura, los llamados a sayHi serán demorados por 3 segundos
```

2020-12-23 18:33 UTC, vplentinax reviewed
Me gustó, me parece más claro. Me refiero a lo que arreglaste en **reformulacion 181 "proxy vs target ** @joaquinelio

2020-12-23 23:59 UTC, joaquinelio commented
@vplentinax  
Reescribí linea 328 que seguia confusa.

2021-01-17 18:03 UTC, vplentinax approved these changes
Pequeñas cositas, una vez aceptadas puedes hacer merge!

2021-01-17 18:03 UTC, vplentinax commented on 1-js/99-js-misc/01-proxy/article.md
> +Por ejemplo, el método `getName()` accede a la propiedad privada `#name` y falla por hacerlo proxy:
```suggestion
Por ejemplo, el método `getName()` accede a la propiedad privada `#name` y  se interrumpe después del proxy:
```

2021-01-17 18:03 UTC, vplentinax commented on 1-js/99-js-misc/01-proxy/article.md
> +La razón es que los campos privados son implementados usando slots internos. JavaScript no usa `[[Get]]/[[Set]]` cuando los accede.
```suggestion
La razón es que los campos privados son implementados usando slots internos. JavaScript no usa `[[Get]]/[[Set]]` cuando accede a ellos.
```

2021-01-17 20:49 UTC, joaquinelio commented on 1-js/99-js-misc/01-proxy/article.md
> +Por ejemplo, el método `getName()` accede a la propiedad privada `#name` y falla por hacerlo proxy:
No, no se interrumpe, falla, porque no encuentra la variable.

Y  no "después del proxy" en todo caso sería "después de convertirlo a proxy"
pero puse "POR" porque la falla es consecuencia de convertirlo.
Falla, por haberlo convertido en proxy.

No enconctré forma comoda de traducir el ubicuo "proxing" que traduje como "hacerlo proxy"
¡ proxificar  ?

2021-01-17 21:08 UTC, joaquinelio commented on 1-js/99-js-misc/01-proxy/article.md
> +Por ejemplo, el método `getName()` accede a la propiedad privada `#name` y falla por hacerlo proxy:
un problema que no vi de poner "hacerlo proxy" es q parece que convirtiera al metodo, 
deberia aclarar que convierto el objeto entero o escribirlo mas vagamente

"...falla despues de hacer el proxy"
"...falla despues de la conversión a proxy" 
"...falla depués de la proxificación. "  

no me parece nada mal la idea. Es muy comodo tener la palabra proxificar.  

tamb puedo sobreaclarar 
"...falla depués de la proxificación del objeto user. "  

@vplentinax , pienso poner 
"...falla depués de la proxificación. "  
¿que tal?

2021-01-18 10:56 UTC, joaquinelio commented
Novedades

-Acepté (alguno de mala gana :P ) tus cambios.
-Menos uno que rechazo porque le erra (o yerra) al concepto, pero deje comentada una versión alternativa que creo mejor.
-También hubo 3 conflictos que acabo de resolver y podrias revisar.  La mejora de Ilya es buena, mejor la explicacion y alternativas de manejo del metodo "revoke".   lineas 966-972 (o podes cliquear los commits para ver las idas y venidas...)

2021-01-25 02:48 UTC, joaquinelio commented
Acepte todas las sug excepto linea 845 porque era un error conceptual que no puedo aceptar.

Es el unico articulo que falta de la seccion Js,
es el más largo de todo el repo, 
el PR  ya cumplio dos meses,

y la demora genera conflictos que tengo que andar resolviendo
  
El art es bueno, vale la pena el merge

2021-01-25 02:48 UTC, merged