Forms event and method submit
javascript-tutorial/es.javascript.info pull request #454
Opened 2020-12-09 21:46 UTC by puntope

2020-12-09 21:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=454) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=454) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=454) it.</sub>

2020-12-10 13:35 UTC, joaquinelio requested changes
bienvenido

algunos acentos,
las cuestiones de forma podes ignorarme, el articulo es muy claro

tuviste el criterio de traducir value pero no name o type...
aja...
es que siempre ando buscando reviewers, aunque el bot te ignore podes dejar las correcciones y comentarios

otra forma de ayudar, 
cada tanto hacemos merge desde ingles,
cuando hay más de un par de lineas descarto los cambios y los paso a issues. "actualizar"
Por un lado es mas facil porque es menos cantidad, 
por otro lado mas complejo porque hay que comparar con el repo ingles, 
revisar el historial de commits, y corregir los nros de lineas  (me ayudo con vscode +gitlens que hace diff con cualquier remoto)

2020-12-10 13:35 UTC, joaquinelio commented on 2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/solution.md
> +También podemos prevenir el scroll en la página utilizando `body.style.overflowY='hidden'`.
probablemente esté bien...
pero creo que lleva a preparación,
creo que es mucho mas directo:
```suggestion
También podemos evitar el scroll en la página utilizando `body.style.overflowY='hidden'`.
```

2020-12-10 13:35 UTC, joaquinelio commented on 2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
> +- En caso contrario si el usuario pulsa `key:Esc` o CANCELAR, entonces `callback(null)` es llamado.
solo sugiero,
no se explicarlo
 ```suggestion
- En caso contrario, si el usuario pulsa `key:Esc` o CANCELAR, entonces `callback(null)` es llamado.
```

2020-12-10 13:35 UTC, joaquinelio commented on 2-ui/4-forms-controls/4-forms-submit/1-modal-dialog/task.md
> +- El formulario debe de estar en el centro de la ventana.
anoté el motivo en otro comentario...

```suggestion
- El formulario debe estar en el centro de la ventana.
```

2020-12-10 13:35 UTC, joaquinelio commented on 2-ui/4-forms-controls/4-forms-submit/article.md
> +Ambas acciones causan que el evento `submit` sea activado en el formulario. El handler puede comprobar los datos, y si hay errores, mostrarlos e invocar `event.preventDefault()`, entonces el formular
Sin sugerencia, comento

me agrada handler en inglés, y en este caso hace una unica aparicion, quizas sea menos confuso 
yo lo traduzco como manejador, 
otros como controlador (y hay pelea) 
pero prefiero manejador para simples metodos/callback handler, 
y reservar controlador para los objetos "controller" aunque  parece que js usa .

2020-12-10 13:36 UTC, joaquinelio commented
Cambio titulo, agrego al issue a mano
confirmarlo al hacer merge

2020-12-10 19:36 UTC, puntope commented
/done

2020-12-10 19:37 UTC, puntope commented
/done

2020-12-10 21:52 UTC, joaquinelio commented
hola, @puntope 
casi ok
eeehhh... quedaron dos sin resolver,
de los que no negocio, "a veces" y un typo

2020-12-10 21:55 UTC, puntope commented
/done

2020-12-10 21:58 UTC, joaquinelio approved these changes
wow that s was fast
...

yes!
👍 

waiting for the second reviewer now...

2020-12-13 21:01 UTC, vplentinax approved these changes
Todo bien...

2020-12-14 06:20 UTC, merged