Drag'n'Drop with mouse events
javascript-tutorial/es.javascript.info pull request #466
Opened 2020-12-25 18:31 UTC by kenliten

Hola @joaquinelio!
Lamento mucho la demora, tuve muchos problemas lidiando con una distro que no conocía e intenté traducir desde el celular y creé muchos problemas, así que al final, tuve que eliminar mi fork y con el el progreso, para crear un nuevo fork, un nuevo branch y bueno, aquí está el primer artículo.

PeAcE!

2020-12-26 20:29 UTC, joaquinelio commented
hola!
no es una carrera...
y tus aportes ya sumaron al proyecto

disculpame ahora la crítica, 
"importance: " de las task no se traducen, NO SE por qué, es metadata pero no se para que la usa
y la verdad que en ingles queda feo, 
pero específicamente (en el readme) pidio que no tradujeramos
```

Metadata
Some files, usually tasks, have YAML metadata at the top, delimited by ---:

importance: 5

---
...
Please don't translate "importance" (and other top metadata).

```

2020-12-26 20:31 UTC, kenliten commented
Oh ok!

2020-12-26 21:27 UTC, joaquinelio requested changes
typos  y sugerencias

No traduzcas "importance" en task porque es metadata que no se para que corno es

sobre lo que puse de aclarar "mousedown", no hace falta, lo resolviste bien y queda claro.

2020-12-26 21:27 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Lo mismo con un elemento arrastrable. La pelota está siempre sobre los demás elementos, así que los eventos pasan en él. Cualquier que sea el manejador que pongamos en los elementos de abajo, no func
solo sug, "ocurren"
"cualquiera que sea el" o mejor quitando palabras

```suggestion
Lo mismo con un elemento arrastrable. La pelota está siempre sobre los demás elementos, así que los eventos pasan en él. Cualquier manejador que pongamos en los elementos de abajo, no funcionará.
```

2020-12-26 21:27 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +// arrastrable potencial sobre el que flotamos ahora mismo
correcto, pero quisiera algo mas claro

si no lo consigo hasta preferiria eliminar tanto adjetivo
"elemento arrastrable sobre el que" 

```suggestion
// elemento potencialmente arrastrable sobre el que flotamos ahora mismo
```

2020-12-26 21:27 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +En el siguiente ejemplo cuando la pelota se arrastra sobre la protería, esta se resalta.
aca no le decimos porteria pero supongo que es el localismo que todos pueden entiender

```suggestion
En el siguiente ejemplo cuando la pelota se arrastra sobre la portería, esta se resalta.
```

2020-12-26 21:27 UTC, joaquinelio commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Hay frameworks que construyen una arquitectura sobre éste: `DragZone`, `Droppable`, `Draggable` y otras clases. La mayoría de ellos hacen cosas similares a lo que hemos descrito anteriormente, así qu
no esta mal
solo sugerencia !!!!
varias

```suggestion
Hay frameworks que construyen una arquitectura sobre esto: `DragZone`, `Droppable`, `Draggable` y otras clases. La mayoría de ellos hacen cosas similares a lo que hemos descrito, así que debería ser fácil entenderlos ahora. O crea el tuyo propio: como puedes ver es fácil de hacer, a veces es más fácil que adaptarse a una solución de terceros.
```

2020-12-26 21:57 UTC, kenliten commented
/done
Si eso era todo, estamos listos!

2021-01-15 06:33 UTC, joaquinelio commented
Hola capo

No, no era todo. Hay que deshacer los dos cambios 
"importance: 5"
no puedo editarlo ni me deja sugerir cambios no se por qué

ya va un mes, 
si no aparece segundo reviewer lo reviso de nuevo y  -> merge.

2021-01-15 06:39 UTC, joaquinelio commented
@kenliten 
ah, borraste tu branch
pero github aun lo recuerda en nosedonde, 
asi que se puede hacer merge igual 
y corregir lo de "importance" después

2021-01-15 21:09 UTC, kenliten commented
Si, lo borre, pense que ya habias hecho el merge, y ahora intento pero no me permite editarlos

2021-01-16 03:46 UTC, joaquinelio commented
No te permite porque está trabajando con una versión congelada

Voy a hacer merge y un despues PR con más cambios para:

- arreglar "importance:"  (aunque nadie lo extrañe)
- legibilidad de las lineas mas importantes del principio

2021-01-16 03:46 UTC, merged