Alternation (OR) |
javascript-tutorial/es.javascript.info pull request #473
Opened 2021-01-17 18:24 UTC by vplentinax

2021-01-17 23:43 UTC, joaquinelio requested changes
lo del escape...

2021-01-17 23:43 UTC, joaquinelio commented on 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/solution.md
> +- Entonces, si tenemos una barra invertida `pattern:\\` (técnicamente tenemos que duplicarlo en el patrón, porque es un carácter especial, por lo que es una sola barra invertida de hecho), entonces c
1 ¿puedo simplificar?

2 sutil que no se explicar cambie un entonces por luego, podes deshacerlo ( tiene que ver con como viene la explicacion)

```suggestion
- Entonces, si tenemos una barra invertida `pattern:\\` (tenemos que duplicarla en el patrón porque es un carácter especial), y luego cualquier carácter está bien después de él (un punto).
```

2021-01-17 23:43 UTC, joaquinelio commented on 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md
> +Tenga en cuenta, en particular, que una comilla doble `subject:\"` no termina una cadena.
```suggestion
Tenga en cuenta, en particular, que una comilla escapada `subject:\"` no termina una cadena.
```
o 
comilla doble escapada
o 
comilla doble escapada con '\\'

2021-01-17 23:43 UTC, joaquinelio commented on 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md
> +Por lo tanto, deberíamos buscar de una cita a otra ignorando las comillas dobles en el camino.
esto es conceptual, 
quotes puede ser comillas o el contenido de ellas (la cita) 

aca no buscamos "citas"  sino atrapar "comillas"  pero dejando ir las comillas escapadas
el caracter de escape  \\ es justamente eso, para  ignorarlas

```suggestion
Por lo tanto, deberíamos buscar de una comilla a otra (la de cierre), ignorando las comillas escapadas en el camino.
```

2021-01-17 23:43 UTC, joaquinelio commented on 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md
> +.. *!*"Say \"Hello\"!"*/!* ... (comillas dobles dentro)
```suggestion
.. *!*"Say \"Hello\"!"*/!* ... (comillas escapadas dentro)
```

2021-01-17 23:43 UTC, joaquinelio commented on 9-regular-expressions/13-regexp-alternation/03-match-quoted-string/task.md
> +.. *!*"\\ \""*/!* ..  (doble barra lateral dentro y comilla doble.)
```suggestion
.. *!*"\\ \""*/!* ..  (doble barra y comilla escapada dentro.)
```

2021-01-17 23:43 UTC, joaquinelio commented on 9-regular-expressions/13-regexp-alternation/article.md
> +# Altarnancia (OR (O)) |
Alternancia
en mi español da mas idea de ciclo, 
pero segun la RAE sifnifica lo mismo que en ingles, variantes de morfemas  (ej de diminutivos; cito, ito, illo....) 
O sea, una terrible elección EN INGLEs debiernon poner variantes o alternativas u opciones, eso es la O.
una cosa O la otra O otra otra.
REGEXP es viejo, (lo use en el 80) no se si alternance se usa desde hace mucho, tampoco encontre ref en español...
como sea, no estoy en condiciones de vetar alternancia.

jaja 
sorry la digresion

2021-01-19 16:07 UTC, vplentinax commented on 9-regular-expressions/13-regexp-alternation/article.md
> +# Altarnancia (OR (O)) |
Ponlo como suggest!

2021-01-20 08:08 UTC, joaquinelio requested changes
comillas y espacios, 
hay varios pero se me cruzan los ojos tengo que andar + y - zoom, sorry la review deficiente

sugiero una linea que creo que es una mejora conceptual, 
no la mando al inglés porque ya estoy molestando demasiado y la ultima Ilya la aprobo de mala gana (y no era buena, en esp quedo mejor)  
Claro que si cambia en algo el concepto no lo cambio en ESP si Ilya no lo acepta en ENG, no es el caso.  

este es un art corto pero arduo, buen aporte al repo
Ya no tengo objeciones conceptuales,  me gustaria que hicieras el merge aceptes o no los nuevos cambios

2021-02-03 11:42 UTC, merged