IndexedDB
javascript-tutorial/es.javascript.info pull request #491
Opened 2021-03-12 17:45 UTC by joaquinelio

2021-03-12 18:31 UTC, joaquinelio commented
Trabajé con indexeddb (Crudo sin idb) hace un par de años,
igual la traduccion  fue ardua
seria bueno una revision de un vet

igual le tengo confianza
es preferible que este online

El articulo original es execlente, 
y saberlo te permite enfrentar cualquiera de las bases mas gordas de server 
menos el sql,  
pero claves, indices, transacciones, cursores, TODO esta ahi, explicadisimo

2021-03-25 15:07 UTC, joaquinelio commented
ppffff por mi culpa ilya rescribio varias partes
7 conflictos
hecho.

2021-05-13 03:51 UTC, joaquinelio commented
8 conflictos nuevos, hecho.

2021-05-15 03:14 UTC, joaquinelio commented
2 conflictos resueltos
trabajo ocioso, deberia estar online

2021-07-28 14:12 UTC, joaquinelio commented
cobflicto resuelto 
mine wins

2021-08-02 12:03 UTC, vrivas reviewed
He realizado solo tres modificaciones para ver si la forma en la que lo hago es correcta.

2021-08-02 12:03 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +También podemos usar `async/await` con la ayuda de un contenedor basado en promesas como idb <https://github.com/jakearchibald/idb>. Es muy conveniente, pero el contenedor no es perfecto y no puede r
```suggestion
También podemos usar `async/await` con la ayuda de un contenedor basado en promesas como idb <https://github.com/jakearchibald/idb>. Aunque ésto es muy conveniente, hay que tener en cuenta que el contenedor no es perfecto y no puede reemplazar a los eventos en todos los casos. Así que comenzaremos con eventos y, cuando hayamos avanzado en el entendimiento de IndexedDb, usaremos el contenedor.
```

2021-08-02 12:03 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Tal poder usualmente es excesivo para las aplicaciones tradicionales cliente-servidor. IndexedDB está previsto para aplicaciones fuera de línea, para ser combinado con ServiceWorkers y otras tecnolog
```suggestion
Toda esta potencia es normalmente excesiva para las aplicaciones cliente-servidor tradicionales. IndexedDB está previsto para aplicaciones fuera de línea, para ser combinado con ServiceWorkers y otras tecnologías.
```

2021-08-02 12:03 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +IndexedDB es una base de datos construida dentro del navegador, mucho más poderosa que `localStorage`.
```suggestion
IndexedDB es una base de datos construida dentro del navegador, mucho más potente que `localStorage`.
```

2021-08-02 12:26 UTC, joaquinelio commented
se pueden hacer varias revisiones,

para que el bot me avise pones "finish review" pero con "change req"
luego hago (o descarto/desprecio) los cambios, y pongo /done
entonces el bot te avisa para que re-revises

2021-08-02 12:54 UTC, joaquinelio commented
1 ¡Excelentes los cambios de redacción! Estaban algo pegoteados al ingles. No creo que mal, pero ahora es mucho más legible y es lo que importa
2 "ésto" no se acentua
3 me hiciste avergonzar con esa coma colgada, siempre las critico y no es de las que perdono.
4 no entendí poderosa/potente pero como me da igual lo acepté. 
 Una vez se burlaron mundialmente porque puse "saltear" en lugar de "saltar". Aunque RAE registra "saltear = omitir" como americanismo, América también se burló de mí. Abatido.

2021-08-02 14:44 UTC, vrivas reviewed
No es fácil :)

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +  // la versión de la base existente en menor que 2 (o ni siquiera existe)
```suggestion
  // la versión de la base existente es menor que 2 (o ni siquiera existe)
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +2. Luego publicamos una actualización, así que nuestro código en más nuevo.
```suggestion
2. Luego publicamos una actualización, así que nuestro código es más reciente.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Para organizar esto, se dispara el evento `versionchange` (cambio-de-versión) en el objeto de base de datos. Debemos escucharlo y cerrar la conexión vieja (y probablemente sugerir una recarga de pági
```suggestion
Para solucionar este tipo de situaciones, se dispara el evento `versionchange` (cambio-de-versión) en el objeto de base de datos que ha quedado obsoleto. Debemos dicho evento y cerrar la conexión vieja (y probablemente sugerir una recarga de página, para cargar el código actualizado).
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Aquí hacemos dos cosas:
```suggestion
Dicho de otra forma, el código anterior hacemos dos cosas:
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +2. La escucha a `openRequest.onblocked` nos informa la situación opuesta: hay una conexión obsoleta en algún otro lugar que no fue cerrada y por eso la conexión nueva no se pudo realizar.
```suggestion
2. La escucha a `openRequest.onblocked` nos informa de la situación opuesta: hay una conexión obsoleta en algún otro lugar que no fue cerrada y por eso la conexión nueva no se pudo realizar.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Estas colisiones ocurren raramente, pero debemos al menos tener algún manejo de ella, como mínimo un manejador `onblocked` para evitar que nuestro script muera silenciosamente.
```suggestion
Estas colisiones ocurren raramente, pero debemos tener algún manejo de ella, como mínimo un manejador `onblocked` para evitar que nuestro script muera silenciosamente.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +De forma similar a `localStorage`, podemos proporcionar una clave cuando agregamos un valor al almacén. Cuando lo que almacenamos son objetos, IndexedDB permite asignar una propiedad del objeto como
```suggestion
De forma similar a `localStorage`, podemos proporcionar una clave cuando agregamos un valor al almacén. Cuando lo que almacenamos son objetos, IndexedDB permite asignar una propiedad del objeto como clave, lo que es mucho más conveniente. También podemos usar claves que se generan automáticamente.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Pero necesitamos crear el almacén de objetos primero.
```suggestion
Pero primero, necesitamos crear el almacén de objetos.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Si no establecemos `keyOptions`, necesitaremos proporcionar una clave explícitamente luego, al momento de almacenar un objeto.
```suggestion
Si no establecemos `keyOptions`, necesitaremos proporcionar una clave explícitamente más tarde: al momento de almacenar un objeto.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +**Un almacén de objetos solo puede ser creado o modificado durante la actualización de su versión. Esto es en el manejador `upgradeneeded`.**
```suggestion
**Un almacén de objetos solo puede ser creado o modificado durante la actualización de su versión., esto es, en el manejador `upgradeneeded`.**
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +1. Crea una transacción, mencionando todos los almacenes que irá a acceder, en `(1)`.
```suggestion
1. Crea una transacción, mencionando todos los almacenes a los que irá a acceder, en `(1)`.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +4. ...Maneja el éxito o fracaso de la petición `(4)`, entonces podemos hacer otras peticiones si lo necesitamos, etc.
```suggestion
4. ...Maneja el éxito o fracaso de la petición `(4)`, a continuación podemos hacer otras peticiones si lo necesitamos, etc.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Al igual que al abrir una base de datos, podemos enviar una petición: `books.add(book)`, y esperar por los eventos `success/error`.
```suggestion
Al igual que al abrir una base de datos, podemos enviar una petición: `books.add(book)` y quedar a la espera  de los eventos `success/error`.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +En el ejemplo anterior empezamos la transacción e hicimos una petición `add`. Pero como explicamos antes, una transacción puede tener muchas peticiones asociadas, que deben todas ser exitosas o todas
```suggestion
En el ejemplo anterior, empezamos la transacción e hicimos una petición `add`. Pero, como explicamos antes, una transacción puede tener muchas peticiones asociadas, que deben todas ser exitosas o todas fallar. ¿Cómo marcamos que una transacción se da por finalizada, que no tendrá más peticiones asociadas?
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Usualmente podemos asumir que una transacción se consuma cuando todas sus peticiones fueron completadas, y el código actual finaliza.
```suggestion
De forma general, podemos asumir que una transacción se consuma cuando todas sus peticiones fueron completadas y el código actual finaliza.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +El principio de auto-commit de las transacciones tiene un efecto colateral importante. No podemos insertar una operación asincrónica como `fetch`, `setTimeout` en el medio de la transacción. IndexedD
```suggestion
El principio de auto-commit de las transacciones tiene un efecto colateral importante. No podemos insertar una operación asincrónica como `fetch`, `setTimeout` en mitad de una transacción. IndexedDB no mantendrá la transacción esperando a que terminen.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +En el código debajo, `request2` en la línea `(*)` falla, porque la transacción ya está finalizada y no podemos hacer más peticiones sobre ella:
```suggestion
En el siguiente código, `request2` en la línea `(*)` falla, porque la transacción ya está finalizada y no podemos hacer más peticiones sobre ella:
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Esto es porque `fetch` es una operación asincrónica, una macrotarea. Las transacciones son cerradas antes de que el navegador comience con las macrotareas.
```suggestion
Esto es porque `fetch` es una operación asincrónica, una macrotarea. Las transacciones se cierran antes de que el navegador comience con las macrotareas.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Pero será mucho mejor, si queremos mantener las operaciones juntas en una transacción, separar las transacciones IndexedDB de la parte asincrónica.
```suggestion
Pero, si queremos mantener las operaciones juntas en una transacción, será mucho mejor separar las transacciones IndexedDB de la parte asincrónica.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Solo `complete` garantiza que la transacción fue guardada como un todo. Las peticiones Individuales pueden ser exitosas, pero la operación final de escritura puede ir mal (por ejemplo por un error de
```suggestion
Solo `complete` garantiza que la transacción fue guardada como un todo. Las peticiones individuales pueden ser exitosas, pero la operación final de escritura puede ir mal (por ejemplo por un error de Entrada/Salida u otra cosa).
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Esto es esperable, no solo por posibles errores de nuestro lado, sino también por razones no relacionadas a la transacción misma. Por ejemplo, la cuota de almacenamiento exedida. Entonces debemos est
```suggestion
Esto es esperable, no solo por posibles errores de nuestro lado, sino también por razones no relacionadas con la transacción en si misma. Por ejemplo, la cuota de almacenamiento podría haberse exedido. Por tanto, debemos estar preparados para manejar tal caso.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +En algunas situaciones, podemos querer manejar el fallo (por ejemplo, intentar otra petición), sin cancelar los cambios en curso, y continuar la transacción. Eso es posible. El manejador `request.one
```suggestion
En algunas situaciones, podemos querer manejar el fallo (por ejemplo, intentar otra petición), sin cancelar los cambios en curso, y continuar la transacción. Eso es posible. El manejador `request.onerror` es capaz de evitar el aborto de la transacción llamando a `event.preventDefault()`.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +¿Necesitamos onerror/onsuccess en cada petición? No siempre. Podemos en cambio usar la delegación de eventos.
```suggestion
¿Necesitamos onerror/onsuccess en cada petición? No siempre. En su lugar podemos usar la delegación de eventos.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Todos los eventos son eventos DOM, con captura y propagación, pero usualmente solo se usa el escenario de la propagación.
```suggestion
Todos los eventos son eventos DOM, con captura y propagación, pero generalmente solo se usa el escenario de la propagación.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +1. Por clave o por rango de clave. En nuestro almacén "books", puede ser por un valor o por un rando de `book.id`.
```suggestion
1. Por clave o por rango de claves. En nuestro almacén "books", puede ser por un valor o por un rango de valores de `book.id`.
```

2021-08-02 14:44 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +- `IDBKeyRange.only(key)` -- es un rango que consiste de solamente una clave `key`, es raramente usado.
```suggestion
- `IDBKeyRange.only(key)` -- es un rango compuesto solamente por una clave `key`, es raramente usado.
```

2021-08-03 13:04 UTC, jespadas requested changes

2021-08-03 13:04 UTC, jespadas commented on 6-data-storage/03-indexeddb/article.md
> +## Abrir una base de datos, "open"
No estoy seguro que esté bien expresada esta frase.

2021-08-03 13:04 UTC, jespadas commented on 6-data-storage/03-indexeddb/article.md
> +// deleteRequest.onsuccess/onerror para rastrear el resultado
se experesa mejor así : rastrea el resultado (es implícito que se refiere al concepto de la izquierda.

2021-08-03 13:13 UTC, joaquinelio commented
esto ya atenta con la autoestima, crei qu mi fuerte era el buen uso del idioma 
fue creo el articulo mas arduo de los que traduje

aplique rapidamente solamente las evidentes (asi oculto las que me avergonzaban ja)
alguna considero quedo con error,
otras tengo que meditarlas, no gramatica sino conceptos y tiempos secuencias 
una esta perfecta pero tengo duda de origen, cometi pecado de reinterpretarlo y desvie el original
vuelvo mas tarde

**_aqui_**. 
sigo con la intriga, siempre lo asumi como la minima localidad que permite el contexto,
si no , es una palabra que no tiene razon de existencia
si uno dice
"aqui y ahora
casi esta viendo el dedo apuntando al piso

2021-08-03 13:24 UTC, joaquinelio commented
hola @jespadas 
sorpresa, 5 meses sin revisores y hoy cumplimos con los dos x PR
te presento a @vrivas probablemente conmejor manejo de idioma que yo

diviertanse vuelvo luego
quizas prefieran a que uno termine antes de seguir el otro

2021-08-03 13:37 UTC, joaquinelio commented on 6-data-storage/03-indexeddb/article.md
> +// deleteRequest.onsuccess/onerror para rastrear el resultado
de acuerdo. pecadillo traductor, de cambiar el estilo. 
el 1er icono sobre herramienta, izquierda de `H B I `
podes editar la linea como sugerencia, me aparece un boton que si acepto la incorpora directamente 
y ambos escribimos menos

2021-08-03 13:48 UTC, jespadas commented on 6-data-storage/03-indexeddb/article.md
> +// deleteRequest.onsuccess/onerror para rastrear el resultado
No, lo decía porque me pediste que revise algunos y tocó este. Pero nada grave. Yo podría ayudarte a hacer revisiones pero me ayudaría más si me dices cuáles para no pasar los dos por las mismas y poder ganar tiempo.

Otra cosa, no me permite hacer PR de los dos artículos que ya tengo listos :/ no entiendo porqué.

2021-08-03 14:04 UTC, vrivas commented
> **_aqui_**.
> sigo con la intriga, siempre lo asumi como la minima localidad que permite el contexto,
> si no , es una palabra que no tiene razon de existencia
> si uno dice
> "aqui y ahora
> casi esta viendo el dedo apuntando al piso

Creo que es porque quizá le damos a "aquí" una interpretación muy "física", de un lugar físico concreto, y no tanto de un documento.

No le des muchas más vueltas, si te cuadra "aquí", no hay por qué cambiarlo.

2021-08-03 14:10 UTC, vrivas commented
> hola @jespadas
hola @jespadas 
> sorpresa, 5 meses sin revisores y hoy cumplimos con los dos x PR
Es lo que tienen las vacaciones en agosto :)

> te presento a @vrivas probablemente conmejor manejo de idioma que yo
 heso ez dixcutivle :D 
 
> diviertanse vuelvo luego
> quizas prefieran a que uno termine antes de seguir el otro

La revisión de #495 también está pendiente. ¿Qué me dices @jespadas? ¿sigues tú con esta (#491) y tomo yo la #495? ¿O lo hacemos al revés?

2021-08-03 14:13 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +## Abrir una base de datos, "open"
Para mí es un término apropiado. Al menos, cuando explicamos BBDD a nuestros estudiantes abrimos de "abrir" la BBDD.

2021-08-04 02:39 UTC, joaquinelio commented
la superposición no es problema en sí, el procedimiento prevé 2 revisores por traduccion

podemos apegarnos al espiritu del sistema "lo que me de la gana"

@jespadas, habia pedido ayuda con revs porque no esperaba tal abrumadora multitud de 2, si seguis con ganas de traducir, es lo que sugiero

@vrivas viniste dispuesto a revisar, pues podes seguir ayudando si es tu deseo

yo en cambio que no tengo ganas de hacer nada,, apenas vere si susy tiene algo que valga, no mas.

(*susy = super-sync,  merge desde repo ingles)

2021-08-04 04:10 UTC, joaquinelio commented on 6-data-storage/03-indexeddb/article.md
> +En algunas situaciones, podemos querer manejar el fallo (por ejemplo, intentar otra petición), sin cancelar los cambios en curso, y continuar la transacción. Eso es posible. El manejador `request.one
no aplico fix para recordarme q hay otra coma q quitar  ,sin

2021-08-04 07:04 UTC, jespadas commented
> > hola @jespadas
> 
> hola @jespadas
> 
> > sorpresa, 5 meses sin revisores y hoy cumplimos con los dos x PR
> 
> Es lo que tienen las vacaciones en agosto :)
> 
> > te presento a @vrivas probablemente conmejor manejo de idioma que yo
> 
> heso ez dixcutivle :D
> 
> > diviertanse vuelvo luego
> > quizas prefieran a que uno termine antes de seguir el otro
> 
> La revisión de #495 también está pendiente. ¿Qué me dices @jespadas? ¿sigues tú con esta (#491) y tomo yo la #495? ¿O lo hacemos al revés?

Tomo la #495 !

2021-08-07 06:55 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Podemos tener muchas bases de datos con nombres diferentes, pero todas deben existir dentro del mismo origen (dominio/protocolo/puerto). Un sitio web no puede acceder bases de datos de otro.
Creo que el original es correcto: puedes tener muchas bases de datos, pero todas ella solo están disponibles (¿=existen?) para el mismo origen.

2021-08-07 06:56 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +## Abrir una base de datos, "open"
Apertura me parece mucho mejor.
Agregar "open", también.

2021-08-07 16:48 UTC, vrivas reviewed
Creo que ya he terminado la revisión "gorda".
Seguro que si volvemos a leerla, saldrán muchas cosas más que revisar... pero no se trata de entrar en un bucle infinito.
@joaquinelio Acepta/rechaza lo que veas claro; discutimos lo que haya dudas; y publicamos cuanto antes.

¡Animo!

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Primero, hacer `fetch` y preparar todos los datos que fueran necesarios, y solo entonces crear una transacción y ejecutar todas las peticiones de base de datos. Así, funcionaría.
```suggestion
Primero, hacer `fetch` y preparar todos los datos que fueran necesarios y, solo entonces, crear una transacción y ejecutar todas las peticiones de base de datos. Así, funcionaría.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +En algunas situaciones, podemos querer manejar el fallo (por ejemplo, intentar otra petición), sin cancelar los cambios en curso, y continuar la transacción. Eso es posible. El manejador `request.one
Eliminada la coma

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Entonces, las peticiones que que devuelvan muchos valores siempre serán devueltos ordenados por clave.
```suggestion
Entonces, las peticiones que devuelvan muchos valores siempre serán devueltos ordenados por clave.
```

Corrección necesaria "que que"

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Entonces, las peticiones que que devuelvan muchos valores siempre serán devueltos ordenados por clave.
```suggestion
Entonces, siempre que una petición devuelva muchos valores, estos estarán ordenadores por la clave.
```
Redacción alternativa.

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Primero necesitamos crear un índice. Esto debe hacerse en `upgradeneeded`, igual que ObjectStore.
Creo que este "ObjectStore" es incorrecto, por no termino de encontrar una forma correcta de traducirlo.
Propuesta:
```suggestion
Primero necesitamos crear un índice. Esto debe hacerse en `upgradeneeded`, al igual que hacíamos la creación del almacén de objetos.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Si queremos borrar libros basados en un precio u otro campo del objeto, debemos primero encontrar la clave en el índice, luego llamar a `delete` con él:
```suggestion
Si queremos borrar libros basados en un precio u otro campo del objeto, debemos primero encontrar la clave en el índice, luego llamar a `delete` con dicha clave:
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Los cursores brindan los medios para trabajar con eso.
```suggestion
Los cursores brindan los medios para manejar esta situación.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +**Un *cursor* es un objeto especial que, dada una consulta, recorre el almacén y devuelve un par clave/valor a la vez, así ahorrando memoria.**
```suggestion
**Un *cursor* es un objeto especial que, dada una consulta, recorre el almacén y devuelve un solo par clave/valor cada vez, ahorrando así memoria.**
```

Creo que "un solo" hace el mismo efecto de énfasis que el "one" del original; de la misma fornma que ellos no usan "a key/value" sino "one key/value", podríamos nosotros usar el "un solo".

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +  - `"nextunique"`, `"prevunique"` -- igual que las anteriores, pero saltando los registros con la misma clave (válido solo para cursores sobre índices. Por ejemplo, de múltiples libros con price=5,
```suggestion
  - `"nextunique"`, `"prevunique"` -- igual que las anteriores, pero saltando los registros con la misma clave (válido solo para cursores sobre índices; por ejemplo, de múltiples libros con price=5, solamente el primero será devuelto).
```
Me resulta extraño que el paréntesis comience en una oración y termine en otra totalmente distinta; por eso usar el ",".

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +El evento `onsuccess` será llamado haya o no más valores coincidentes, y en `result` obtenemos el cursor apuntando al siguiente registro, o `undefined`.
```suggestion
El evento `onsuccess` será llamado haya o no más valores coincidentes, y en `result` obtenemos el cursor apuntando al siguiente registro o `undefined`.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +En el ejemplo anterior el cursor fue hecho sobre el almacén de objetos.
```suggestion
En el ejemplo anterior, el cursor fue hecho sobre el almacén de objetos.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Pero también podemos hacerlo sobre un índice. Recordamos, los índices nos permiten buscar por los campos del objeto. Los cursores sobre índices hacen precisamente lo mismo que sobre el almacén de obj
```suggestion
Pero también podemos hacerlo sobre un índice. Recordamos, los índices nos permiten buscar por los campos del objeto. Los cursores sobre índices hacen precisamente lo mismo que sobre el almacén de objetos: ahorran memoria al devolver un solo valor cada vez.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +## Contenedor promisificador
Nunca he visto la palabra promisificador.
Lo cual no signigica que esté mal.

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Agregar `onsuccess/onerror` a cada petición es una tarea agobiante. A veces podemos hacernos la vida más fácil usando delegación de eventos, es decir establecer manejadores para las transacciones com
```suggestion
Agregar `onsuccess/onerror` a cada petición es una tarea agobiante. A veces podemos hacernos la vida más fácil usando delegación de eventos (por ejemplo, estableciendo manejadores para las transacciones completas), pero `async/await` es mucho más conveniente.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Usemos en adelante para este capítulo un contenedor (wrapper) liviano que añade promesas <https://github.com/jakearchibald/idb>. Este crea un objeto global `idb` con métodos IndexedDB [promisificados
```suggestion
Usemos en adelante para este capítulo un contenedor (wrapper) liviano que añade promesas <https://github.com/jakearchibald/idb>. Este contenedor crea un objeto global `idb` con métodos IndexedDB [promisificados](info:promisify).
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Si no atrapamos un error, este se propaga hasta el más `try..catch` externo más cercano.
```suggestion
Si no atrapamos un error, este se propaga hasta el `try..catch` externo más cercano.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +Como sabemos, una transacción se autofinaliza tan pronto como el navegador termina el código actual y las microtareas. Entonces si ponemos una *macrotarea* como `fetch` en el medio de una transacción
```suggestion
Como sabemos, una transacción se autofinaliza tan pronto como el navegador termina el código actual y las microtareas. Por tanto, si ponemos una *macrotarea* como `fetch` en el medio de una transacción, la transacción no esperará a que termine. Simplemente se autofinaliza. Así la siguiente petición fallaría.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +El `inventory.add` que sigue a `fetch` `(*)` falla con el error "transacción inactiva", porque la transacción se autocompletó y para ese momento ya está cerrada.
```suggestion
El `inventory.add` que sigue a `fetch` `(*)` falla con el error "transacción inactiva", porque la transacción se autocompletó y, llegado ese momento, ya está cerrada.
```

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +let promise = books.add(book); // obtener una promesa (no espera por su resultado)
```suggestion
let promise = books.add(book); // obtiene una promesa (no espera por su resultado)
```

Creo que, en todos los ejemplos anteriores, siempre se ha usado presente de indicativo en estos comentarios de código.

2021-08-07 16:48 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +IndexedDB puede ser pensado como "localStorage con esteroides". Es una simple base de datos de clave-valor, suficientemente poderosa para apps fuera de línea y fácil de usar.
```suggestion
IndexedDB puede considerarse como "localStorage con esteroides". Es una simple base de datos de clave-valor, suficientemente poderosa para apps fuera de línea y fácil de usar.
```

2021-08-07 17:44 UTC, joaquinelio commented on 6-data-storage/03-indexeddb/article.md
> +Podemos tener muchas bases de datos con nombres diferentes, pero todas deben existir dentro del mismo origen (dominio/protocolo/puerto). Un sitio web no puede acceder bases de datos de otro.
Queria que quedara claro "origen", que el vínculo con el server de creacion es permanente.
Pero abiendo que es una cookie con esteroides, queda claro.
La db esta vinculada a dominio/protocolo/puerto/home usuario/browser

2021-08-07 18:06 UTC, joaquinelio commented on 6-data-storage/03-indexeddb/article.md
> +Entonces, las peticiones que que devuelvan muchos valores siempre serán devueltos ordenados por clave.
¿y si devuelve pocos?

2021-08-07 19:29 UTC, joaquinelio commented on 6-data-storage/03-indexeddb/article.md
> +## Contenedor promisificador
La inventamos porque tiene dedicado un articulo.
WRAPPER es otra palabra que me resistía atraducir (¿contenedor? ¿Envoltorio, envoltura?), pero el consorcio es el consorcio y a aguantarse el color de los pasillos.

2021-08-07 20:45 UTC, joaquinelio commented
@vrivas 
¡Ya pero YA! No máas de un semestre más.
muy buena rev, edite un par de cositas.

cuando me quejo de laas comas,no es especiicamente las comas sino la contruccion.  
fuiste eficaz lidiando con eso, no es solo gramatica lo q arreglaste

MERGE
sig suggest, pr a master
poodes mirar este pr para comparar o mirarlo online para una rev fresca... o para admirarlo nomas.

2021-08-07 20:45 UTC, merged

2021-08-07 21:29 UTC, vrivas commented on 6-data-storage/03-indexeddb/article.md
> +## Contenedor promisificador
Contenedor me ha parecido correcto.

2021-08-07 21:35 UTC, vrivas commented
¡Excelente trabajo, @joaquinelio!
Ha sido un placer y he aprendido muchísimo.
Intentaré seguir revisando otros capítulos.