Focusing: focus/blur
javascript-tutorial/es.javascript.info pull request #527
Opened 2021-07-14 10:37 UTC by j-llano

2021-07-14 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=527) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=527) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=527) it.</sub>

2021-07-15 00:23 UTC, joaquinelio requested changes
hello gracias me estaba sintiendo solo
Muy bueno
Algunos detalles que podes aceptar/ignorar,
Otros son por el raro "--", aceptalos o cambialos,
Me hiciste dudar con "utilicemolos", no se si "..mos-los" es el mismo caso que "..mos-nos",  y como no sé, lo dejo.  Deberia preguntar a fundeu.
Ah, y ponele aceite a la barra de espacio  =)

2021-07-15 00:23 UTC, joaquinelio commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +El ejemplo anterior nu funciona porque cuando el usuario enfoca sobre un <input> el evento ´focus´ se inicia solamente sobre esa entrada, no se propaga, por lo que `form.onfocus` nunca se inicia.
```suggestion
El ejemplo anterior no funciona porque cuando el usuario enfoca sobre un <input> el evento ´focus´ se inicia solamente sobre esa entrada, no se propaga, por lo que `form.onfocus` nunca se inicia.
```

2021-07-15 00:23 UTC, joaquinelio commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +  // pon el manejador en fase de captura (último argumento cierto)
```suggestion
  // pon el manejador en fase de captura (último argumento "verdadero")
```

o "true"
no perdamo el foco  =)

2021-07-15 00:23 UTC, joaquinelio commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +Además, existen los eventos `focusin` and `focusout` -- exactamente igual que `focus/blur` pero se propagan.
```suggestion
Además, existen los eventos `focusin` and `focusout`: exactamente igual que `focus/blur` pero se propagan.
```

2021-07-15 00:23 UTC, joaquinelio commented on 2-ui/4-forms-controls/2-focus-blur/article.md
> +-No se propagan. Se puede capturar el estado o `focusin/focusout`.
No es claro el original ingles
podrias mandarle un PR al ruso...

```suggestion
-No se propagan. En su lugar se puede capturar el estado o usar `focusin/focusout`.
```

2021-07-15 01:28 UTC, joaquinelio commented
Actualicé la lista del progress con tu usuario y pr,
estuvo inactiva por 4 meses

2021-07-20 10:08 UTC, j-llano commented
Tengo un poco de tiempo estos días así que intentaré traducir algo más. 
pd: ya he echado la bronca a la barra de espacio.

2021-07-20 12:53 UTC, joaquinelio commented
**el procedimiento esta en el issue #17**
(se reclama articulo poniendo el coment en el #17, el bot aprueba si esta disponible)
y el resumen del ultimo progreso esta en mi ultimo coment ahi

veras en este PR que te salio esto 
`Error: the article has another translator @ in the Progress Issue #17.`
porqye estaba reclamado por otro traductor

ignorando a don Bot, cambie a mano el issue 17 y puse tu nombre porque lleva 4 meses sin movimiento

plis revisa el #17
del ultimo coment podes elegir cualquier art SIN PR 
y me avisas alli que borro el traductor porque ninguno es mas nuevo que 3 meses
O
si te animas podes hacer review de los 3 PR ya traducidos que estan pendientes

2021-07-20 14:25 UTC, joaquinelio approved these changes

2021-07-20 14:28 UTC, joaquinelio commented
!Incorporado!

@j-llano  plis lee lo que puse de los articulos ya traducidos

2021-07-20 14:28 UTC, merged

2021-07-20 14:30 UTC, joaquinelio commented
@j-llano 
 seguimos procedimiento y Don Bot se puso contento.

2021-07-20 15:19 UTC, joaquinelio commented
@j-llano 
olvide verificar, online veo que tiene tasks
tambien pendientes de traduccion