ArrayBuffer, binary arrays
javascript-tutorial/es.javascript.info pull request #532
Opened 2021-07-24 22:06 UTC by jespadas

2021-07-24 22:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=532) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=532) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=532) it.</sub>

2021-07-24 22:49 UTC, joaquinelio commented
hola @jespadas 
Todavia no hago la rev, pero anoto:

* Revisa si tiene "tasks", cada tarea tiene su subdirectorio (aca parece solo una linea, mas rapido para mi si la edito en github)
* Es importante respetar el estilo y los tiempos,  pero la gramatica tiene prioridad. Mmm... mentira. La fluidez es mas importante. 
* Respetar  los numeros  de linea,  es importante cuando hacemos MERGE desde el repo ingles.
*

2021-07-25 00:05 UTC, joaquinelio requested changes
No la terminé,
¿podrias corregir la numeracion de lineas? Me es dificil corregirlo dentro de github
 
No es solo el numero de linea que me sería facil corregir, tambien  
aparecio un 4 de la nada (114)
hay metadata separada (deja de funcionar -no puedo recordar donde sorry)
y lineas partidas no solo formato sino el sentido, p ej  1 linea (118)  se transformo en 3 (124 125 126) y se confunde con el codigo 

no aflojes plis esto estuvo lonely los ultimos meses =)

2021-07-26 14:44 UTC, jespadas commented on 4-binary/01-arraybuffer-binary-arrays/article.md
Entiendo, lo hice porque habia un error de sintaxis en el archivo original y hacia que una gran parte del documento se vea fuera de forma.

2021-07-26 14:44 UTC, jespadas commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +Aunque, hay un poco de confusión, porque hay muchas clases. Por nombrar algunas:
Es verdad, lo voy a revisar ahora.

2021-07-26 14:55 UTC, jespadas commented
/done

2021-07-26 17:51 UTC, joaquinelio requested changes
Sigue el problema de la numeracion, tu articulo es casi 10 lineas mas largo.  Si dejara as´i el merge desde el ingles saldria siempre mal.
 
No se cual es el "err de sintaxis" original, plis no confundas con el markup dentro del codigo.   No uses correctores de estilo, rompen la estructura.

Me muerdo la lengua con la recomendacion de quitar comas...  
hay casos en que la estructura lo exige, ahora pecamos de falta y la gramatica queda mal.
La coma no marca pausas sino estructura. Pero ante la duda prefiero la fluidez (lo correcto seria rescribir la linea pero no vienen de la RAE a auditarnos) 

Leiste el coment de la numeracion de lineas? Por ej la linea 118 que separaste en 3 quedó sin sentido. 
Para corrregirlo tendraas que comparar linea x linea con el ingles. Si tu editor lo permite, lo recomiendo.  En vscode usaba extension "gitlens" pero le pusieron mejoras y se volvio engorroso, a veces prefiero usar 2 ventanas separadas.

2021-07-26 18:08 UTC, jespadas commented
He corregido el número de líneas, regrese al estado original el error que a mi parecer lo tiene el repositorio original. Por lo de las comas, debemos ponernos de acuerdo porque yo lo deje con ciertas pausas ya que para mi la fluides implica otra forma de la que me pides.

2021-07-26 18:08 UTC, jespadas commented
/done

2021-07-26 21:49 UTC, joaquinelio commented
Acabo de ver lo que creo que ves como error.  Pero lo tengo que entender mejor. 
Si es error, mandamos el PR al ingles.
Por norma lo corrijo primero en inglés.  A veces rechaza el cambio o lo arregla de otra forma.

Comas: Poné todas las que quieras que no te reprimo más, en cambio solo anoto:
*A veces 2 comas actuan como un separador que se lee como si estuviera entre parentesis, eso esta mal cuando la frase pierde coherencia. Acá es donde me quejo (ej linea 7, creo que yerra mucho asi en ingles pero un corrector nativo me lo negó. Quizas confundo los casos). 
*No siempre se puede quitar o reemplazar con "y". No conviene si la idea importante se confunde y esto es importante en un tutorial. No sigo reglas gramaticales, veo qué quiere comunicar y si se lee cómodo (la gramatica ayuda).
Si queres devolver las comas, no problem. Sorry por el incordio.

Me pongo a revisarlo.

2021-07-26 23:55 UTC, joaquinelio requested changes
no veo que haya err de sintaxis,
online se ven y funcionan

2021-07-26 23:55 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +Pero si vamos a escribir en él o a iterar sobre él básicamente para casi cualquier operación, debemos utilizar una vista, por ejemplo:
uf!

```suggestion
Pero si vamos a escribir en él, o iterar sobre él (básicamente, para casi cualquier operación), debemos utilizar una vista. Por ejemplo:
```

aca requiere las comas. 
Entre sujeto y predicado no se pone coma. La excepcion es esta, cuando uno pone un bloque entre comas. Y aca se complica más porque el bloque es una lista, que lleva varias.

1) si el "básicamente" fuera una aclaracion superflua, se separaria con comas:
`Pero si vamos a escribir en él o a iterar sobre él, **básicamente para casi cualquier operación**, debemos utilizar una vista, por ejemplo:`
se leeria
`Pero si vamos a escribir en él o a iterar sobre él ( ... ) debemos utilizar una vista, por ejemplo:`

2)  en cambio aca el "básicamente"  parece parte de una lista  (escribir/iterar/cualquier) , tmbien requiere comas
`Pero si vamos a escribir en él, o a iterar sobre él, o, básicamente, para casi cualquier operación, debemos utilizar una vista, por ejemplo:` (no se explicar las comas de la conjuncion y el basicamente)

demasiado ardua lectura para un concepto tan simple. Por eso recomiendo cortarlo.

2021-07-26 23:55 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +2. Si se da un `Array` o cualquier objeto tipo array se crea un array tipado de la misma longitud y se copia el contenido.
```suggestion
2. Si se da un `Array`, o cualquier objeto tipo array, se crea un array tipado de la misma longitud y se copia el contenido.
```
aca sí van las 2 comas, lo que va dentro es un bloque aclaratorio autonomo, 
y esa es la coma permitida antes del predicado
sin el bloque queda coherente
"Si se da un `Array` se crea un... "

2021-07-26 23:55 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +// otro punto de vista sobre los mismos datos
mmm...

pref seguir con vistas
```suggestion
// otra vista sobre los mismos datos
```

2021-07-26 23:55 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
>  ```warn header="No `int8` or similar single-valued types"
```suggestion
```warn header="No existe `int8` o tipos de valor único similares"
```

2021-07-26 23:55 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +`TypedArray` tiene métodos regulares de `Array`, con notables excepciones.
```suggestion
`TypedArray` tiene los métodos regulares de `Array`, con notables excepciones.
```

2021-07-26 23:55 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +- `arr.subarray([begin, end])` crea una nueva vista del mismo tipo desde `begin` hasta `end` (exclusivo). Es similar al método `slice` (que también está soportado), pero no copia nada sólo crea una n
ojo no estoy seguro, excluye end?

de la coma sí.

```suggestion
- `arr.subarray([begin, end])` crea una nueva vista del mismo tipo desde `begin` hasta `end` (excluyéndolo). Es similar al método `slice` (que también está soportado) pero no copia nada, sólo crea una nueva vista para operar sobre el trozo de datos dado.
```

2021-07-26 23:55 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +Para hacer casi cualquier operación sobre `ArrayBuffer`, necesitamos una vista.
no va coma ante ese verbo
pero no me importa XD

2021-07-28 15:22 UTC, jespadas commented
/done

2021-07-28 16:51 UTC, joaquinelio approved these changes

2021-07-28 16:51 UTC, joaquinelio commented on 4-binary/01-arraybuffer-binary-arrays/article.md
> +    Opcionalmente podemos proporcionar `byteOffset` para empezar (0 por defecto) y la `length` (hasta el final del buffer por defecto), entonces la vista cubrirá sólo una parte del `buffer`.
```suggestion
    Opcionalmente podemos proporcionar `byteOffset` para empezar (0 por defecto) y la longitud o `length` (hasta el final del buffer por defecto), entonces la vista cubrirá sólo una parte del `buffer`.
```

2021-07-28 16:52 UTC, merged

2021-07-28 17:26 UTC, joaquinelio commented
biutiful