Shadow DOM and events
javascript-tutorial/es.javascript.info pull request #550
Opened 2021-10-02 12:39 UTC by joaquinelio

2021-12-14 14:55 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +La idea detrás del árbol shadow es encapsular los detalles internos de implementación de un componente.
```suggestion
La idea detrás del shadow tree es encapsular los detalles internos de implementación de un componente.
```

2021-12-14 14:57 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +La idea detrás del árbol shadow es encapsular los detalles internos de implementación de un componente.
La palabra compuesta `show tree` no debe ser traducido asi como `shadow host`, `shadow boundary` o `shadow root`

2021-12-14 16:09 UTC, dbritto-dev requested changes

2021-12-14 16:09 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +Los eventos solo cruzan los límites de shadow DOM si sus banderas `composed` se setean en `true`.
```suggestion
Los eventos solo cruzan los límites de shadow DOM si su bandera `composed` se establece como `true`.
```

2021-12-14 16:09 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +Observa que en caso de componentes anidados, un shadow DOM puede estar anidado dentro de otro. En ese caso los eventos se propagan a través de los límites de todos los shadow DOM. Entonces, si se pre
```suggestion
Tenga en cuenta que en caso de componentes anidados, un shadow DOM puede estar anidado dentro de otro. En ese caso los eventos se propagan a través de los límites de todos los shadow DOM. Entonces, si se pretende que un evento sea solo para el componente inmediato que lo encierra, podemos enviarlo también en el shadow host y establecer `composed: false`. Entonces saldrá al shadow DOM del componente, pero no se propagará hacia un DOM de mayor nivel.
```

2021-12-14 16:09 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +Si enviamos un evento personalizado `CustomEvent`, debemos setearle explícitamente `composed: true`.
```suggestion
Si enviamos un evento personalizado `CustomEvent`, debemos establecer explícitamente `composed: true`.
```

2021-12-14 16:09 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +Cuando enviamos eventos personalizados, necesitamos setear ambas propiedades `bubbles` y `composed` a `true` para que se propague hacia arriba y afuera del componente.
```suggestion
Cuando enviamos eventos personalizados, necesitamos establecer ambas propiedades `bubbles` y `composed` a `true` para que se propague hacia arriba y afuera del componente.
```

2021-12-14 16:09 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +Por ejemplo, si un usuario hace clic en `<span slot="username">` en el ejemplo debajo, el target del evento es precisamente ese elemento `span` para ambos manejadores de eventos, el shadow y el light
```suggestion
Por ejemplo, si un usuario hace clic en `<span slot="username">` en el ejemplo siguiente, el objetivo del evento es precisamente ese elemento `span` para ambos manejadores, shadow and light.
```

2021-12-14 16:09 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +## Propagación, event.composedPath()
```suggestion
## Propagando, event.composedPath()
```

2021-12-14 16:10 UTC, dbritto-dev commented
@joaquinelio  todo tuyo :D

2021-12-14 17:11 UTC, joaquinelio commented
gracias!!! @dbritto-dev 
gúilcombác
 
### shadow-??????
Uf. Lo voy a poner como issue.  Hay que cepillar el repo con esto. 

AHORA estoy de acuerdo,
es usual que aparezca en codigo o como propiedad element.shadowRoot
pero no me vas a convencer de que "shadow and light" es una palabra compuesta.

### setear
demasiado usual y se me escapo... pero acordate, los que usamos estas pocas aberraciones vamos a lograr que el drae las registre.

etc.
gracias, volveré luego

2021-12-14 19:22 UTC, dbritto-dev commented
> gracias!!! @dbritto-dev gúilcombác
> 
> ### shadow-??????
> Uf. Lo voy a poner como issue. Hay que cepillar el repo con esto.
> 
> AHORA estoy de acuerdo, es usual que aparezca en codigo o como propiedad element.shadowRoot pero no me vas a convencer de que "shadow and light" es una palabra compuesta.
> 
> ### setear
> demasiado usual y se me escapo... pero acordate, los que usamos estas pocas aberraciones vamos a lograr que el drae las registre.
> 
> etc. gracias, volveré luego

falto traducir el `and` en `shadow and light`, hahaha :)

2021-12-16 00:19 UTC, joaquinelio commented on 8-web-components/7-shadow-dom-events/article.md
> +**Los eventos que ocurren en shadow DOM, cuando son atrapados fuera del componente, tienen el elemento host como target.**
te parece claro?  asi se entiende pero cansa leerlo...
pero ok

2021-12-16 00:23 UTC, joaquinelio commented on 8-web-components/7-shadow-dom-events/article.md
> +## Propagación, event.composedPath()
es correcto, 
pero me suena feo...
¿cuanto insistis con esto? me dejo convencer facil

2021-12-16 00:26 UTC, joaquinelio commented
/done

2021-12-16 00:30 UTC, joaquinelio commented
mentira /done, ¿si hago el ultimo commit puedo darle merge? 

¡falta un solo articulo para terminar el repo!!
y estos 2 pr, si queres podes echarle un vistazo al otro... 
**especialmente si usaste regex**

2021-12-16 04:53 UTC, dbritto-dev commented on 8-web-components/7-shadow-dom-events/article.md
> +## Propagación, event.composedPath()
@joaquinelio yo creo que lo dejamos como Propagación

2021-12-16 04:56 UTC, dbritto-dev approved these changes

2021-12-16 12:10 UTC, joaquinelio commented
biutiful

2021-12-16 12:11 UTC, merged