minorFixes
javascript-tutorial/es.javascript.info pull request #648
Opened 2022-08-15 13:46 UTC by d-caldasCaridad

- he agregado actualizaciones y correcciones
- "Step" lo llamé "Acción"
- "Step over" lo llamé "El paso siguiente"
- "Step into" lo llamé "..."
- faltaban algunas líneas...
Y es todo...

2022-08-15 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=648) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/es.javascript.info?pullRequest=648) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/es.javascript.info?pullRequest=648) it.</sub>

2022-08-15 13:54 UTC, d-caldasCaridad reviewed
Satisfecho un 99%

2022-08-15 14:03 UTC, d-caldasCaridad commented
:D

2022-08-15 20:58 UTC, joaquinelio requested changes
hola y gracias

tengo q arreglar mi noteb si quiero hacer buena review

pero hay conflictos, estas trabajando con un repo desactualizado, algunas lineas del master se modificaron 3 julio

traduccion:
bien por españolizar debug y clic

puedes vs puede no hibo acuerdo entre maintainers, aolo espero q sea coherente dentro del artículo 

cambiaria, si tenes ganas, todos  los "debug" 
 conjugadoa por el wspañol depurar,
y aclarar una sola vez en las 1ras lineas "depurar (debug en ingles)"

los comandos de chrome (como  step into) poner lo aue pone chrome en español, el mio lo tengo en ingles, no verifiqué por perezoso

tamb tengo q verificar qu loa nro d linea coincidan con el repo ingles, si no cuando hacemos merge desde ingles el merge se tara...
por eso la review se complica

2022-09-05 19:15 UTC, joaquinelio commented
ups! olvide nombrarte @d-caldasCaridad 

resumo:
figuran conflictos porque el articulo ya habia sido modificado

quizas tu pr tenga cosas valiosas (términos que no habian sido traducidos por ej) 
pero tendras que actualizar tu branch primero

2022-09-06 06:01 UTC, d-caldasCaridad commented
Sr. @joaquinelio por favor tenme paciencia porque soy nuevo en esto de manejar GitHub, JS...
Estoy de acuerdo con tu criterio y con el de los mantenedores, además muy contento de tener la oportunidad de participar en este proyecto.

2022-09-09 12:52 UTC, joaquinelio commented
Mi primer PR fue en este repo y empece mal, se me mezclaban  los aportes pues no sabia nada de los branch. Me ayudaron, y segui aportando.
Se aprende.

2023-03-01 10:35 UTC, closed without merging